### ISSUE TITLE
Add pause and resume for iOS AVSpeechSynthesizer

### ISSUE THREAD

**Issue by futurnaingenieur** [dlutton/flutter_tts#100]
## 🚀 Feature Requests

It would be amazing to be able to pause and resume tts on iOS since we unfortunately cannot synthesise to file with AVSpeechSynthesizer.

### Describe the feature
I think AVSpeechSynthesizer supports this already by using pauseSpeaking and continueSpeaking . (See [https://developer.apple.com/documentation/avfoundation/avspeechsynthesizer#//apple_ref/occ/instp/AVSpeechSynthesizer/paused](url)).

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by dlutton** [comment]
This has been added to the latest version.
