### ISSUE TITLE
down vote favorite String is read as number rather than reading it digit by digit

### ISSUE THREAD

**Issue by lollita** [dlutton/flutter_tts#101]
I have a string "9039662543", and when speak is on, this string is read as "nine million....".
Do it is possible to read as "nine zero three..."?

**Comment by dlutton** [comment]
@lollita is this occurring on Android, iOS, or both?

**Comment by lollita** [comment]
Mainly for Android but welcome also for iOS.

**Comment by coldembrace** [comment]
@lollita just insert a single space after each char e.g. `9039662543` => `9 0 3 9 6 6 2 5 4 3` and you'll get the desired output.

**Comment by dlutton** [comment]
@lollita let me know if @coldembrace's solution will work for you.

**Comment by lollita** [comment]
It work fine. Ty.

**Comment by faliqulamin** [comment]
Hello @dlutton @coldembrace 
How to give pause or gap between number?

**Comment by dlutton** [comment]
@faliqulamin as @coldembrace mentioned, insert a single space after each char.

**Comment by faliqulamin** [comment]
thank you @dlutton,
but i mean, there is function that give delay between char?
