### ISSUE TITLE
 The same code can be played on Android 8, but not on Android 10

### ISSUE THREAD

**Issue by i-jade** [dlutton/flutter_tts#105]
## 💬 Questions and Help
Thank you for developing such a good plugin。
I recently had this problem when using plugins for simple tests：The same code can be run normally on my Huawei  EMUI8.0 (Android 8), but not on my OnePlus 7T (Android 10)，The `flutterTts.speak ()`function on my OnePlus7T has no return value. My code is as follows:
```
 void initTTS() async {
    flutterTts = FlutterTts();
    await flutterTts.setLanguage("en-US");
    await flutterTts.setSpeechRate(1.0);
    await flutterTts.setVolume(1.0);
    await flutterTts.setPitch(1.0);
    flutterTts.setErrorHandler((handler) {
      print(handler);
    });
  }

  Future _speak() async {
    var result = await flutterTts.speak("这是一个报警信息");
    print(result);
  }

  Future _stop() async {
    var result = await flutterTts.stop();
    //if (result == 1) //setState(() => ttsState = TtsState.stopped);
  }

```
I called `initTTS ()` in the `initState()` function, I called `_speak ()` in the `onTap ()` function, there are no errors on EMUI8, there is a problem on OnePlus7T, and no error message appears. So How can I solve this problem? thank you very much!

**Comment by dlutton** [comment]
If you change the language, is it able to speak the characters?

**Comment by i-jade** [comment]
> If you change the language, is it able to speak the characters?

I just tested en-GB, zh-TW, es-US, and it didn't work. By the way, I ran your example demo on my OnePlus7T, and unlike EMUI, there is no language choice
![jpg](https://i.loli.net/2020/05/05/bPDC5GxORejWFBv.jpg)

**Comment by dlutton** [comment]
Have you confirmed the TTS engine being used on your OnePlus?

**Comment by i-jade** [comment]
> Have you confirmed the TTS engine being used on your OnePlus?

Thank you very much, this problem has been solved. My onePlus does not have a built-in TTS engine, I can successfully run it after downloading the Google text-to-speech engine.
