### ISSUE TITLE
tts.stop() without triggering completionHandler

### ISSUE THREAD

**Issue by coldembrace** [dlutton/flutter_tts#107]
## 💬 Questions and Help

Thanks for a great tts lib! 
It seems like `completionHandler` is triggering when I stop the speech programmatically. I assume that's an expected behaviour, but is there a way to prevent it?

**Comment by dlutton** [comment]
@coldembrace yes that's expected behavior at this time.  What is the purpose around preventing it?

**Comment by coldembrace** [comment]
@dlutton Thanks for the quick response! Actually I'm trying to play multiple speeches one by one.
```
await textToSpeech.setLanguage(lng1);
await textToSpeech.speak(text1);
textToSpeech.setCompletionHandler(() async {
    Future.delayed(Duration(milliseconds: 1000), () async {
        await textToSpeech.setLanguage(lng2);
        await textToSpeech.speak(text2);
        textToSpeech.setCompletionHandler(() async {
             print("all done");
         });
     });
});
```
It works fine until I call `await textToSpeech.stop()` (and completionHandler is triggering) when the first text is still speaking for example. 
Anyway, I think stop handler in iOS is also automatically triggering after AVSpeechSynthesizer's `speak` method gets called, so probably I should look for another solution.

**Comment by dlutton** [comment]
I'll test this out later when I get some time and think of an elegant solution for this situation.

**Comment by coldembrace** [comment]
@dlutton Appreciate your help!

**Comment by dlutton** [comment]
Just to confirm @coldembrace, is your use case where if stop is called, you want it to continue onto the next speech?

If you just want it to cancel altogether, you can just `await textToSpeech.speak(text2);` right after the first `await textToSpeech.speak(text1);`

**Comment by coldembrace** [comment]
@dlutton I want to cancel altogether. The issue is I really need to call my completion block somehow **only** when the second speech is done.

**Comment by dlutton** [comment]
okay, but the synthesizeToFile is only supported on Android.  Playing multiple speeches one by one works in the way I mentioned before at least for iOS, I still have to test it on Android.  When you stop, it'll cancel the whole thing.  I'll let you close the issue when you're comfortable that you have a solution, otherwise I can keep this open.

**Comment by coldembrace** [comment]
I ended up with an approach without using the completion handler (reworked my app a bit). Just calling multiple `speak` methods one by one seems working fine on both Android and iOS. @dlutton appreciate your help!
```
await textToSpeech.setLanguage(lng1);
await textToSpeech.speak(text1);
await textToSpeech.setLanguage(lng2);
await textToSpeech.speak(text2);
```
