### ISSUE TITLE
The background audio is stopped with speak completion on iOS device.

### ISSUE THREAD

**Issue by yoshoten-i-sol** [dlutton/flutter_tts#108]
## 💬 Questions and Help

Provide question related to this flutter plugin.
#99 
@wexder 
For this question, I tried to set playback or ambient to category and mixWithOthers to options but didn't working.
Then I found it's because of this code
`    
do {
      try audioSession.setActive(false, options: .notifyOthersOnDeactivation)
    } catch {
      print(error)
    }
`
that called on 
`
public func speechSynthesizer(_ synthesizer: AVSpeechSynthesizer, didFinish utterance: AVSpeechUtterance)
`
Maybe we needn't to stop the play on any mix mode because other audio didn't stopped on it.
Thank you for your hard work.

**Comment by macoshita** [comment]
Same problem. Ver. 1.2.3

This commit, but I don't know why.
I want to remove it, but If you can't remove it, I'd like the option.

https://github.com/dlutton/flutter_tts/commit/5d4c01d8bb836a59b3a1abb57a76a1a6f1e04349

**Comment by wexder** [comment]
we can add the way to pass options to audiosession. But I currently don't have time to implement it.

**Comment by marcotta** [comment]
@macoshita could you explain a bit more about your setup, I will try to help

**Comment by marcotta** [comment]
@macoshita could you confirm this commit solves your problem?
https://github.com/dlutton/flutter_tts/commit/a6cb372d41e40c09ed1ac1a8e32ffea0b6d32abc
