### ISSUE TITLE
Tts on iOS defaults to speaking to the receiver (before it was on the speaker).

### ISSUE THREAD

**Issue by eldermao1** [dlutton/flutter_tts#110]
### Expected behavior
When tts speaks I should be able to listen it on the speaker (not receiver) or at least be able to set it on the receiver by an option. I tried with `IosTextToSpeechAudioCategoryOptions.defaultToSpeaker` but it doesn't do anything.

### Reproduction steps
flutter_tts 1.2.0 + iOS hit play and you won't hear anything unless you hear on the phone's receiver.
Also, if I try using the new option `flutterTts.setSharedInstance(true);` it gives me this error:
`flutter: MissingPluginException(No implementation found for method setSharedInstance on channel flutter_tts)`

How can I make it speak to the speaker again?

Thank you!
Mauricio
### Configuration

**Version:** 1.2.0

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by dlutton** [comment]
is this still an issue with the latest build @eldermao1 ?

**Comment by eldermao1** [comment]
I dropped this library and did something else instead because it wasn't
stable so I can't test it now. Thank you for looking into it either way,
I'm sure it will help others.
