### ISSUE TITLE
Can I ask how many voices flutter_tts have? 

### ISSUE THREAD

**Issue by dinhan1192** [dlutton/flutter_tts#111]
Firstly, thank you for the great package,
But I am working on a project that needs many kinds of voices, so does flutter_tts have other kinds of voice? or only one ?
Thank you.

**Comment by dlutton** [comment]
This package uses the built in TTS engine on the device, so it depends on the device.  The get voices method should assist you with that.

**Comment by dinhan1192** [comment]
Thank you for your response !!!!

**Comment by dinhan1192** [comment]
Sorry, but I have to ask, does flutter tts provide Vietnamese language?
Thank you for your time!

**Comment by dlutton** [comment]
That also depends on the tts engine on your device.  For example, on Android, this package uses the com.google.android.tts engine on your device, so if that engine supports that locale, then it's available.  You'll want to run the get languages method to view a list of languages supported on your device.

**Comment by dinhan1192** [comment]
Oh really!! Thank you so much for your help !!! I love your flutter tts bro
!!!
