### ISSUE TITLE
Excuse me, I want to ask about Vietnamese and flutter_localizations

### ISSUE THREAD

**Issue by dinhan1192** [dlutton/flutter_tts#115]
## 💬 Questions and Help

Well, I find out that flutter_tts run well with my app that I am building. But I wonder, however, if the phone of Customer has Vietnamese installed and I set language of flutter_tts to Vietnamese, can the customer's phone still perform the task as expected (I mean text to speech). Do I have to install another package, eg: flutter_localizations ?
Thank you a lot for your effort!!!

**Comment by dlutton** [comment]
@dinhan1192 I have not tested this with another language set on the device, however I believe as long as Vietnamese is a supported TTS language on the device and it's selected, your app should work as expected.

**Comment by dinhan1192** [comment]
Thank you for your response, I tested on AVD and it worked awesome !!!
