### ISSUE TITLE
I want to ask about the pause in Android

### ISSUE THREAD

**Issue by dinhan1192** [dlutton/flutter_tts#118]
Did you have pause and continued for Android ? I did not see it in the read me, I tried testing on AVD and it still continue to speak =.=
Thank you!

**Comment by dlutton** [comment]
Unfortunately the Android TTS SDK doesn't provide a pause method.  This is only supported on iOS and will soon be implemented for web.

**Comment by dinhan1192** [comment]
Thank you for your answer!
