### ISSUE TITLE
Does it support a man's voice

### ISSUE THREAD

**Issue by yuefeng007** [dlutton/flutter_tts#121]
### Describe the feature
Does it support a man's voice

### Platforms affected (mark all that apply)
- [ √ ] :iphone: iOS
- [ √] :robot: Android

**Comment by dlutton** [comment]
You'll have to do a get voices call to see what's available on the tts engine on your device.

**Comment by kamleshwebtech** [comment]
How can I get voices call in dart? Kindly suggest. Thanks.

**Comment by zhangyc** [comment]
> How can I get voices call in dart? Kindly suggest. Thanks.

    final e=await flutterTts.getEngines;

flutterTts.getVoices.then((value){
      print('-----voice:${value}');
    });
