### ISSUE TITLE
About the setProgressHandler

### ISSUE THREAD

**Issue by dinhan1192** [dlutton/flutter_tts#123]
So when I use delay in the for loop like in this https://github.com/dlutton/flutter_tts/issues/66#issuecomment-639275237, it seems that the setProgressHandler does not work anymore, but other void function still works like just a print !!!
Thank you for your effort!!

**Comment by dinhan1192** [comment]
the problem is, I want to get the last index of the string flutter tts
speak ^^, but it seems when I use delay like that, the setProgressHandler did not work,
so ....
Thank you for your response !!!

**Comment by dlutton** [comment]
Fix to #66 has been merged.
