### ISSUE TITLE
About the speak

### ISSUE THREAD

**Issue by dinhan1192** [dlutton/flutter_tts#124]
So, another problem here concerning with the speak.
It seems that when you click on the speak of another content, the very first speak did not completely stop! 
Thank you!

**Comment by dlutton** [comment]
You can control that with platform listeners such as 
`flutterTts.setStartHandler(() {
  setState(() {
    ttsState = TtsState.playing;
  });
});`. 

You can use that to set a state so if speak is called while it's in the playing state, you can then do a stop followed by a play.  You can also use flutterTts.setCompletionHandler to find out when the speak has completed.

**Comment by dinhan1192** [comment]
the problem is, I want to get the last index of the string flutter tts
speak ^^ you know, just to make a workaround for continue and pause ^^, but
it seems when I use delay like that, the setProgressHandler did not work,
so ....
Thank you for your response !!!

**Comment by dinhan1192** [comment]
Thank you for your response !!! I will try it ^^
