### ISSUE TITLE
getLanguages on Huawei Y7P stops code execution

### ISSUE THREAD

**Issue by fleoparra** [dlutton/flutter_tts#125]
When I execute await flutterTts.getLanguages this line stops code execution (the next line is not executed)

On other devices this await flutterTts.getLanguages works as expected.

Huawei Y7p do not have google play services and do not have any TTS engine.

I think that maybe can throw an exception instead of stop code execution. I don´t know.

**Comment by dlutton** [comment]
does it throw a specific exception when that code is ran on that device?  I'd assume it would fail before that as there is no TTS engine on the device, but I haven't tested that.

**Comment by fleoparra** [comment]
I am using this code to verify after 3 seconds if getLanguages works as expected:

      flutterTtsReadLanguages  = false;
      Future.delayed(Duration(seconds: 3), () {
        if (!flutterTtsReadLanguages && context != null) {
          List<FlatButton> actions = [];
          actions.add(FlatButton(
            onPressed: () => Navigator.pop(context, false),
            child: Text(AppLocalizations.of(context).translate('close').toUpperCase()),
          ));
          Alerts.dialogWithActions(
              context, AppLocalizations.of(context).translate('ttsError'), Text(AppLocalizations.of(context).translate('ttsErrorMsg')), actions);
        }
      });

      List<dynamic> languages = await flutterTts.getLanguages;
      flutterTtsReadLanguages  = true;

**Comment by dlutton** [comment]
I have added better exception handling on getLanguages and also a getengines call.
