### ISSUE TITLE
About the speak not stop

### ISSUE THREAD

**Issue by dinhan1192** [dlutton/flutter_tts#126]
So, I notice another bug concerning the flutter tts ^^
when speaking a long content, let's say 8000 characters, I run a "for" for it with a delay. But when I press stop while speaking the first round, it stop, but it doesn't truly stop! it still run the next round!

I tried using setCompletionHandler and setCancelHandler but none of them worked =.=
Thank you for your effort!
An

**Comment by dlutton** [comment]
@dinhan1192 can you provide an example.

**Comment by vtisnado** [comment]
@dinhan1192 If you have a function that loops for large text, you should check with a boolean value if the text is playing inside the **tts.setCompletionHandler**. 

Here is an example with the function Im using:

```
int speakLoop = 0;
if(texts.length > 0) {
tts.speak(texts[speakLoop]);
tts.setCompletionHandler(() {
	speakLoop++;
	if (speakLoop <texts.length ) {
		if (_isPlaying.value == true ){
			tts.speak(texts[speakLoop]);
		}
	} else {

	}
});
}
```
