### ISSUE TITLE
Error when try to FlutterTts.getLanguages

### ISSUE THREAD

**Issue by davidgalarza** [dlutton/flutter_tts#130]
### Expected behavior

I'm trying to get the available languages on my users device, when I execute my code on my personal phone it works perfectly but in my bug report system (Sentry) I'm getting this error on some devices.
```
PlatformException
PlatformException(error, Attempt to invoke interface method 'java.util.Iterator java.util.Set.iterator()' on a null object reference, null)
message_codecs.dart in StandardMethodCodec.decodeEnvelope at line 569
platform_channel.dart in MethodChannel._invokeMethod at line 156
Called from: <asynchronous suspension>
flutter_tts.dart in FlutterTts.getLanguages at line 198
Called from: <asynchronous suspension>
practiceLesson.dart in _PracticeLessonScreenState.initState.<fn> at line 98
Called from: <asynchronous suspension>
```
I get more than 10k reports of that. I don't know if its related with the brand but  the 90% of errors are from Huawei phones
<img width="1021" alt="Captura de Pantalla 2020-06-20 a la(s) 18 59 09" src="https://user-images.githubusercontent.com/20847597/85213743-2213ad00-b328-11ea-83e2-21abdec29398.png">

### Reproduction steps
Here is my code

```dart
@override
  void initState() {
    initTTS();
}
initTTS() async {
    flutterTts = FlutterTts();
    languages = await flutterTts.getLanguages;
    this.langCodeSpeech = languages.firstWhere((code) {
      return code.toString().startsWith(widget.courseLangCode);
    }, orElse: () => null);
    if (langCodeSpeech != null)
      await flutterTts.setLanguage(this.langCodeSpeech);
}
```

**Version:** 1.2.2

**Platform:** 
- [ ] :robot: Android

**Comment by dlutton** [comment]
This appears to be related to #125.

I'll have to research the issue on those devices and add better error handling.

**Comment by dlutton** [comment]
I have added better exception handling for getLanguages and also added a getEngines call.
