### ISSUE TITLE
(BloC) The event/state(BloC) comes from flutter_tts listener, cannot re-render the view.

### ISSUE THREAD

**Issue by chounry** [dlutton/flutter_tts#131]
What i did :
I dispatch an event when the `setErrorHandler` and `setCompletionHandler` get called, because i want the view to change after the speaking done. But It doesn't change the view after a new state retrieve. 

I write a print() 1 line before the view that will be return(render), it actually print, but the view doesn't get render like it suppose to be. 

Can anyone help me with this.? This is so nonsense.

**Comment by dlutton** [comment]
based on the description of the issue, I don't believe this is related to the flutter_tts engine.  Have you tried re-rendering the view in a setState method?
