### ISSUE TITLE
Error when building 1.2.5 

### ISSUE THREAD

**Issue by StephanCassel** [dlutton/flutter_tts#135]
Hi 

Error when building 1.2.5 

Tried flutter clean and flutter pub cache repair but did not help.
When I returned to version 1.2.3 same error occurred.
flutter clean and flutter pub cache repair same thing.
  

/Users/stephan/Documents/Projects/sinkadus/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:33: error: constructor FlutterTtsPlugin in class FlutterTtsPlugin cannot be applied to given types;
    flutterEngine.getPlugins().add(new com.tundralabs.fluttertts.FlutterTtsPlugin());
                                   ^
  required: Context,MethodChannel
  found: no arguments
  reason: actual and formal argument lists differ in length
1 error

/Users/stephan/development/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-NO)
    • Flutter version 1.17.5 at /Users/stephan/development/flutter
    • Framework revision 8af6b2f038 (6 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/stephan/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • LYA L29 • LHS7N18A13001240 • android-arm64 • Android 10 (API 29)

• No issues found!

**Comment by Janus451** [comment]
Hi, 

I have the same problem. When I try to build the project the build fails. Just some time ago, everything worked well. 

C:\Users\Jan\AndroidStudioProjects\flutter_app_test\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:16: error: constructor FlutterTtsPlugin in class FlutterTtsPlugin cannot be applied to given types;
    flutterEngine.getPlugins().add(new com.tundralabs.fluttertts.FlutterTtsPlugin());
                                                      ^
  required: Context,MethodChannel
  found: no arguments
  reason: actual and formal argument lists differ in length
1 error

FAILURE: Build failed with an exception.


[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.900], locale de-DE)
    • Flutter version 1.17.5 at C:\Users\Jan\flutter_windows_v1.12.13+hotfix.8-stable\flutter
    • Framework revision 8af6b2f038 (6 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Jan Lechner\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!

**Comment by dlutton** [comment]
Thanks for reporting this.  I tested this version on an android build without any errors before releasing it.  I'll test more later on and roll back the changes to android if needed.

**Comment by dlutton** [comment]
this should be fixed in the latest build.

**Comment by StephanCassel** [comment]
Works fine. Thanks for your excellent package !
