### ISSUE TITLE
Auto detect language

### ISSUE THREAD

**Issue by ninjaasmoke** [dlutton/flutter_tts#137]
Instead of predefining a language, is there a way to set multiple languages or a set of all languages, and determine the language based on the input, automatically?

**Comment by dlutton** [comment]
I'm sure it's possible with something like the google ML language identification kit, however it's not something that's built into this package.

**Comment by dlutton** [comment]
@ninjaasmoke You can use this [package](https://github.com/dlutton/flutter_language_id) I created to help you determine the language of the text.
