### ISSUE TITLE
synthesizeToFile trying to save file at wrong location/path

### ISSUE THREAD

**Issue by farazk86** [dlutton/flutter_tts#140]
## 🐛 Bug Report

I'm using ``synthesizeToFile`` to save to Downloads folder in android. I used ``Android Path Provider`` dart package to get the path to Downloads. Which works fine. I then want to save the file to this path.  To get the full save path I do: ``String _savePath = p.join(_downloadsPath, 'tts.wav');`` which returns on ``print(_savePath)``:

`/storage/emulated/0/Download/tts.wav`

I try to save to this location using:

```
if (_status == PermissionStatus.granted){
                      await _flutterTts.synthesizeToFile(_controller.text, _savePath);
                    }
```

but I get this error and file not found error, but notice the path where it is trying to open the file. Its trying to combine the path I gave it to the internal path. Why is it doing this?

```
E/TextToSpeech( 4163): Opening file /storage/emulated/0/Android/data/com.lewanayustaz.easy_ocr/files/storage/emulated/0/Download/tts.wav failed
E/TextToSpeech( 4163): java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
E/TextToSpeech( 4163): 	at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:344)
E/TextToSpeech( 4163): 	at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:231)
E/TextToSpeech( 4163): 	at android.speech.tts.TextToSpeech.synthesizeToFile(TextToSpeech.java:1817)
E/TextToSpeech( 4163): 	at com.tundralabs.fluttertts.FlutterTtsPlugin.synthesizeToFile(FlutterTtsPlugin.java:391)
E/TextToSpeech( 4163): 	at com.tundralabs.fluttertts.FlutterTtsPlugin.onMethodCall(FlutterTtsPlugin.java:200)
E/TextToSpeech( 4163): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/TextToSpeech( 4163): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/TextToSpeech( 4163): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/TextToSpeech( 4163): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/TextToSpeech( 4163): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/TextToSpeech( 4163): 	at android.os.Looper.loop(Looper.java:183)
E/TextToSpeech( 4163): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/TextToSpeech( 4163): 	at java.lang.reflect.Method.invoke(Native Method)
E/TextToSpeech( 4163): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/TextToSpeech( 4163): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
D/TTS     ( 4163): Failed creating file : /storage/emulated/0/Android/data/com.lewanayustaz.easy_ocr/files/storage/emulated/0/Download/tts.wav
```

``Permissions`` is working, I have granted permission to external storage and the output of ``Permission.storage.status`` is ``I/flutter ( 4163): PermissionStatus.granted``

### Expected behavior

To save at the path provided

**Version:** 1.2.6

**Platform:** 
-  Android

**Comment by farazk86** [comment]
Right, so its clear that we cannot give a custom path, as when I tried to just use the file name as in the example readme with the command: 

`await _flutterTts.synthesizeToFile(_controller.text,'tts.wav');`

I get the message:

`D/TTS     (18619): Successfully created file : /storage/emulated/0/Android/data/com.lewanayustaz.easy_ocr/files/tts.wav`

It would be great to give custom paths and let us save in provided location, but even this is not generating the file. When I go to the location mentioned above in file manager, there is nothing there.

Am I missing something?

Thanks

**Comment by dlutton** [comment]
The "/storage/emulated/" folder does not really exist on the device, it's more of a reference.  It should be stored somewhere in  "Internal Storage" on the device.  You can pull the file down using adb.  `adb pull /storage/emulated/0/Android/data/com.lewanayustaz.easy_ocr/files/tts.wav` in your case on the command line.  I'm glad you're providing input as I'm wasn't sure how people were going to use this.  I'll add the option to provide a custom save path.

**Comment by farazk86** [comment]
> The "/storage/emulated/" folder does not really exist on the device, it's more of a reference. It should be stored somewhere in "Internal Storage" on the device. You can pull the file down using adb. `adb pull /storage/emulated/0/Android/data/com.lewanayustaz.easy_ocr/files/tts.wav` in your case on the command line. I'm glad you're providing input as I'm wasn't sure how people were going to use this. I'll add the option to provide a custom save path.

Thanks for the reply.

Until you get that feature implemented of custom save path, can I make this work by possibly copying the file synthesized to my custom path.  I can use a function like below to move the generated file from its default location to the new one, but I am having trouble getting the String path of the default saved tts file. I tried looking at the source but could not figure it out as I'm not that experienced in dart :(

```
Future<void> moveFile(File sourceFile, String newPath) async {
    try {
      // prefer using rename as it is probably faster
      return await sourceFile.rename(newPath);
    } on FileSystemException catch (e) {
      // if rename fails, copy the source file and then delete it
      final newFile = await sourceFile.copy(newPath);
      await sourceFile.delete();
      //return newFile;
    }
  }
```

Would this work? and how can I get the string of saved file by ``synthesizeToFile ``?

Thanks

**Comment by farazk86** [comment]
Also I'd like to update this, that I am positive that ``synthesizeToFile`` is not working as intended. 

It does not generate a file that can be seen in file explorer. Even in the default location

**Comment by dlutton** [comment]
I'll take a look at this issue @farazk86.

**Comment by dlutton** [comment]
@farazk86 I tested synthesizeToFile on Android and it does appear to be working.  You can run `adb pull /storage/emulated/0/Android/data/com.lewanayustaz.easy_ocr/files/tts.wav` from the command line or on your emulated device you can go to Settings -> Storage -> Internal Shared Storage -> Files -> Click on Audio at the top and the wav file should appear for you to play.  I have attached a screenshot below.  I still plan on allowing a custom file path in a future release.

![Screen Shot 2020-07-23 at 2 58 07 AM](https://user-images.githubusercontent.com/14303235/88274399-7ea01a00-cc90-11ea-98e2-b7e39c7c4674.png)
