### ISSUE TITLE
When calling speak() multiple times, with await and async, only last call is returned/executed.

### ISSUE THREAD

**Issue by slimyTextBox** [dlutton/flutter_tts#141]
## 🐛 Bug Report

Code below, when I call speak() multiple times, having all the calls awaited in async funtions, only last call is executed and spoken. "await" and ".then"  make no difference. I tried async functions with multiple types: Future, Future void , Future int , void. With and without return.

Language is set to "en-US" runtime

Tested on android

**Version:** ^1.2.6

**Platform:** 
- [NOT CHECK] :iphone: iOS
- [CHECK ] :robot: Android

In all blocks/examples  the phone says only "three"

==========Block 1==============
Future asyncFunction (String string)async{
    await _speak2('one').then((_) async {
      _speak2('two');
      await _speak2('three');
    });
}

==========Block 2==============
Future asyncFunction (String string)async{
    await _speak2('one').then((_) async {
      await _speak2('two');
      await _speak2('three');
    });
}

==========Block 3==============
Future asyncFunction (String string)async{
      await _speak2('one');
      await  _speak2('two');
      await _speak2('three');
}
==========Block 4==============
Future asyncFunction (String string)async{
      await _speak2('one');
      await  _speak2('two');
      asyncFunction2();

}

Future asyncFunction2 (){
await _speak2('three');
}
}
=========End of Code blocks, full code below, copy paste from the example,==========
=========I placed the 4 function highlighting this problem first =========================

import 'dart:async';
import 'dart:io' show Platform;
import 'package:flutter/foundation.dart' show kIsWeb;

import 'package:flutter/material.dart';
import 'package:flutter_tts/flutter_tts.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

enum TtsState { playing, stopped, paused, continued }

class _MyAppState extends State<MyApp> {
  

Future lalala() async {
    _speak2('one').then((value) async {
      _speak2('two');
      await _speak2('three');
    });
   
  }

  Future _speak2(String str) async {
    await flutterTts.setVolume(volume);
    await flutterTts.setSpeechRate(rate);
    await flutterTts.setPitch(pitch);

    if (_newVoiceText != null) {
      if (_newVoiceText.isNotEmpty) {
        var result = await flutterTts.speak(str);
        if (result == 1) setState(() => ttsState = TtsState.playing);
      }
    }
  }

  Future _speak() async {
    await flutterTts.setVolume(volume);
    await flutterTts.setSpeechRate(rate);
    await flutterTts.setPitch(pitch);

    if (_newVoiceText != null) {
      if (_newVoiceText.isNotEmpty) {
        var result = await flutterTts.speak(_newVoiceText);
        if (result == 1) setState(() => ttsState = TtsState.playing);
      }
    }
  }

  Widget _btnSection() {
    if (!kIsWeb && Platform.isAndroid) {
      return Container(
          padding: EdgeInsets.only(top: 50.0),
          child: Row(mainAxisAlignment: MainAxisAlignment.spaceEvenly, children: [
            _buildButtonColumn(Colors.green, Colors.greenAccent, Icons.play_arrow, 'PLAY', _speak),
            _buildButtonColumn(Colors.red, Colors.redAccent, Icons.stop, 'STOP', _stop),
            _buildButtonColumn(Colors.red, Colors.redAccent, Icons.stop, 'LALALA', () async {
              await lalala();
            }),
          ]));
    } else {
      return Container(
          padding: EdgeInsets.only(top: 50.0),
          child: Row(mainAxisAlignment: MainAxisAlignment.spaceEvenly, children: [
            _buildButtonColumn(Colors.green, Colors.greenAccent, Icons.play_arrow, 'PLAY', _speak),
            _buildButtonColumn(Colors.red, Colors.redAccent, Icons.stop, 'STOP', _stop),
            _buildButtonColumn(Colors.blue, Colors.blueAccent, Icons.pause, 'PAUSE', _pause),
          ]));
    }
  }

  FlutterTts flutterTts;
  dynamic languages;
  String language;
  dynamic voices;
  String voice;
  double volume = 0.5;
  double pitch = 1.0;
  double rate = 0.5;

  String _newVoiceText;

  TtsState ttsState = TtsState.stopped;

  get isPlaying => ttsState == TtsState.playing;

  get isStopped => ttsState == TtsState.stopped;

  get isPaused => ttsState == TtsState.paused;

  get isContinued => ttsState == TtsState.continued;

  @override
  initState() {
    super.initState();
    initTts();
  }

  initTts() async {
    flutterTts = FlutterTts();

    await _getLanguages();
    // await getVoices();

    flutterTts.setStartHandler(() {
      setState(() {
        print("Playing");
        ttsState = TtsState.playing;
      });
    });

    flutterTts.setCompletionHandler(() {
      setState(() {
        print("Complete");
        ttsState = TtsState.stopped;
      });
    });

    flutterTts.setCancelHandler(() {
      setState(() {
        print("Cancel");
        ttsState = TtsState.stopped;
      });
    });

    if (kIsWeb || Platform.isIOS) {
      flutterTts.setPauseHandler(() {
        setState(() {
          print("Paused");
          ttsState = TtsState.paused;
        });
      });

      flutterTts.setContinueHandler(() {
        setState(() {
          print("Continued");
          ttsState = TtsState.continued;
        });
      });
    }

    flutterTts.setErrorHandler((msg) {
      setState(() {
        print("error: $msg");
        ttsState = TtsState.stopped;
      });
    });
  }

  Future _getLanguages() async {
    languages = await flutterTts.getLanguages;
    if (languages != null) setState(() => languages);
  }

  Future setLang(String lang) async {
    if (languages.contains(lang)) {
      await flutterTts.setLanguage(lang);
      language = lang;
    }
  }

  void getVoices() async {
    voices = await flutterTts.getVoices;
    voices.sort((a, b) => a.toString().compareTo(b.toString()));
    voices = voices.where((x) => x.toString().toLowerCase().contains(language.toLowerCase())).toList();
  }

  Future setVoice(String voice) async {
    await flutterTts.setVoice(voices[1]);
    // if (voices.contain(voice)) await flutterTts.setVoice(voice);
  }

  Future _stop() async {
    var result = await flutterTts.stop();
    if (result == 1) setState(() => ttsState = TtsState.stopped);
  }

  Future _pause() async {
    var result = await flutterTts.pause();
    if (result == 1) setState(() => ttsState = TtsState.paused);
  }

  @override
  void dispose() {
    super.dispose();
    flutterTts.stop();
  }

  List<DropdownMenuItem<String>> getLanguageDropDownMenuItems() {
    var items = List<DropdownMenuItem<String>>();
    for (dynamic type in languages) {
      items.add(DropdownMenuItem(value: type as String, child: Text(type as String)));
    }
    return items;
  }

  List<DropdownMenuItem<String>> getVoiceDropDownMenuItems() {
    var items = List<DropdownMenuItem<String>>();
    for (dynamic type in voices) {
      items.add(DropdownMenuItem(value: type as String, child: Text(type as String)));
    }
    return items;
  }

  void changedLanguageDropDownItem(String selectedType) async {
    setState(() {
      language = selectedType;
      flutterTts.setLanguage(language);
      getVoices(); //
    });
  }

  void changedVoiceDropDownItem(String selectedType) {
    setState(() {
      voice = selectedType;
      flutterTts.setVoice(voice);
    });
  }

  void _onChange(String text) {
    setState(() {
      _newVoiceText = text;
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
            appBar: AppBar(
              title: Text('Flutter TTS'),
            ),
            body: SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Column(children: [
                  _inputSection(),
                  _btnSection(),
                  languages != null ? _languageDropDownSection() : Text(""),
                  voices != null ? _voiceDropDownSection() : Text(""),
                  _buildSliders()
                ]))));
  }

  Widget _inputSection() => Container(
      alignment: Alignment.topCenter,
      padding: EdgeInsets.only(top: 25.0, left: 25.0, right: 25.0),
      child: TextField(
        onChanged: (String value) {
          _onChange(value);
        },
      ));

  Widget _languageDropDownSection() => Container(
      padding: EdgeInsets.only(top: 50.0),
      child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [
        DropdownButton(
          value: language,
          items: getLanguageDropDownMenuItems(),
          onChanged: changedLanguageDropDownItem,
        )
      ]));

  Widget _voiceDropDownSection() => Container(
      padding: EdgeInsets.only(top: 50.0),
      child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [
        DropdownButton(
          value: voice,
          items: getVoiceDropDownMenuItems(),
          onChanged: changedVoiceDropDownItem,
        )
      ]));

  Column _buildButtonColumn(Color color, Color splashColor, IconData icon, String label, Function func) {
    return Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [
      IconButton(icon: Icon(icon), color: color, splashColor: splashColor, onPressed: () => func()),
      Container(
          margin: const EdgeInsets.only(top: 8.0),
          child: Text(label, style: TextStyle(fontSize: 12.0, fontWeight: FontWeight.w400, color: color)))
    ]);
  }

  Widget _buildSliders() {
    return Column(
      children: [_volume(), _pitch(), _rate()],
    );
  }

  Widget _volume() {
    return Slider(
        value: volume,
        onChanged: (newVolume) {
          setState(() => volume = newVolume);
        },
        min: 0.0,
        max: 1.0,
        divisions: 10,
        label: "Volume: $volume");
  }

  Widget _pitch() {
    return Slider(
      value: pitch,
      onChanged: (newPitch) {
        setState(() => pitch = newPitch);
      },
      min: 0.5,
      max: 2.0,
      divisions: 15,
      label: "Pitch: $pitch",
      activeColor: Colors.red,
    );
  }

  Widget _rate() {
    return Slider(
      value: rate,
      onChanged: (newRate) {
        setState(() => rate = newRate);
      },
      min: 0.0,
      max: 1.0,
      divisions: 10,
      label: "Rate: $rate",
      activeColor: Colors.green,
    );
  }
}

**Comment by dlutton** [comment]
Thanks for this report.  I'll need to change the future to return when the speak has completed rather than immediately.

**Comment by slimyTextBox** [comment]
Thank you

**Comment by SandroMaglione** [comment]
I think that the same bug is in the `whenComplete` callback.

I am trying to make the system speak two words one after the other, the second one when the first is completed. This is the code I used:
``` dart
Future<void> speakBoth(String word1, String word2) async =>
      speak(word1).whenComplete(() async {
        print("whenComplete");
        return speakResult(word2);
      });
```

The bug seems to occur and the system speaks only the second word (word2).
The log prints these messages:
```
D/TTS     ( 7757): Utterance ID has started: SIL_2d3cb9fa-ebf3-4d16-9722-c1cc86a27066
I/flutter ( 7757): whenComplete
D/TTS     ( 7757): Utterance ID has been stopped: 2d3cb9fa-ebf3-4d16-9722-c1cc86a27066. Interrupted: true
D/TTS     ( 7757): Utterance ID has been stopped: SIL_2d3cb9fa-ebf3-4d16-9722-c1cc86a27066. Interrupted: true
D/TTS     ( 7757): Utterance ID has started: SIL_fe1f1240-d736-4769-a2c6-7982222e5f45
D/TTS     ( 7757): Utterance ID has started: fe1f1240-d736-4769-a2c6-7982222e5f45
D/TTS     ( 7757): Utterance ID has completed: fe1f1240-d736-4769-a2c6-7982222e5f45
```
So it seems that the first word starts, but the `whenComplete` does not wait for it to finish but is called right away, stopping the first word and starting immediately the second one.

**Note**: I added `flutterTts.setSilence(300)`, I do not know if this configuration may cause problem in this scenario.

**Comment by dlutton** [comment]
so that it maintains backwards compatibility, you can now simply call `await flutterTts.awaitSpeakCompletion(true);` with the latest version and it will await until speak has completed.  This only needs to be called once.
