### ISSUE TITLE
add a custom language in TTS flutter

### ISSUE THREAD

**Issue by youssefRA** [dlutton/flutter_tts#142]
## 💬 Questions ai need a way to add a custom language
I have this :-
`class homeApp extends StatefulWidget {
  @override
  _homeAppState createState() => _homeAppState();
}

class _homeAppState extends State<homeApp> {
  FlutterTts flutterTts;

  @override
  void initState() {
    flutterTts = FlutterTts();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    Future say(text) async {
      print(await flutterTts.getLanguages);
      await flutterTts.setLanguage('ar');
      await flutterTts.speak(text);
    }

    return Scaffold(
      appBar: AppBar(
        title: Text('appBar'),
        backgroundColor: Colors.green[200],
      ),
      body: Column(
        children: <Widget>[
          FlatButton(
              onPressed: () {
                say('مرحبا');
              },
              child: Text('Button'))
        ],
      ),
    );
  }
}
`

**Comment by dlutton** [comment]
you'll have to use one of the language codes being returned by the getLanguages method.  If 'ar' is returned, you should be able to use that successfully to speak your desired text.  If not, then the google TTS engine doesn't support it on Android.

**Comment by youssefRA** [comment]
it is not returned, is there is any another way

**Comment by dlutton** [comment]
Not with this package unfortunately.  You can see if Google cloud provides that language.

**Comment by youssefRA** [comment]
okay, thanks a lot.
