### ISSUE TITLE
Recommdation of edge case with stop() should be documented

### ISSUE THREAD

**Issue by JBaba** [dlutton/flutter_tts#149]
## 💬 Questions and Help

I have found edge case and after debugging the module has found the solution. I don't know if this is bug or not But users should be aware about it if this behavior occurs. For current release i think this should be documented on the read me or anywhere else.

### Short summary:
**Platform observed:** Android
**Error:** Nullpointer / VM shutdown
**Result:** App crash
**Workaround:** Possible
**Documentation:** Missing

### Situation:

When you call `tts.stop()` and subsequently background task (`audioservice`) is removed app crashes.

following code is the reason for crash,

```
private void invokeMethod(final String method, final Object arguments) {
    handler.post(
        new Runnable() {
          @Override
          public void run() {
            methodChannel.invokeMethod(method, arguments);
          }
        });
  }
```
### Explanation of crash:

`methodChannel` is `null` because of `onDetachedFromEngine` get executed first and then `methodChannel.invokeMethod(method, arguments);` is executed.

This does not happen very first time even though its does most often. If we don't notice first time then repeating this `stop() -> renove task` back forth will produce the error.   

Exception: `Nullpointer. invokeMethod called on null`

### Solution

we have to combine background task removed with `completer`

```
_tts.setCancelHandler(() {
        _stopCompleter.complete();
 });

@override
  Future<void> onStop() async {
    // wait for cancel handler to be called on tts.stop()    
    await _stopCompleter.future;
    // Shut down this task
    await super.onStop();
  }
```

**Comment by mwolffalonso** [comment]
Thanks man, this was a life saver!

**Comment by mwolffalonso** [comment]
> ## 💬 Questions and Help
> I have found edge case and after debugging the module has found the solution. I don't know if this is bug or not But users should be aware about it if this behavior occurs. For current release i think this should be documented on the read me or anywhere else.
> 
> ### Short summary:
> **Platform observed:** Android
> **Error:** Nullpointer / VM shutdown
> **Result:** App crash
> **Workaround:** Possible
> **Documentation:** Missing
> 
> ### Situation:
> When you call `tts.stop()` and subsequently background task (`audioservice`) is removed app crashes.
> 
> following code is the reason for crash,
> 
> ```
> private void invokeMethod(final String method, final Object arguments) {
>     handler.post(
>         new Runnable() {
>           @Override
>           public void run() {
>             methodChannel.invokeMethod(method, arguments);
>           }
>         });
>   }
> ```
> 
> ### Explanation of crash:
> `methodChannel` is `null` because of `onDetachedFromEngine` get executed first and then `methodChannel.invokeMethod(method, arguments);` is executed.
> 
> This does not happen very first time even though its does most often. If we don't notice first time then repeating this `stop() -> renove task` back forth will produce the error.
> 
> Exception: `Nullpointer. invokeMethod called on null`
> 
> ### Solution
> we have to combine background task removed with `completer`
> 
> ```
> _tts.setCancelHandler(() {
>         _stopCompleter.complete();
>  });
> 
> @override
>   Future<void> onStop() async {
>     // wait for cancel handler to be called on tts.stop()    
>     await _stopCompleter.future;
>     // Shut down this task
>     await super.onStop();
>   }
> ```

Sorry for my ignorance, but how is it that two different plugins use the same platform methodchannel? Shouldn't be different channels?

**Comment by ryanheise** [comment]
I've submitted a pull request for this bug here: https://github.com/dlutton/flutter_tts/pull/151 .

This fix both guards against the NPE and also stops the current utterance in progress (a FlutterEngine shouldn't use any native resources after it has supposedly been destroyed). This means that in addition to the native bug fix, it is also probably a good idea to do what you're doing in Dart and ensure that the utterance has completed before calling `super.onStop` to shut down the FlutterEngine.
