### ISSUE TITLE
Make speak await completion

### ISSUE THREAD

**Issue by ryanheise** [dlutton/flutter_tts#152]
## 🚀 Feature Requests

It would be very convenient if the Future returned by `FlutterTts.speak` marked the completion of the utterance.

### Contextualize the feature

This can be handled within the plugin's implementation of `speak`, at the Dart layer.

### Describe the feature

The most common thing I need to do using this plugin besides initiating a `speak` request is to wait for it to complete.

The API would be very convenient if it worked in this fashion:

```dart
print("Speaking...");
await flutterTts.speak("Hello");
print("Finished speaking.");
```

This would allow me to programmatically stack speak requests together like this, where the logic is dynamic:

```dart
await flutterTts.speak(nextUtterance());
await flutterTts.speak(nextUtterance());
await flutterTts.speak(nextUtterance());
```

This would also make it easier to intersperse different types of audio into sequence using different audio plugins. E.g.:

```dart
await flutterTts.speak(utterance1);
await audioPlayer.play(soundEffect); // just_audio currently works this way
await Future.delayed(pauseDuration);
// and so on.
```

The current API makes everything possible, although not in a convenient way for this type of async/await coding pattern.

In the audio_service flutter_tts demo, I include a wrapper around your plugin that provides a cut-down version of the proposed API:

```dart
/// A wrapper around FlutterTts that makes it easier to wait for speech to
/// complete.
class Tts {
  final FlutterTts _flutterTts = new FlutterTts();
  Completer _speechCompleter;
  bool _playing = false;

  Tts() {
    _flutterTts.setCompletionHandler(() {
      _speechCompleter?.complete();
    });
  }

  bool get playing => _playing;

  Future<void> speak(String text) async {
    _playing = true;
    _speechCompleter = Completer();
    await _flutterTts.speak(text);
    await _speechCompleter.future;
    _speechCompleter = null;
    _playing = false;
  }

  Future<void> stop() async {
    if (_playing) {
      await _flutterTts.stop();
      _speechCompleter?.complete();
    }
  }
}
```

There are obviously many things left out of this cut-down solution, although it gives a general idea of how it could be handled within the plugin at the Dart layer. I am also happy with flutter_tts as it is, since I can always continue to create such a wrapper around it, although I do think having this type of API built into flutter_tts would be amazingly convenient.

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by dlutton** [comment]
similar to issue #141, where I mentioned "I'll need to change the future to return when the speak has completed rather than immediately."  This is definitely on my radar as this is how it should be working.

**Comment by tandacedric** [comment]
> similar to issue #141, where I mentioned "I'll need to change the future to return when the speak has completed rather than immediately." This is definitely on my radar as this is how it should be working.

When will this be available? Please this keeps me from moving forward

**Comment by dlutton** [comment]
I'll see if I can make some time over the weekend @tandacedric.

**Comment by dlutton** [comment]
so that it maintains backwards compatibility, you can now simply call `await flutterTts.awaitSpeakCompletion(true);` with the latest version and it will await until speak has completed.  This only needs to be called once.

**Comment by newengine** [comment]
how to interrupt and start a new speech?

**Comment by dlutton** [comment]
@newengine `await flutterTts.stop()` should work for you.

**Comment by newengine** [comment]
after stop(),  it can not resume playing.

**Comment by dlutton** [comment]
@newengine can you add a snippet of the code you're running.

**Comment by newengine** [comment]
i am using it with Audioservice.    it works fine when it's not using await flutterTts.awaitSpeakCompletion(true);,  

below is the code to resume the play after calling stop()

      final session = await AudioSession.instance;
      if (await session.setActive(true)) {
        await AudioServiceBackground.setState(
          controls: [MediaControl.pause, MediaControl.stop],
          processingState: AudioProcessingState.ready,
          playing: true,
        );

      }

**Comment by dlutton** [comment]
`flutterTts.awaitSpeakCompletion(true);` is optional, so if it works fine without it, you should continue without using it.  Is there a reason you started using it?  I'm not sure what you mean by "resume" play.  Do you mean pausing tts and then continuing on (pausing doesn't work with android) or did you mean stopping and then speaking a new text being passed to it?
