### ISSUE TITLE
getVoices should return Language too, not only name

### ISSUE THREAD

**Issue by devon** [dlutton/flutter_tts#153]
## 🚀 Feature Requests

```
  private func getVoices(result: FlutterResult) {
    if #available(iOS 9.0, *) {
      let voices = NSMutableArray()
      for voice in AVSpeechSynthesisVoice.speechVoices() {
        voices.add(voice.name)
      }
      result(voices)
    } else {
      // Since voice selection is not supported below iOS 9, make voice getter and setter
      // have the same bahavior as language selection.
      getLanguages(result: result)
    }
  }
```

Right now, the getVoices only return names, but we don't know the language for the name. Let's say, which voice is for French, which one is for English.

We cannot set the right voice if we don't know the language of the voice.

### Platforms affected (mark all that apply)
- [x ] :iphone: iOS
- [ x] :robot: Android

**Comment by dlutton** [comment]
are you requesting a list of strings containing both the voice name and locale, or a map containing name and locale of the voice?

**Comment by devon** [comment]
A map containing the name and locale of the voice should be better. Thanks.

**Comment by johanlantz** [comment]
Agree that a map is probably nicer but I had the same problem and added a polling API in the plugin since it was the simplest solution. 

Opened a PR here: https://github.com/dlutton/flutter_tts/pull/169
in case anything there can be of help.

**Comment by dlutton** [comment]
I appreciate the PR @johanlantz however I already have the fix for this which is a map containing both the voice and language and when you set the voice, it requires both the voice and language.  I'm currently adding another separate fix and then I'll push the changes hopefully over the weekend.

**Comment by devon** [comment]
Both of you are great. @johanlantz  @dlutton

**Comment by dlutton** [comment]
Sorry for the delay, @devon and @johanlantz, when you get a moment, can you test this PR to see if it works for what you're requesting? #177. If you need assistance on pulling in this dependency using a certain branch, you can look here (https://flutter.dev/docs/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages).  Use the ref argument to pin the branch you want to use.  In this case, that ref is `voice_enhancement`.  If it all works, I'll merge in the code and update the version number.  

Also, note that the method now returns a map of name and locales so when you set it, you'll do something like this `await flutterTts.setVoice({"name": "Karen", "locale": "en-AU"});`

**Comment by devon** [comment]
It works. Thanks.

I test on a demo app as: 

```
flutter_tts:
  git:
    url: https://github.com/dlutton/flutter_tts
    ref: voice_enhancement

var voices = await flutterTts.getVoices;
print(voices);

await flutterTts.setVoice({'locale': 'ar-SA', 'name': 'Maged'});
await flutterTts.speak('some text');
```

getVoices return: 

```
[{locale: ar-SA, name: Maged}, {locale: cs-CZ, name: Zuzana}, {locale: da-DK, name: Sara}, {locale: de-DE, name: Anna}, {locale: el-GR, name: Melina}, {locale: en-AU, name: Karen}, {locale: en-GB, name: Daniel}, {locale: en-IE, name: Moira}, {locale: en-IN, name: Rishi}, {locale: en-US, name: Samantha}, {locale: en-ZA, name: Tessa}, {locale: es-ES, name: Mónica}, {locale: es-MX, name: Paulina}, {locale: fi-FI, name: Satu}, {locale: fr-CA, name: Amélie}, {locale: fr-FR, name: Thomas}, {locale: he-IL, name: Carmit}, {locale: hi-IN, name: Lekha}, {locale: hu-HU, name: Mariska}, {locale: id-ID, name: Damayanti}, {locale: it-IT, name: Alice}, {locale: ja-JP, name: Kyoko}, {locale: ko-KR, name: Yuna}, {locale: nl-BE, name: Ellen}, {locale: nl-NL, name: Xander}]
```
