### ISSUE TITLE
Exporting Speech as Audio Files 

### ISSUE THREAD

**Issue by coder-Aayush** [dlutton/flutter_tts#154]
## 🚀 Feature Requests

It will be awesome if there was feature of exporting speech as audio file.

**Comment by dlutton** [comment]
@coder-Aayush synthesizeToFile allows you to save the text as an audio file.  Do you have an example of what you're trying to do specifically?

**Comment by coder-Aayush** [comment]
I am trying to export speech as an audio file. Is this can be a features update.

**Comment by dlutton** [comment]
you can currently save the speech as an audio file and from there you can do as you wish.  Use the synthesizeToFile method.
