### ISSUE TITLE
I/TextToSpeech(18051): Asked to disconnect from ComponentInfo{com.google.android.tts/com.google.android.tts.service.GoogleTTSService}

### ISSUE THREAD

**Issue by Savyash** [dlutton/flutter_tts#155]
### Expected behavior
Lost connection to device.

### Reproduction steps
no specific steps to produce

**Version:** ^1.2.7

**Platform:** 
- [not sure] :iphone: iOS
- [yes] :robot: Android

**Comment by edwinbustamanterodriguez** [comment]
I have the some problem:
#Text_to_speech
  flutter_tts: ^1.2.7

Any Solution..??

**Comment by dlutton** [comment]
can you provide any activity that may have caused this issue?
