### ISSUE TITLE
Error when using another language on iOS

### ISSUE THREAD

**Issue by tranduc3sao** [dlutton/flutter_tts#156]
## 🐛 Bug Report

I configure it to use Vietnamese vi-VN. It works fine on Android but on IOS it uses english en-US

### Reproduction steps
```
    FlutterTts tts = FlutterTts();
    await tts.setLanguage("vi-VN");
    await tts.setSpeechRate(Platform.isIOS ? .5 : 1.0);
    await tts.setVolume(1.0);
    await tts.setPitch(1.0);
    await tts.isLanguageAvailable("vi-VN");
    await tts.speak(text);
```

### Configuration

**Version:** 0.8.6

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by dlutton** [comment]
what is the response you receive from `await tts.isLanguageAvailable("vi-VN");` on iOS?

**Comment by tranduc3sao** [comment]
> what is the response you receive from `await tts.isLanguageAvailable("vi-VN");` on iOS?

The value is false. And I don't see the Vietnamese language in the getLanguages function result. Does the library only support Android and not iOS?

**Comment by dlutton** [comment]
@tranduc3sao flutter_tts is supported on Android and iOS however the package is using their native TTS libraries so there are going to be some differences between the two.  iOS AVSpeech​Synthesizer may not support the Vietnamese language.
