### ISSUE TITLE
setVoice

### ISSUE THREAD

**Issue by silaic** [dlutton/flutter_tts#157]
i have an issue on setVoice()
i set voice just before call play(String text), but voice set seems not works.
i read italian voices from logging and set one as default. (not works)
i read voices using getVoices, then set first one from set using:
setVoices(tts.getVoices().first())
and even this not works.
i run debug app on phisical device ( redmi8) or on android emulator phone but result is same.
there is something i do wrong?

the voice that the tts play is the voice i have set from google tts engine list of voices. (inside phone settings)

**Comment by silaic** [comment]
i solved the issue using a workaround.
instead using 

await player.setVoice(voice);

used it without Future functions, just:

player.setVoice(voice)  // works like a charm

**Comment by dlutton** [comment]
can you provide the voice and text you're using?

**Comment by shinriyo** [comment]
where is voice??

**Comment by Ricardoi1** [comment]
> i solved the issue using a workaround. instead using
> 
> await player.setVoice(voice);
> 
> used it without Future functions, just:
> 
> player.setVoice(voice) // works like a charm

Thank you so much, I was suffering the same issue
