### ISSUE TITLE
iOS sound issue

### ISSUE THREAD

**Issue by xbadal** [dlutton/flutter_tts#158]
Volume is too low in iOS but works fine in Android.

**Comment by alexmcroberts** [comment]
I noticed this too. One thing I tried was setting the `defaultToSpeaker` option, and that helped me.

```
    await flutterTts.setIosAudioCategory(IosTextToSpeechAudioCategory.playback, [
      IosTextToSpeechAudioCategoryOptions.defaultToSpeaker
    ]);
```

**Comment by benunes01** [comment]
did that solve the problem? I also have this problem!

**Comment by dlutton** [comment]
@benunes01 and @xbadal, did @alexmcroberts's comment fix your issue?

**Comment by ltsolutionviet** [comment]
@dlutton  It working for case speaker, but not work when connect bluetooth device

> I noticed this too. One thing I tried was setting the `defaultToSpeaker` option, and that helped me.
> 
> ```
>     await flutterTts.setIosAudioCategory(IosTextToSpeechAudioCategory.playback, [
>       IosTextToSpeechAudioCategoryOptions.defaultToSpeaker
>     ]);
> ```
