### ISSUE TITLE
Set Engine TTS

### ISSUE THREAD

**Issue by dqtorres** [dlutton/flutter_tts#159]
The configuration would be missing, to be able to use other tts engines and not use the default

**Comment by dqtorres** [comment]
The configuration would be missing, to be able to use other tts engines and not use the default

**Comment by dqtorres** [comment]
There is no way to be able to use reciprocating engine installed in the device

**Comment by dlutton** [comment]
For Android, the default engine in this package is using "com.google.android.tts", are you looking for an option to pass a string such as "com.svox.pico" to use a different engine?

**Comment by dqtorres** [comment]
> For Android, the default engine in this package is using "com.google.android.tts", are you looking for an option to pass a string such as "com.svox.pico" to use a different engine?


Yes, the google engine does not express all languages ​​well, I am from Barcelona and the Catalan language is not very successful by google, I use an engine from the company acapela tts voice

**Comment by dqtorres** [comment]
Yes, the google engine does not express all languages ​​well, I am from Barcelona and the Catalan language is not very successful by google, I use an engine from the company acapela tts voice

**Comment by dlutton** [comment]
okay and do you also need an option to install the tts engine if not installed on the device or how were you planning on handling that scenario?

**Comment by dqtorres** [comment]
I was thinking of installing it manually, and in the application some preferences to select the engines installed in the devices

**Comment by dlutton** [comment]
okay so there is already an `await flutterTts.getEngines();` call you can make, so you're hoping to use a selection from that list to set the TTS engine right.

**Comment by Syutkin** [comment]
Maybe at least not hardcode "com.google.android.tts" and use selected android TTS engine instead?

**Comment by hioshih** [comment]
Nice, this would be much appreciated. Currently I can't seem to be able to use any third party language pack.

**Comment by dqtorres** [comment]
https://www.acapela-group.com/

**Comment by dlutton** [comment]
setEngine is now available for Android
