### ISSUE TITLE
Can we have voice selection, at least for android?

### ISSUE THREAD

**Issue by honzasvasek** [dlutton/flutter_tts#16]
## 🚀 Feature Requests

Android Voice Selection.

tts.setvoice() implementation  (so we can select male or female voices) can be done by setting de voice number in default voice in setup, but it would be nice to be able to do this from the app.

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [X ] :robot: Android

**Comment by dlutton** [comment]
@honzasvasek I can definitely add tts.setVoice() however you'll have to pass an object back similar to the voice object required to set the voice [setVoice](https://developer.android.com/reference/android/speech/tts/TextToSpeech#setVoice(android.speech.tts.Voice)) 
```
Voice (String name,  Locale locale, int quality, int latency, boolean requiresNetworkConnection, Set<String> features) 
```
Unfortunately there isn't an option for passing a value for "male" or "female".  [Android TTS Reference](https://developer.android.com/reference/android/speech/tts/TextToSpeech) - this provides all of the methods the Android TTS package provides.

Here is an example of what getVoices() returns and as you can see, some may result with a name of #male in it however not all of them do.

```
[Voice[Name: es-us-x-sfb-local, locale: es_US, quality: 400, latency: 200, requiresNetwork: false, features: [networkTimeoutMs, notInstalled, networkRetriesCount]], Voice[Name: fr-fr-x-vlf#male_1-local, locale: fr_FR, quality: 400, latency: 200, requiresNetwork: false, features: [networkTimeoutMs, notInstalled, networkRetriesCount]]
```

**Comment by honzasvasek** [comment]
@dlutton would be great if you add this, but how about using the same approach as in the Google TTS setup voice selection UI, just giving the voice number (that being the index into the voice list). So we can use flutterTts.setVoice(4); to select Voice #4.

**Comment by dlutton** [comment]
@honzasvasek so you'd like a getVoices option to return a list of voices and then a setVoice to set the voice based on that index of getVoices?

**Comment by honzasvasek** [comment]
I think that is the way to go, easiest would be when we could do the
setVoice without even having to do the getVoices. For my application a
numVoices, would be handy, so I can give the user an interface similar to
the one that Google uses in the Google-tts setup.

**Comment by dlutton** [comment]
@honzasvasek unfortunately there isn't an easy way to do a setVoice(1) as you previously mentioned.  getvoices() can return over 200 voices with some of them having male and/or female voices.  I did however add a getVoices and setVoice function for you in the latest version which you can play around with.  I'm hoping that's enough for you to add some logic to your application for what you need.  If you have other ideas for this implementation, please let me know or submit a PR.
