### ISSUE TITLE
When speaking underscore.

### ISSUE THREAD

**Issue by Chung14011998** [dlutton/flutter_tts#160]
## 🐛 When I buiild app on debug mode, underscore is still read. But when I build app on release mode, lib skipped underscore?
How to delay about 2 seconds at the between statement?

### Configuration

**Version:** 1.2.7

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by Chung14011998** [comment]
I already had a trick, thanks.

**Comment by MurtuzaSrashtaSoft** [comment]
how you put a delay between the statement?

**Comment by Chung14011998** [comment]
> how you put a delay between the statement? @Chung14011998

No, I replace "_" to text "underscore". So this problem is solved.

**Comment by MurtuzaSrashtaSoft** [comment]
Thank you for your reply. but I m asking this question **How to delay about 2 seconds between statement?** @Chung14011998
