### ISSUE TITLE
How to adding new Language?

### ISSUE THREAD

**Issue by ahmedhassan747474** [dlutton/flutter_tts#164]
How to adding new Language

**Comment by dlutton** [comment]
You'll have to request it through Google (Android) or Apple (iOS).
Google TTS = https://developer.android.com/reference/android/speech/tts/TextToSpeech
Apple TTS = https://developer.apple.com/documentation/avfoundation/avspeechsynthesizer

**Comment by ahmedhassan747474** [comment]
thank you
