### ISSUE TITLE
await speak completion issues - v1.3.0

### ISSUE THREAD

**Issue by nick-uk** [dlutton/flutter_tts#168]
## 🐛 Bug Report

await flutterTts.speak() doesn't block. setCompletionHandler() is not always triggered.

### Expected behavior
Await until competition.

### Reproduction steps
```dart
flutterTts = FlutterTts();
flutterTts.setCompletionHandler(() {
    print('[' +DateTime.now().toString() +']--> from setCompletionHandler()');
});
Future<void> speak(String text) async {
   print('[' + DateTime.now().toString() + '] App says: ' + text);
   await flutterTts.speak(text);
   print('[' + DateTime.now().toString() + ']-> DEBUG: SPEAK COMPLETE');
}
```
>.
-----> output
I/flutter ( 4585): [2020-10-31 14:51:09.226713] App says: Voice is enabled, I can read your everything you want.
I/flutter ( 4585): [2020-10-31 14:51:09.236404]-> DEBUG: SPEAK COMPLETE
I/flutter ( 4585): [2020-10-31 14:51:12.946675]--> from setCompletionHandler()

In a real Android 10 device, it seems the setCompletionHandler() is never triggered.

### Configuration
     Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.22.2 
    • Dart version 2.10.2
    Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Platform android-30, build-tools 29.0.3
    minSdkVersion 21
    targetSdkVersion 29

Android 10  (emulator). Android 10 Samsung (real device)

**Version:** 1.3.0

**Platform:** 
- [ ] :iphone: iOS
- [ x] :robot: Android

**Comment by dlutton** [comment]
Try setting this flag before speaking `await flutterTts.awaitSpeakCompletion(true);`.

**Comment by nick-uk** [comment]
Hi dlutton, 

Perfect. This seems to solve my issue!
