### ISSUE TITLE
Invalid int: "OS" FlutterTtsPlugin.java line 67

### ISSUE THREAD

**Issue by putraxor** [dlutton/flutter_tts#17]
## 🐛 Bug Report
```
Fatal Exception: java.lang.IllegalArgumentException
Invalid int: "OS"
com.eyedeadevelopers.fluttertts.FlutterTtsPlugin$2.onInit (FlutterTtsPlugin.java:67)
```

### Device
**Device**
Brand: samsung
Model: Galaxy Note3
Orientation: Portrait
RAM free: 473.27 MB
Disk free: 12.46 GB
**Operating System**
Version: 5.0
Orientation: Portrait
Rooted: No
**Crash**
Date: Dec 31, 2018, 5:04:00 PM
App version: 3.3.21 (3321)

### Configuration

**Version:** `flutter_tts: ^0.1.1`

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by dlutton** [comment]
Are you testing this on a real device or an emulator?  I'm unable to recreate it using an emulator on a Galaxy device API 5.0.  I did google the error and it appears to be a device specific error (Samsung) along with the API version.  Do you have a full stack trace you're able to provide?  I'll most likely just need to add a IllegalArgumentException check along with the NullPointerException I'm already checking for.

Sources regarding the error being device/API specific.

[Samsung](https://developer.samsung.com/forum/board/thread/view.do?boardName=SDK&messageId=295016)
[Google](https://issuetracker.google.com/issues/37012397)

**Comment by putraxor** [comment]
Unfortunately I can't provide full stack trace since this log come Crashlytic. I seems this crash only on specific device as you said.
I upgraded this plugin to 0.1.2 because it's already blocked with try-catch

**Comment by dlutton** [comment]
Okay great.  I'll include the IllegalArgumentException catch on the next version to ensure it's caught.

**Comment by putraxor** [comment]
I confirm this issue still occurs

**Comment by dlutton** [comment]
I have merged your PR.  Thank you @putraxor
