### ISSUE TITLE
Endless wait if no TTS engine is installed or enabled on the device

### ISSUE THREAD

**Issue by Scias** [dlutton/flutter_tts#172]
## 🐛 Bug Report

It appears that if an Android device doesn't have any TTS engine installed (at least that's the case for Google TTS), calls like getEngines, getLanguages and isLanguageAvailable never return and keep awaiting indefinitely.

I use isLanguageAvailable during my app startup to check if TTS is functional on the device, however it never returns and stalls the whole application forever. I tried with the other methods I mentioned above too with no success.

It used to work fine a few months ago when I last tested this case scenario of a user not having any TTS service available.

I managed to reproduce the issue on 3 different devices + the emulator, (Android 8, 10 and 11) and also from a new blank flutter project.

My app code looks like this : 

```
FlutterTts tts = FlutterTts();
...
await tts.isLanguageAvailable("fr-FR") && await tts.isLanguageAvailable("ja-JP") ? TtsReady = true : TtsReady = false; 
// ^ awaits forever and everything below is never executed
```

Note that I only have and tried with Google TTS. I don't know if the issue occurs with other TTS services.

### Expected behavior

The calls should return null or false and not stall forever.

### Reproduction steps

Make a new flutter project

```
FlutterTts tts = FlutterTts();

@override
  initState() {
    super.initState();
    initTts();
  }

  initTts() async {
    print("hello");
    var t = await tts.getEngines;
    print("world");
    print(t);
  }
```

Normal result if Google TTS is installed/activated :  

```
I/flutter ( 8342): hello
I/flutter ( 8342): world
I/flutter ( 8342): [com.google.android.tts]
```

Disable/uninstall Google TTS
`pm disable com.google.android.tts`

Result after : 

```
I/flutter ( 8657): hello
*crickets*
```

### Configuration

**Version:** 1.3.0

**Platform:** 
- [x] :robot: Android

**Comment by tzachov** [comment]
Had the same issue. Solved it by adding a missing definition in `AndroidManifest.xml` (same level as `application`):
```
<queries>
  <intent>
    <action android:name="android.intent.action.TTS_SERVICE" />
  </intent>
</queries>
```
(Copied from somewhere and the name of the intent was incorrect. This snippet was taken from Android Developer site)

**Comment by TranTuanManh** [comment]
I had the same issue. Anyone has solution?
