### ISSUE TITLE
How to set kate voice for ios en-GB.

### ISSUE THREAD

**Issue by MurtuzaSrashtaSoft** [dlutton/flutter_tts#174]
## 💬 Questions and Help

How to set kate voice for ios en-GB.

I m doing the below code but it's speak **Daniel** voice and I want to set kete voice for the same.

```
Future setLanguage({String value = 'en-US'}) async {
    var result = await objFlutterTts.isLanguageAvailable(value);
    print("setLanguageResult" + result.toString());
    await objFlutterTts.setLanguage(value);
    if (Platform.isIOS) {
      await objFlutterTts.setSharedInstance(true);
      List all = await objFlutterTts.getVoices;
      objFlutterTts.setVoice(all[6]);
      print(all);
      printLog("setVoice " + value.toLowerCase() + "-x-afx#female_1-local");
    }
}

```
Thank you in advice for your help.

![Skype_Picture_2020_11_23T08_28_36_757Z](https://user-images.githubusercontent.com/64843262/99943173-e083a400-2d96-11eb-9fd8-5c98300bbc51.jpeg)

https://stackoverflow.com/questions/64965412/how-to-set-kate-voice-for-ios-en-gb-in-flutter-flutter-tts-pub

**Comment by dlutton** [comment]
@MurtuzaSrashtaSoft, I have a fix for this coming in soon that will allow you set pass in the voice name and language to set the correct voice.

**Comment by MurtuzaSrashtaSoft** [comment]
Thanks for the quick development and response.
