### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by ryanheise** [dlutton/flutter_tts#176]
## 🚀 Feature Requests

See https://dart.dev/null-safety/migration-guide

### Contextualize the feature

Package authors are being encouraged to start migrating their packages by creating a null-safety preview release, starting at the leaves of the dependency graph. For example, flutter_tts will need to migrate to null safety before packages that depend on flutter_tts can migrate to null safety.

### Describe the feature

https://dart.dev/null-safety
https://dart.dev/null-safety/faq

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by dlutton** [comment]
@ryanheise thanks for adding this feature request.  I'll be adding null-safety soon.

**Comment by ryanheise** [comment]
According to this announcement, stable is coming soon and it is time to promote the null safe preleases to stable ahead of the stable SDK release:

https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010

**Comment by IchordeDionysos** [comment]
The new Dart version with null-safety was just released 😍 
https://medium.com/dartlang/announcing-dart-2-12-499a6e689c87

**Comment by dlutton** [comment]
Thank you @IchordeDionysos, I'll try to get this merged in soon.
