### ISSUE TITLE
Unable to read long text

### ISSUE THREAD

**Issue by CalvinTp** [dlutton/flutter_tts#178]
## 🐛 Bug Report

I am using flutter_tts and noticed that if the text is long, the text would not be read out loud on Android platform. I don't have the same issue on iOS. For only have a few sample of test:
- If the length of text is 3500 then there is no issue
- If I double the length of the text to 7000, the text would not be read out loud. 

### Expected behavior
- Always read the text input regardless of the size of the text

### Reproduction steps
- Use long text (e.g > 7000 text length) 

### Configuration
- Android 

**Version:** 
flutter_tts version: 1.3.0
Flutter version: 1.22.4

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by CalvinTp** [comment]
After going through older issues, this issue is similar to issue #66

**Comment by CalvinTp** [comment]
Duplicate of #66

**Comment by dlutton** [comment]
what's your preference for this to work @CalvinTp?  On the Android side, we can add the extra text to the queue rather than flushing the new text.  https://developer.android.com/reference/android/speech/tts/TextToSpeech#QUEUE_ADD

The only problem with adding it to the queue by just looking at the text length on the Android end and splitting up the code is that it may break up in the middle of a word.

**Comment by CalvinTp** [comment]
@dlutton, sorry for the delay in responding as I was tied up. As you pointed out, I also wanted to prevent codes that break the strings based on length as it might breaks in the middle of a word or sentence (which would be bad for narration). 

I wrote some codes below to handle the conditions to find some natural breakpoints for English texts. I have not covered extensively all the conditions. 

The input text is "stringToRead" and you can adjust "breakLength" to any variable near 4000. 

The codes would generate a List of Strings and then call the codes to read each of them individually until everything is read.


```
       
        //Configurable variable 
        int breakLength = 3500;

        List<String> texts = [];

        bool loopContinue = true;
        int startIndex = 0;

        //Debug track count - Not used for functional
        int i = 0;
        while(loopContinue){

          //Final loop break due to smaller than limit
          if (startIndex+breakLength>stringToRead.length-1) {
            String extractStringRange = stringToRead.substring(startIndex, stringToRead.length-1);
            texts.add(extractStringRange);
            break;
          }

          String extractStringRange = stringToRead.substring(startIndex, startIndex+breakLength);

          int breakPoint1 = -1;

          //Condition 1
          for (int index = extractStringRange.indexOf(".\n"); index >= 0; index = extractStringRange.indexOf(".\n", index + 1))
          { breakPoint1 = index; }

          //Condition 2
          if ((breakPoint1 == -1)||(breakPoint1 == null)) {
            for (int index = extractStringRange.indexOf("\n"); index >= 0; index = extractStringRange.indexOf("\n", index + 1)) {
              breakPoint1 = index;
            }
          }

          //Condition 3
          if ((breakPoint1 == -1)||(breakPoint1 == null)) {
            for (int index = extractStringRange.indexOf(". "); index >= 0; index = extractStringRange.indexOf(". ", index + 1)) {
              breakPoint1 = index;
            }
          }

          if ((breakPoint1 != -1)||(breakPoint1 != null)) {
            String extractBreakString = stringToRead.substring(startIndex, startIndex+breakPoint1);
            texts.add(extractBreakString);
            startIndex = startIndex+breakPoint1 + 1;

          } else {
            //Error handling - Provide the remaining string to the end of string and exit the loop
            String extractBreakString = stringToRead.substring(startIndex, stringToRead.length);
            loopContinue = false;
          }

          i++;

          //Error handling - Limit loop instead of causing app to hang for unexpected error
          if (i == 10000) {
            loopContinue = false;
          }

        }

        int speakLoop = 0;
        if(texts.length > 0) {
          flutterTts.speak(texts[speakLoop]);

          flutterTts.setCompletionHandler(() {

            speakLoop++;
            if (speakLoop <texts.length ) {
              flutterTts.speak(texts[speakLoop]);
            } else {
      
            }
          });

        }

```

**Comment by dlutton** [comment]
Either way it sounds like it should be up to the user to split out the text and not the plugin.
I created a PR for you to test when you get a moment.

You can include the branch in your dependency like below and test it out when you get a moment:
```
flutter_tts:
  git:
    url: https://github.com/dlutton/flutter_tts
    ref: android_queue_mode
```
All you have to do is run `await flutterTts.setQueueMode(1);` and then you can split up your code however you wish and run that text within the `speak` method.

As an example if your text is greater than 4k characters, you can run this.
```
await flutterTts.setQueueMode(1);
await flutterTts.speak(text.substring(0, 40000));
await flutterTts.speak(text.substring(3999, 5000));
```
Of course you'd have to know your text and understand the best place to split it so that you don't split in the middle of a word.

Let me know if this will work for you.

**Comment by DevanshiGor** [comment]
> Either way it sounds like it should be up to the user to split out the text and not the plugin. I created a PR for you to test when you get a moment.
> 
> You can include the branch in your dependency like below and test it out when you get a moment:
> 
> ```
> flutter_tts:
>   git:
>     url: https://github.com/dlutton/flutter_tts
>     ref: android_queue_mode
> ```
> 
> All you have to do is run `await flutterTts.setQueueMode(1);` and then you can split up your code however you wish and run that text within the `speak` method.
> 
> As an example if your text is greater than 4k characters, you can run this.
> 
> ```
> await flutterTts.setQueueMode(1);
> await flutterTts.speak(text.substring(0, 40000));
> await flutterTts.speak(text.substring(3999, 5000));
> ```
> 
> Of course you'd have to know your text and understand the best place to split it so that you don't split in the middle of a word.
> 
> Let me know if this will work for you.

 await _flutterTts!.setQueueMode(1);
 👆🏻Worked like Charm !!!
