### ISSUE TITLE
Not able to change male voice (Arabic and English mode)

### ISSUE THREAD

**Issue by khansultan1** [dlutton/flutter_tts#180]
## 🐛 Bug Report
While getting the voice list I'm getting a list of voices available but when trying to set voice, only Female voice is getting even after setting male in both language English or Arabic mode.

 await flutterTts.setVoice("en-us-x-sfg#male_1-local" );

### Expected behavior
it should get a male or female voice based on voice set
### Configuration

**Version:** 0.1.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by dlutton** [comment]
@khansultan1 can you test this PR to see if it works for what you're requesting? #177. If you need assistance on pulling in this dependency using a certain branch, you can look here (https://flutter.dev/docs/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages). Use the ref argument to pin the branch you want to use. In this case, that ref is voice_enhancement. If it all works, I'll merge in the code and update the version number.

Also, note that the method now returns a map of name and locales so when you set it, you'll do something like this await flutterTts.setVoice({"name": "Karen", "locale": "en-AU"});

I'm not a heavy user of the voices, so let me know if you'd like this set a different way and I can make the adjustment.
