### ISSUE TITLE
Support of Icelandic

### ISSUE THREAD

**Issue by thorvalld** [dlutton/flutter_tts#182]
### Describe the feature
It would be so nice to add the support for Icelandic languages in the TTS package, are there any plans for Icelandic ? 

### Platforms affected
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by dlutton** [comment]
@thorvalld unfortunately I'm not able to add specific language support through this flutter package.  This package uses the platform specific package for TTS.  Android uses the google text to speech package and iOS uses Apple's text to speech package.  You'd have to request it through Google or Apple if it's not supported on your device.

**Comment by thorvalld** [comment]
Oh I see, hopefully Google/Apple adds the support for the language soon!
