### ISSUE TITLE
Doesn't work with bluetooth headset on iOS

### ISSUE THREAD

**Issue by meowofficial** [dlutton/flutter_tts#184]
## 🐛 Bug Report

When bluetooth headset connected and tts engine is beginning to speak, it disconnects headset and speaks through speakers. With wire headset it works as expected. Issue occurs only on iOS.

**Comment by dlutton** [comment]
Which iOS categories are you setting?

For example:
```dart
await flutterTts
        .setIosAudioCategory(IosTextToSpeechAudioCategory.playAndRecord, [
      IosTextToSpeechAudioCategoryOptions.allowBluetooth,
      IosTextToSpeechAudioCategoryOptions.allowBluetoothA2DP,
      IosTextToSpeechAudioCategoryOptions.mixWithOthers
    ]);
```

**Comment by meowofficial** [comment]
I didn't set ios audio categories, just used example app from this package.

**Comment by dlutton** [comment]
Do any of the Bluetooth audio categories work for you?
allowBluetooth = https://developer.apple.com/documentation/avfoundation/avaudiosessioncategoryoptions/avaudiosessioncategoryoptionallowbluetooth
allowBluetoothA2DP = https://developer.apple.com/documentation/avfoundation/avaudiosessioncategoryoptions/avaudiosessioncategoryoptionallowbluetootha2dp

**Comment by meowofficial** [comment]
Yeah, it works, thanks
