### ISSUE TITLE
Arabic language support

### ISSUE THREAD

**Issue by kayisi44** [dlutton/flutter_tts#185]
## 🚀 Feature Requests

I think there should be Arabic language support in the Flutter Tts package because now Arabic is one of the languages ​​that are being used frequently and wanted to be learned and we want to add these languages ​​to our applications.

I would be very glad if you could add this feature in the first update to come.

I am working on a language application. I am trying to teach people 5 languages ​​including Arabic in this application, I can use flutter tts in other 4 languages, but I cannot use it in Arabic. I want this update from you because I think this feature will help me a lot in teaching Arabic language.

### Platforms affected (mark all that apply)
- [ X ] :iphone: iOS
- [ X ] :robot: Android

**Comment by dlutton** [comment]
Please see the closed issues requesting language support.

Unfortunately I'm not able to add a language. This package uses the native TTS engines on Android and iOS, so the languages depend on what is supported on the device natively.
