### ISSUE TITLE
[Web, iOS only] Audio not playing if device is muted/ringer is silenced

### ISSUE THREAD

**Issue by JonasJW** [dlutton/flutter_tts#187]
## 🐛 Bug Report

Using flutter web, on iOS devices with safari, the audio is only played when device is unmuted/ringer is silenced.

This issue from `video_player` might be related: https://github.com/flutter/flutter/issues/47524

### Expected behavior

Should play audio if device is muted. Not sure if it is a bug or intended behavior but I would expect it play audio when muted too.

### Configuration

**Version:** 2.0.0

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [x] Flutter Web (iOS only)

**Comment by dlutton** [comment]
@JonasJW this should work with the latest release using the iOS session and mode options (see Readme).  There are no audio features similar on web unfortunately.
