### ISSUE TITLE
example looks weird

### ISSUE THREAD

**Issue by KCKCC** [dlutton/flutter_tts#19]
## 💬 Questions and Help

I just run the example with vscode on emulator
it looks weird
screenshot

 https://imgur.com/ROSxmSN

and debug console logs some rendering problems :

https://pastebin.com/F1G6eGYJ

Am I missing something?

please help! thank you~

Platform is Android

**Comment by dlutton** [comment]
@KCKCC can you share the emulator device and api version you're using?

**Comment by KCKCC** [comment]
yes,the emulator is LDplayer (android 5.1.1 API22)
I try it on my phone today and it works fine,
so this maybe emulator's problem.

**Comment by dlutton** [comment]
@KCKCC please test with latest change when you get a moment.
