### ISSUE TITLE
setLanguage("bn-BD") - not working anymore

### ISSUE THREAD

**Issue by md-siam** [dlutton/flutter_tts#196]
## 🐛 Bug Report

bn-BD was working fine a few days back. But now it's not working.

### Configuration

**Version:** 2.1.0

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by dlutton** [comment]
does this language come back when you run `await flutterTts.getLanguages` ?

**Comment by md-siam** [comment]
flutter: [de-DE, da-DK, en-AU, sv-SE, fr-FR, es-ES, cs-CZ, en-IN, ar-SA, zh-CN, nl-BE, ko-KR, no-NO, pl-PL, zh-TW, fr-CA, fi-FI, pt-PT, ru-RU, sk-SK, it-IT, tr-TR, he-IL, en-ZA, en-US, zh-HK, nl-NL, pt-BR, en-GB, hu-HU, ro-RO, hi-IN, th-TH, el-GR, es-MX, en-IE, id-ID, ja-JP]

I am 100% sure "bn-BD" was there now it's not. How? 😟

**Comment by dlutton** [comment]
Did you maybe change the device you were on or using a different Android API?

**Comment by md-siam** [comment]
![Screen Shot 2021-01-20 at 11 32 34 AM](https://user-images.githubusercontent.com/21225918/105131654-93604c00-5b13-11eb-9267-44decac93325.png)

**Comment by md-siam** [comment]
look at the picture. "bn-BD" + more languages were there.

**Comment by md-siam** [comment]
Android  devices have more languages than Apple devices 😩
![Screen Shot 2021-01-20 at 9 53 22 PM](https://user-images.githubusercontent.com/21225918/105200862-760a9c80-5b6a-11eb-86d4-6e3b4f903c54.png)

**Comment by md-siam** [comment]
Android device:
![Screen Shot 2021-01-20 at 9 51 07 PM](https://user-images.githubusercontent.com/21225918/105200970-8b7fc680-5b6a-11eb-8047-6e70e4af4c15.png)

**Comment by md-siam** [comment]
Android device has way more languages compared to Apple iPhones 🥺

**Comment by dlutton** [comment]
Yes that will occur since this plugin uses platform specific text to speech API calls on each device.  You can see the discussion here. https://github.com/dlutton/flutter_tts/discussions/191.

**Comment by md-siam** [comment]
Thanx your works  🙂
