### ISSUE TITLE
iOS Crashes with: TTSCreateDecryptedDataFromEncryptedData

### ISSUE THREAD

**Issue by obrunsmann** [dlutton/flutter_tts#199]
Since around one week we see iOS crashes rising with the following trace:

```
Crashed: com.apple.TextToSpeech.SpeechThread
0  TextToSpeech                   0x1b012ee38 TTSCreateDecryptedDataFromEncryptedData + 148
1  TextToSpeech                   0x1b012ee9c TTSCreateDecryptedDataFromEncryptedData + 248
2  TextToSpeechBundleSupport      0x1b8fe5674 -[TTSVocalizer loadResource:mimeType:resourceURL:supportsAccurateWordCallbacks:] + 424
3  TextToSpeechBundleSupport      0x1b8fe2a34 -[TTSSpeechServerInstance _loadVoiceResource:voiceResource:] + 484
4  TextToSpeechBundleSupport      0x1b8fe2510 -[TTSSpeechServerInstance _initializeSpeechEngine:] + 1852
5  TextToSpeechBundleSupport      0x1b8fe2794 -[TTSSpeechServerInstance _initializeSpeech:] + 56
6  TextToSpeechBundleSupport      0x1b8fdfc10 -[TTSSpeechServerInstance _processCurrentRequest:] + 64
7  TextToSpeechBundleSupport      0x1b8fe0e44 -[TTSSpeechServerInstance _handleSpeechThread] + 1552
8  TextToSpeechBundleSupport      0x1b8fdfbc0 _SpeechThread + 48
9  libsystem_pthread.dylib        0x1db56db40 _pthread_start + 320
10 libsystem_pthread.dylib        0x1db576768 thread_start + 8
```

We have not changed anything in the way calling the TTS library and also the 2.1 Version is unchanged.

**Version:** 2.1

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by dlutton** [comment]
This appears to be an issue that was addressed by Apple.
https://developer.apple.com/forums/thread/671863

According to that forum, it was an issue with iOS 14.2+, but should be fixed in the latest update.
```A new asset went live today that should resolve this issue, and devices should download it within the next day or so automatically. We will also address the root cause of the crash in a future version of iOS. Those of you seeing spikes in crashes in your apps should see those spikes go away shortly.```

**Comment by obrunsmann** [comment]
Ah okay, that would explain why it occurred all of a sudden without anything being changed in the package.

Then I will watch the thread. Thanks!
