### ISSUE TITLE
Is setting other language working?

### ISSUE THREAD

**Issue by ozexpert** [dlutton/flutter_tts#20]
## 🐛 Bug Report

when calling 
```
await flutterTts.setLanguage("ko-KR");
print(await flutterTts.isLanguageAvailable('ko-KR'));
```
or even with `ko`, I get 
```
D/TTS     (26190): Language is not available - ko
D/TTS     (26190): Language is not available - ko-kr
```

### Expected behavior

Korean language should be available

### Reproduction steps

```
await flutterTts.setLanguage("ko-KR");
print(await flutterTts.isLanguageAvailable('ko-KR'));
```

### Configuration

**Version:** 0.1.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by ozexpert** [comment]
my phone is Samsung "Galaxy Note 8".

**Comment by dlutton** [comment]
@ozexpert I just tested on a galaxy emulator and "ko-KR" is valid.  Which Android API are you testing with?  When I test on an earlier APIs such as 23, it's not available, however newer APIs such as 28 have it available.

[Android getAvailableLanguages](https://developer.android.com/reference/android/speech/tts/TextToSpeech#getAvailableLanguages())

API 23
`[en-US, de-DE, fr, es-ES, de, en, it-IT, it, en-GB, es, fr-FR]`

API 28
`[ko-KR, ru-RU, zh-TW, hu-HU, th-TH, nb-NO, da-DK, tr-TR, et-EE, bs, sw, vi-VN, en-US, sv-SE, su-ID, bn-BD, sk, el-GR, hi-IN, fi-FI, km-KH, bn-IN, fr-FR, uk-UA,en-AU, nl-NL, fr-CA, sr, pt-BR, si-LK, de-DE, ku, cs-CZ, pl-PL, sk-SK, fil-PH, it-IT, ne-NP, hr, zh-CN, es-ES, cy, ja-JP, sq, yue-HK, en-IN, es-US, jv-ID, la, id-ID, ro-RO, ca, ta, en-GB]`

**Comment by ozexpert** [comment]
thanks for the quick response @dlutton however; with my android 8.0 on galaxy note 8, 
```
List<dynamic> languages = await flutterTts.getLanguages;
    print(languages);
```
I get 
```
 [eng-x-lvariant-f02, spa-x-lvariant-f00]
```

**Comment by ozexpert** [comment]
Do i need to run on release build? i'm on debug build. doing `flutter run`

**Comment by dlutton** [comment]
I'm using debug build as well.

I downloaded API 26 and it returns this for flutterTts.getLanguages.
`[en-AU, ko-KR, fr-BE, nl-NL, ru-RU, zh-TW, hu-HU, sr, th-TH, pt-BR, de-DE, si-LK, ku, nb-NO, cs-CZ, da-DK, tr-TR, pl-PL, bs, sw, it-IT, pt-PT, vi-VN, ne-NP, hr, en-US, zh-CN, es-ES, sv-SE, cy, ja-JP, sq, bn-BD, sk, yue-HK, en-IN, hi-IN, es-US, fi-FI, la, bn-IN, km-KH, fr-FR, id-ID, uk-UA, ca, ta, en-GB]`

**Comment by ozexpert** [comment]
with emulator (API 28) 
```
I/flutter ( 4414): [ko-KR, ru-RU, zh-TW, hu-HU, th-TH, nb-NO, da-DK, tr-TR, et-EE, bs, sw, vi-VN, en-US, sv-SE, su-ID, bn-BD, sk, el-GR, hi-IN, fi-FI, km-KH, bn-IN, fr-FR, uk-UA, en-AU, nl-NL, fr-CA, sr, pt-BR, si-LK, de-DE, ku, cs-CZ, pl-PL, sk-SK, fil-PH, it-IT, ne-NP, hr, zh-CN, es-ES, cy, ja-JP, sq, yue-HK, en-IN, es-US, jv-ID, la, id-ID, ro-RO, ca, ta, en-GB]
```
I get above, which is fine.. but with the same codebase and using my real device (Galaxy Note 8), I get 
```
I/flutter (15157): [eng-x-lvariant-f02, spa-x-lvariant-f00]
```
which is a problem. any clue?

**Comment by ozexpert** [comment]
i tried Tts package - https://pub.dartlang.org/documentation/tts/latest/ (not flutter_tts; yours), and seems the getAvailableLanguages outputs
```
[eng-USA-f02, spa-MEX-f00]
```
I think there's something strange about the Samsung Galaxy Note 8. I haven't tested other android devices yet, but something odd is happening. 

I'm actually re-writing my app made with Cordova to Flutter and was using https://github.com/vilic/cordova-plugin-tts plugin for Tts and works fine in the Galaxy Note 8. Wonder what's the difference. I'll try to check the code and come back. Thanks!

**Comment by ozexpert** [comment]
Figured Out. 

![image](https://user-images.githubusercontent.com/787164/50848813-11d16300-132a-11e9-8569-a0e864a277ae.png)
Samsung phone's default is not Google Text-To-Speech engine. 

I have changed my phone to use Google Text-To-Speech, then now it works.

**Comment by dlutton** [comment]
Ah so you were using a different Engine.  Good to know!  Maybe I should include the Android [getEngines](https://developer.android.com/reference/android/speech/tts/TextToSpeech#getEngines()) call in this package.

**Comment by ozexpert** [comment]
@dlutton that would be awesome. the locale string is totally different for Samsung TTS engine, which sucks. 

however, 
https://developer.android.com/reference/android/speech/tts/TextToSpeech.html#TextToSpeech(android.content.Context,%20android.speech.tts.TextToSpeech.OnInitListener,%20java.lang.String)

Looks like you can give an engine package name, would it be better forcing to use google's engine then?

**Comment by ozexpert** [comment]
"com.google.android.tts" seem to be the Google's TTs package name. set as default?

**Comment by dlutton** [comment]
I noticed that as well @ozexpert.  I'll play around with that and see if I can force it through the constructor as you mentioned.

**Comment by dlutton** [comment]
@ozexpert I have pushed a new commit with Google's TTS package set as the default.  Please test when you get a moment.
