### ISSUE TITLE
awaitSpeakCompletion(true) does not work on web

### ISSUE THREAD

**Issue by twogood** [dlutton/flutter_tts#205]
## 🐛 Bug Report

On Flutter web, `flutterTts.speak()` returns immediately even if `awaitSpeakCompletion(true)` has been called.

### Expected behavior

On Flutter web, `flutterTts.speak()` should not return until the utterance is complete when `awaitSpeakCompletion(true)` has been called.

### Reproduction steps

```
    await flutterTts.awaitSpeakCompletion(true);

    print("${DateTime.now()}: before speak");
    var result = await flutterTts.speak("Starting countdown now.");
    print("${DateTime.now()}: after speak");
```

Gives logs like this. Tested on recent Chrome and Firefox on Ubuntu Linux:

```
2021-02-22 17:39:38.192: before speak
2021-02-22 17:39:38.193: after speak

2021-02-22 17:40:16.703: before speak
2021-02-22 17:40:16.705: after speak
```

The value of `result` is `null`.

### Configuration

**Version:** 2.1.0

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [X] :spider_web: Web

**Comment by twogood** [comment]
I'm trying to workaround it with a `_speechCompleter` like in #152 but it seems like the handler set by `setCompletionHandler` is never called.

**Comment by twogood** [comment]
I wonder if `SpeechSynthesisUtterance` i supposed to be reused with a new text?

**Comment by sandeshgoel** [comment]
Is this issue fixed? I still see that "On Flutter web, flutterTts.speak() returns immediately even if awaitSpeakCompletion(true) has been called".

I am using latest version 3.2.3

**Comment by dlutton** [comment]
@sandeshgoel , it doesn't appear I merged in code from the PR for this fix.  I'll get this merged in if it's still an issue.

**Comment by jrheisler** [comment]
It seems to still be an issue.

**Comment by dlutton** [comment]
@jrheisler the latest release should fix your issue.

**Comment by ihorkozar** [comment]
@dlutton @jrheisler I'm using the latest version of the library and I got this issue (
