### ISSUE TITLE
platform-web missing languages

### ISSUE THREAD

**Issue by BoHellgren** [dlutton/flutter_tts#207]
## 🐛 Bug Report

My Flutter app uses text to speech with Swedish text (sv-SE).
```
List<dynamic> languages = await flutterTts.getLanguages;
print(languages);
```
gives the following result in an Android app on my Samsung S10e:

[ko-KR, mr-IN, ru-RU, zh-TW, hu-HU, th-TH, ur-PK, nb-NO, da-DK, tr-TR, et-EE, bs, sw, pt-PT, vi-VN, en-US, **sv-SE**, ar, su-ID, bn-BD, gu-IN, kn-IN, el-GR, hi-IN, fi-FI, km-KH, bn-IN, fr-FR, uk-UA, en-AU, nl-NL, fr-CA, sr, pt-BR, ml-IN, si-LK, de-DE, ku, cs-CZ, pl-PL, sk-SK, fil-PH, it-IT, ne-NP, hr, en-NG, zh-CN, es-ES, cy, ta-IN, ja-JP, sq, yue-HK, en-IN, es-US, jv-ID, la, id-ID, te-IN, ro-RO, ca, en-GB]

but only the following when running the same app as a web app on Chrome on the same Samsung S10e:
[de_DE, en_GB, en_US, es_ES, es_MX, fr_FR, it_IT, pt_BR, ru_RU]

### Configuration
flutter_tts: ^2.1.0
Chrome version 88.0.4324.181
Flutter 1.26.0-17.6.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision a29104a69b (10 days ago) • 2021-02-16 09:26:56 -0800
Engine • revision 21fa8bb99e
Tools • Dart 2.12.0 (build 2.12.0-259.12.beta)

**Comment by dlutton** [comment]
@BoHellgren unfortunately the list of supported languages is going to vary between devices and browsers.  Android will use the google text to speech API where the browser is going to use the web speech API.  iOS uses their own speech synthesis API as well.  So while this plugin uses native code to make the TTS calls, the downside is the support of languages and certain methods will vary.

**Comment by BoHellgren** [comment]
This is very disappointing and makes flutter_tts unusable for my app, which must work on web as well as Android and iOS. It would be good to document this limitation in the README.
The device can speak Swedish, but that function apparently cannot be accessed from Chrome. There are things like Cordova and Ionic Capacitor to access device APIs from web apps. Would you consider using something like that to support Swedish on web also?

**Comment by BoHellgren** [comment]
Update: Swedish works with Chrome on iPhone and Safari on iPhone! Why Chrome on Android does not support Swedish is a mystery.

**Comment by dlutton** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API outlines the speech API for browsers that this plugin uses.  You'd have to get support from Android/Chrome to figure out why your language isn't supported there.  I'll add this info in the README as you suggested.

**Comment by BoHellgren** [comment]
I just found the solution! It turns out that Chrome on Android uses the "default TTS engine", which in my case (Samsung S10e)  was the Samsung TTS engine. Which does not support Swedish! But there is an option in Settings - Language to change the default TTS engine to the Google TTS engine. Which supports many more languages, including Swedish!

I don't suppose that it is possible to choose TTS engine programmatically, in the API?

In any case, it would be good if you could mention this setting in the README! Thanks.
