### ISSUE TITLE
[DeprecateApi] import io.flutter.plugin.common.PluginRegistry.Registrar;

### ISSUE THREAD

**Issue by wuyue92tree** [dlutton/flutter_tts#209]
## 🐛 Bug Report
```
 Running with sound null safety
E/flutter (28132): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method getEngines on channel flutter_tts)
E/flutter (28132): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter (28132): <asynchronous suspension>
E/flutter (28132): #1      FlutterTts.getEngines (package:flutter_tts/flutter_tts.dart:215:21)
E/flutter (28132): <asynchronous suspension>
E/flutter (28132): #2      _MyAppState._getEngines (package:pisces_app/main.dart:99:19)
E/flutter (28132): <asynchronous suspension>
E/flutter (28132):
I/AwareBitmapCacher(28132): init lrucache size: 2097152 pid=28132
```
![image](https://user-images.githubusercontent.com/7899044/110726937-4c5e1f80-8255-11eb-9ef8-70a139bb0c0d.png)

### Reproduction steps
- flutter version: 2.0.1
- Dart version: 2.12.0

```
// build.gradle
allprojects {
    tasks.withType(JavaCompile) {
        options.compilerArgs << "-Xlint:deprecation"
    }
}
```

### Configuration

**Version:** 3.0.0

**Platform:** 
- [ ] :iphone: iOS
- [√] :robot: Android

**Comment by dlutton** [comment]
I'll add a suppression to the deprecated `Registrar` type to fix this.  The registerWith is used to remain compatible with apps that don’t use the v2 Android embedding.

**Comment by JRQuimora** [comment]
I got the same error when i recompiled it with Xlint:deprecation, any news on this?

**Comment by dlutton** [comment]
@JRQuimora this should be more of a warning rather than an error message.
