### ISSUE TITLE
synthesizeToFile Questions

### ISSUE THREAD

**Issue by maares** [dlutton/flutter_tts#210]
Hi, I'm testing your library and was able to setup very rapidly, so thanks for your great library !

As per reading through out the gitHub repository, there's not Pause not seekTo functionality yet for Android, therefore I'm using  synthesizeToFile in other save it and reproduce it with another library. The query I have (and most likely, I'm using the library in the wrong way), is that synthesizeToFile take to long to save the file.

```

Future<void> ttsToFile() async {
    var ttsSpeech = helper.removeAllHtmlTags(html.content);
    var fileName = Platform.isAndroid ? "tts.wav" : "tts.caf";

    await flutterTts
        .synthesizeToFile(ttsSpeech, fileName);

    var directoryPath = "${await helper.getPath()}";

    ttsFilePath = "$directoryPath/$fileName";
  }

```

I can see every 5 seconds how the file increases in size and length. Am I doing something wrong here?, cause await flutterTts.synthesizeToFile(ttsSpeech, fileName) continues but on reality the file is still writing.

Another though, and honestly did not try yet, is to try and save the file with speech rate to max on save, and then reproduce it with a lower speech rate.

**UPDATE**

I did try the approach of setting the speech rate to see if file was save more rapidly, sadly, same result.

As for now implemented a really dirty awful **pause / play** functionality that meets my needs  in the following way.

```

Future<void> playPause() async {
    if (ttsState == 'playing') {
      ttsState = 'idle';
      await flutterTts.stop();
    } else {
      ttsState = 'playing';

      ///really absurd work around
      ///every time is playing will kepp track of the offset speech
      ///every time is paused and play again will start the speach with current offset
      var ttsSpeech = helper.removeAllHtmlTags(html.content);
      var stringList = ttsSpeech.split(' ');
      stringList.removeRange(
        0,
        ttsOffSet,
      );
      ttsSpeech = stringList.join(' ');

      flutterTts.speak(ttsSpeech);
      flutterTts.setProgressHandler((text, startOffset, endOffset, word) {
        ttsOffSet++;
      });
    }
  }

```

I would really appreciate your insights on this, as I'm really convince that I'm using the library in the wrong way.

Many thanks in advance!

**Comment by anilasimbilen** [comment]
I think synthesizeToFile resolves before writing the file. I am also waiting for an update.

**Comment by dlutton** [comment]
@anilasimbilen you're correct, synthesizeToFile resolves before writing the file.  I'll have to fix this.

**Comment by andy-t-wang** [comment]
Any update on this?

**Comment by dlutton** [comment]
@andy-t-wang I'll get to this soon

**Comment by anhtuan23** [comment]
Looking forward to have this issue resolved.

Currently, I have to add a really awkward delay as a workaround

``` dart
    await flutterTts.synthesizeToFile(text, fileName);
    await Future.delayed(const Duration(milliseconds: 200));
```

**Comment by dlutton** [comment]
@anhtuan23 i'll try to get it completed this weekend.

**Comment by dlutton** [comment]
use `await flutterTts.awaitSynthCompletion(true);`
