### ISSUE TITLE
[Question] Offline voices and change voices

### ISSUE THREAD

**Issue by stefanodecillis** [dlutton/flutter_tts#212]
## 💬 Questions and Help

Hi, 
this is the first time I'm playing with the tts so the following questions will be out of my curiosity. 

1. I would like to reproduce some text without an internet connection (offline). Do both iOS and Android support it? From which level of API?
Also, this plugin doesn't work on android emulator (I hope it's just mine) and I guess it's because of the languages installed on the device. There is some way (a free one) to add new voices to the engine? I would like to know if there is this possibility and how does it work.

**Comment by dlutton** [comment]
@stefanodecillis Internet connection is required if languages aren't installed and need to be downloaded.  As long as your android emulator is using the google text to speech engine, it should work.

**Comment by stefanodecillis** [comment]
@dlutton there is a way to install them from "my app"? Or better, can I download "somehow" the voice and then add it as an asset in my application? 
In case we can, how does it work?

**Comment by dlutton** [comment]
@stefanodecillis on android, this package is using the google tts engine.  Unfortunately this package doesn't support other tts engines at this time.

**Comment by stefanodecillis** [comment]
@dlutton thank you for your answer! Closing the thread:)
