### ISSUE TITLE
Need more language support

### ISSUE THREAD

**Issue by Daeon97** [dlutton/flutter_tts#215]
## 🚀 Feature Requests

Support for native Nigerian languages

### Contextualize the feature

I logged flutterTts.getLanguages() to console and didn't find any native Nigerian languages. I am trying to build a TTS related app that voices out words in one of the three major languages in my country unfortunately FlutterTts does not fit into my usecase at the moment. I am sad 😞

### Describe the feature

Support for the three major Nigerian languages- Igbo, Yoruba and Hausa, would be nice 🙂

### Platforms affected (mark all that apply)
- :iphone: iOS
- :robot: Android

**Comment by dlutton** [comment]
@Daeon97 this package uses the native TTS engines on your device.  Android uses the google TTS engine and iOS uses Apple.  Adding languages is out of my hands as that is something that would have to be done on those engines.

**Comment by Daeon97** [comment]
Okay thanks for the clarification
