### ISSUE TITLE
setLanguage function ignores the country code

### ISSUE THREAD

**Issue by Peter1848** [dlutton/flutter_tts#22]
On Android, the setLanguage function ignores the country code:

`flutterTts.setLanguage("en-GB")		// doesn’t work, "en-US" is choosen`

The problematic java line:
```
void setLanguage(String language, Result result) {
Locale locale = new Locale(language);		// You should split the language: new Locale("en", "GB");
```

**Comment by dlutton** [comment]
@Peter1848 good catch.  When you get a moment please test 0.2.2 which should fix that bug.
Thank you!
