### ISSUE TITLE
How do I make Dart wait for an asynchronous call before switching animations?

### ISSUE THREAD

**Issue by abooodbah** [dlutton/flutter_tts#221]
## 💬 Questions and Help

By default The text to speech engine uses an async call, this causes the main Dart thread to go on with whatever line of code comes next, this leads up to another setstate() call after the TTS speak function which reverts the animation state from Speaking to Idle almost instantly.

is there any way to avoid this issue?

I want it to work as follows:

setstate(() => _animation = 'Speaking')

wait until the TTS is finished speaking

setstate(() => _animation = 'Idle')

If I'm misunderstanding something, could you please point it out? in case this is how Dart works then if you have any workarounds that'd be great.

Simplified code for inspection:

```
void _speak(String sentence) async {
    if (!_isSpeaking) {
      setState(() => _animation = 'Speak');
      setState(() => _isSpeaking = true);

      var result = await tts.speak(sentence);
      if (result != null) {
        setState(() => _isListening = false);
        setState(() => _isSpeaking = false);
      }

}

 } else {
      setState(() => _isSpeaking = false);
    }
  }
```
I have using the .then() but it doesn't activate for some reason.

Could someone give me insight on how to use TTS correctly in this situation :<

I have scrolled through the TTS documentation but couldn't find useful information on the problem I'm currently facing.

**Comment by dlutton** [comment]
set `await flutterTts.awaitSpeakCompletion(true);`

**Comment by abooodbah** [comment]
> await flutterTts.awaitSpeakCompletion(true);

I actually have it set to true in my code but still same problem.

**Comment by dlutton** [comment]
@abooodbah can you provide a full example of what you're trying to accomplish?

**Comment by abooodbah** [comment]
> @abooodbah can you provide a full example of what you're trying to accomplish?

I have found a workaround for now using the completion handler. I believe the `if (result != null) {` statement can't be evaluated at first when it is reached since  `tts.speak(sentence);` happens on another thread which is why it is being skipped.
could you confirm whether my assumption is correct?

**Comment by dlutton** [comment]
You can run that `if (result != null)` check after awaiting `tts.speak(sententce)` as it should return a non null value.

**Comment by dlutton** [comment]
Also as you have mentioned, the completion handlers are a good use case for this.
