### ISSUE TITLE
My language is not available on the web, only android, how do I add it? (Th-TH)

### ISSUE THREAD

**Issue by aomlovebank1212** [dlutton/flutter_tts#223]
My language is not available on the web, only android, how do I add it? (Th-TH)

**Comment by dlutton** [comment]
@aomlovebank1212 
web uses the Web Speech API.
https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API
https://wicg.github.io/speech-api/

I'm unable to add languages.

However, when navigating to the example website I put together, I do see th-TH in Chrome and Safari.
https://dlutton.github.io/flutter_tts/#/

**Comment by aomlovebank1212** [comment]
speaktotext() async {
      var u = new SpeechSynthesisUtterance();
      u.lang = 'th-TH';
      u.text = '50 บาท';
      window.speechSynthesis.speak(u);
It doesn't work, now the Thai accent hasn't arrived, what should I do?

**Comment by dlutton** [comment]
@aomlovebank1212, that text and language code works on the example website.  When you run getLanguages, is th-TH on the list that is returned?

**Comment by aomlovebank1212** [comment]
> @aomlovebank1212, that text and language code works on the example website. When you run getLanguages, is th-TH on the list that is returned?

No th-TH here at all. Bro

**Comment by dlutton** [comment]
@aomlovebank1212 that means the language isn't supported on that browser.
