### ISSUE TITLE
[iOS][Real Device] The plugin doesn't work when the app is backgrounded

### ISSUE THREAD

**Issue by yixiang** [dlutton/flutter_tts#225]
I believe it has something to do with the fact that the plugin is trying to do something to the audio session.

I'm certain that the process is running because background location is active.

**Comment by yixiang** [comment]
Console log:

[AXTTSCommon] Failure starting audio queue alp!
[AXTTSCommon] _BeginSpeaking: couldn't begin playback

**Comment by yixiang** [comment]
Ok, it's my bad. Adding audio background mode fixed the problem.
```
        <key>UIBackgroundModes</key>
        <array>
               <string>audio</string>
        </array>
```

**Comment by nayanAubie** [comment]
Adding the above `UIBackgroundModes` still does not work in my case.
iPhone 7 - 15.8.1
