### ISSUE TITLE
[Question] Are the languages supported by each device different?

### ISSUE THREAD

**Issue by nero-angela** [dlutton/flutter_tts#229]
I am wondering if the languages supported by each device are different, and if languages that are not currently supported will be supported by installing the language pack in the OS.

**Comment by dlutton** [comment]
@nero-angela yes, this plugin uses the native TTS engine, so it all depends on the device.

**Comment by nero-angela** [comment]
Thank you for quick response.
As an additional question, if the language of the TTS is different from the text, there is no response. Is there a way to detect if the language setting is wrong?? No messages are called with `setErrorHandler`.

**Comment by dlutton** [comment]
@nero-angela unfortunately there is no language detection in this package,  however I have create a separate package to help with that if you need it.   https://github.com/dlutton/flutter_language_id
