### ISSUE TITLE
getting error when `flutter run --release`

### ISSUE THREAD

**Issue by ozexpert** [dlutton/flutter_tts#23]
## 🐛 Bug Report

error: invalid file path '/Users/****/Github/****/mobile/build/flutter_tts/intermediates/manifests/aapt/release/AndroidManifest.xml'.

error: invalid file path '/Users/****/Github/****/mobile/build/flutter_tts/intermediates/manifests/aapt/release/output.json'.

```
* What went wrong:
Execution failed for task ':flutter_tts:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
```

### Expected behavior

I believe this worked before but seems not after upgrading to flutter_tts: 0.2.0. Tested Android only. 

### Reproduction steps

`flutter run --release`

### Configuration

**Version:** 0.2.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by dlutton** [comment]
@ozexpert Try to run the `flutter clean` command in your project folder and try to build again.

**Comment by dlutton** [comment]
Also, ensure your minSdkVersion in your AndroidManifist.xml file is 16.

**Comment by ozexpert** [comment]
flutter clean did the trick. sorry for the noise.
