### ISSUE TITLE
[Bug] Not working on Android 11 (API 30)

### ISSUE THREAD

**Issue by pavel-birdy** [dlutton/flutter_tts#230]
## 💬 Questions and Help

<img width="424" alt="Screenshot 2021-05-09 at 17 40 10" src="https://user-images.githubusercontent.com/53362329/117574368-605dba80-b0fa-11eb-8f4d-6d622b07e3bc.png">
I couldn't make it work on my project I just copied the code from the example app. The example app is working fine. It's always loading and looks like the  `FlutterTts()` never gets initialized, not sure what I am missing I read the documentation.

**Comment by pavel-birdy** [comment]
<img width="424" alt="Screenshot 2021-05-09 at 17 40 10" src="https://user-images.githubusercontent.com/53362329/117611300-dc9ae100-b180-11eb-9afd-d57337ce86c5.png">
It's working fine on a real device. So it's not an issue for me now. But I would like to know why it didn't work on the emulator when the example app from downloaded source code worked.

**Comment by pavel-birdy** [comment]
Here is the list of versions I tested working on the emulator. Since my app supports only from and above API 24. My phone is running on API 29 (Android 10) 

- API 29 (Android 10.0) (emulator+phone)
- API 28 (Android 9.0) (emulator)
- API 27 (Android 8.1) (emulator)
- API 26 (Android 8.0) (emulator)
- API 25 (Android 7.1.1) (emulator)
- API 24 (Android 7.0) (emulator)

**Comment by dlutton** [comment]
@pavel-birdy I have been testing on API level 30 and it's working.  The video I posted on another issue https://github.com/dlutton/flutter_tts/issues/228  is using API 30 (Android 11.0).

**Comment by vicentemrb** [comment]
I've got the same issue, i put a appbundle on Play Store, then i download it on a device with Android 11, and it doesn't work.
On the docummentations say to put this on the android manifest:
`<queries>
  <intent>
    <action
       android:name="android.intent.action.TTS_SERVICE" />
  </intent>
</queries>`
https://developer.android.com/reference/android/speech/tts/TextToSpeech

**Comment by Ossyyrr** [comment]
The google documentation says :

"Apps targeting Android 11 that use text-to-speech should declare TextToSpeech.Engine#INTENT_ACTION_TTS_SERVICE in the elements of their manifest".

Add the following code just above the <application in your manifest.

<queries>
    <intent>
        <action android:name="android.intent.action.TTS_SERVICE" />
    </intent>
</queries>

**Comment by pavel-birdy** [comment]
@Ossyyrr Thank you so much, It worked 🎉
@dlutton please add this to the documentation.
here is the link https://developer.android.com/reference/android/speech/tts/TextToSpeech
