### ISSUE TITLE
flutter_tts demo code can not work 

### ISSUE THREAD

**Issue by Manrupt** [dlutton/flutter_tts#232]
i copied example code but it can not works, it's even can not get a expect result of method  flutterTts.getLanguages. I tried printing the snapshot values and got this: 
  **AsyncSnapshot<dynamic>(ConnectionState.waiting, null, null, null)** 
It seem like snapshot always be waiting state.  How can I fix it ?
ps:  
flutter_tts version  3.0.0
dart version  ">=2.12.0 <3.0.0"
device info:  Android 11   (Oneplus 7 Pro)
flutter doctor:
[✓] Flutter (Channel master, 2.2.0-11.0.pre.126, on macOS 11.2.3 20D91 darwin-arm, locale zh-Hans-CN)
    • Flutter version 2.2.0-11.0.pre.126 at /Users/manrupt/app/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 600e489313 (4 weeks ago), 2021-04-15 01:04:03 -0400
    • Engine revision dcdc42b715
    • Dart version 2.14.0 (build 2.14.0-4.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/manrupt/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 56.0.5
    • Dart plugin version 211.7233

[✓] Connected device (2 available)
    • GM1910 (mobile) • 30fe4d2c • android-arm64  • Android 11 (API 30)
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 90.0.4430.93

**Comment by Ossyyrr** [comment]
I have the same problem, it works for me on some devices and not on others.

**Comment by dlutton** [comment]
@Manrupt is this still an issue with the latest release?
