### ISSUE TITLE
awaitSpeakCompletion does not wait correctly?

### ISSUE THREAD

**Issue by meydominic** [dlutton/flutter_tts#234]
## 🐛 Bug Report

Hey,
I don't know how to explain correctly. Maybe I'm doing something wrong. If I set awaitSpeakCompletion to true and calling one `speak` directly after another, it won't speak the second one.

### Expected behavior

The second call should wait for the first one to finish

### Configuration

**Version:** 3.1.0

Flutter: 2.0.6

Tried on a real Android 11 device and on Android 11 emulator.

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

Example code:

Part of SpeechController class:
```Dart
  Future<void> speak(String text) async {
    final bool enabled = app<TextToSpeechSettings>().enabled.value;
    if (enabled == null || !enabled || text == null || text.isEmpty) {
      return;
    }

    await flutterTts.awaitSpeakCompletion(true);
    await flutterTts.speak(text.toLowerCase());
}
```

How I call `speak` :
```Dart
            app<SpeechController>()
                .speak(MenuText.rebooking());
            app<SpeechController>()
                .speak(RebookingText.ttsOnVisitSearchScreen());
```

**Comment by dlutton** [comment]
`await flutterTts.awaitSpeakCompletion(true);` only needs to be called once to enable to disable.  You do not need to call it each time speak is called.  Is your SpeechController a static class?  It's difficult to know the exact issue here without the full code, but I'll try to replicate on an Android 11 emulator.

**Comment by meydominic** [comment]
No it's not static. Tomorrow I can try on an Android 10 emulator if there is any difference and on an iOS emulator (if tts is working there).

Maybe I expressed wrong. The second `speak` does not wait for the first to finish. I thought all attempts will wait (like a queue?).

But I think I have to implement something like a queue myself (`Queue<string>`).

**Comment by dlutton** [comment]
@meydominic you shouldn't have to queue it up yourself.  In Android, you can also try to `await flutterTts.setQueueMode(1);`

**Comment by meydominic** [comment]
For Android it's nice, but I need it for iOS too later :/ But thank you, didn't know about setQueueMode

**Comment by meydominic** [comment]
I am aware that I call both speaks without `await`. But if I understand it correctly the tts implementation should put it on an queue on Android if I set `setQueueMode`.

**Comment by meydominic** [comment]
Any news?

**Comment by dlutton** [comment]
@meydominic It's definitely working fine in a basic example, based on your WIP example I can only assume that you're instantiating FlutterTts on each call.  Have you tried making TtsService a singleton?

**Comment by meydominic** [comment]
Hey,
thanks for your response. I'll have to test it. We are working with Get_It package, which creates one object for the whole application.
