### ISSUE TITLE
[Android] speech rate is at normal when the value is at 1.0.

### ISSUE THREAD

**Issue by actow** [dlutton/flutter_tts#236]
REF: https://developer.android.com/reference/android/speech/tts/TextToSpeech#setSpeechRate(float)
REF: https://github.com/dlutton/flutter_tts/blob/master/lib/flutter_tts.dart#L137
REF: https://github.com/dlutton/flutter_tts/blob/master/android/src/main/java/com/tundralabs/fluttertts/FlutterTtsPlugin.java#L262

This is different from iOS API, where 0.5 means normal.

To make it consistent, we need to do one of the following.

Option 1:
- Change flutter_tts API documentation to reflect that 1.0 means normal.
- Change iOS code to map flutter 1.0 to iOS 0.5

Option 2:
- Keep flutter_tts API documentation the same.
- Change Android code to map flutter 0.5 to Android 1.0.

Option 3:
- Update the [comment](https://github.com/dlutton/flutter_tts/blob/master/android/src/main/java/com/tundralabs/fluttertts/FlutterTtsPlugin.java#L262) to correctly reflect the inconsistency.

Option 3 is the safest approach and should be done as a short term fix if we are going with option 1 or 2 soon.

Between 1 & 2, given that option 1 is a breaking change and option 2 is not (at least not according to flutter_tts documentation), option 2 is preferred. What's more all 3 other platforms that supports speech rate (iOS, mac and web) have 0.5 as the normal.

**Comment by actow** [comment]
@dlutton Before you start diving into this yourself. Could you look at my pull request first?

**Comment by ferjlozada** [comment]
How can I shutdown tts and return to the default values?
