### ISSUE TITLE
It doesn't complete a long text.

### ISSUE THREAD

**Issue by furkankaradas** [dlutton/flutter_tts#239]
## 🐛 Bug Report

I run the code you have given as an example. When I give a text like the one below, it reads up to half of the third sentence.

Given text: "Fossils are another way that ancient life is preserved. Most fossils include an animal’s hard parts, such as teeth and bones. One type of fossil, called a trace fossil, may also include eggs, tooth marks, contents of the guts, and fossil excrement. Some products from ancient life offer us more than scientific knowledge. One such product is coal, a solid fuel of plant origin. It develops over millions of years, during which swamp vegetation is submerged in water, depleted of oxygen, and covered by layers and layers of sand and mud. These overlapping layers settle with the Earth’s movements and are compressed over time."

### Configuration

**Version:** 3.0.0

**Platform:** 
- Web

**Comment by dlutton** [comment]
Are you testing this in Chrome?  If so this appears to be a bug with Chrome.
https://bugs.chromium.org/p/chromium/issues/detail?id=335907

**Comment by furkankaradas** [comment]
I am testing in Chrome. Seem Chrome bug. If I will have any solution, I will share it. 

Thank you for supporting.
