### ISSUE TITLE
How can we change the voice from female to male?

### ISSUE THREAD

**Issue by SreehariRajeev** [dlutton/flutter_tts#247]
## 💬 Questions and Help
Hi, can anyone please tell me how I can change the voice from female to male voice,
and one more thing, is three any way to add custom voices.

**Comment by Logic2Paradigm** [comment]
Change the pitch
`
final FlutterTts flutterTts = FlutterTts();
flutterTts.setPitch(1.0); //higher pitch for female, lower for male
`

**Comment by dlutton** [comment]
@SreehariRajeev this plugin uses platform specific engines, so the list of voices and languages depend on the device and engine being used.  I cannot add custom voices or languages to this plugin.

**Comment by kalimaty** [comment]
Future<void> changeVoice(Voice vc) async {
    double pitch;
    String voice;
    switch (vc) {
      case Voice.male:
        pitch = 0.8;
        voice = 'en-us-x-sfg#male_1-local';
        break;
      case Voice.boy:
        pitch = 1.8;
        voice = 'en-us-x-sfg#male_1-local';
        break;
      case Voice.female:
        pitch = 1.0;
        voice = 'en-us-x-sfg#female_1-local';
        break;
      case Voice.girl:
        pitch = 1.7;
        voice = 'en-us-x-sfg#female_1-local';
        break;
      default:
        pitch = 1.0;
        voice = 'en-US-language';
    }

    await flutterTts.setPitch(pitch);
    await flutterTts.setVoice({'name': voice, 'locale': 'en-US'});
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('voice', vc.toString());
    currentVoice = vc;
    notifyListeners();
  }

**Comment by jaykukadiya99** [comment]
Hey @dlutton @kalimaty 

I can't find the voice of a female in the getVoices() function. Could you please let me know how to use it in a newer version, or which version are you using?
