### ISSUE TITLE
synthesizeToFile() mp3 header missing while recording!

### ISSUE THREAD

**Issue by divshekhar** [dlutton/flutter_tts#250]
## 💬 Questions and Help
I am trying to merge multiple mp3s (Flutter_FFmpeg) generated using `synthesizeToFile()`. 
The FFmpeg throws error:

```
W/mobile-ffmpeg(13094): [mp3 @ 0x7ef755ee00] Format mp3 detected only with low score of 1, misdetection possible!
E/mobile-ffmpeg(13094): [mp3 @ 0x7ef755ee00] Failed to read frame size: Could not seek to 1026.
D/flutter-ffmpeg(13094): FFmpeg exited with rc: 1
```

Is this error from `synthesizeToFile()` or might be FFmpeg's bug? Is there any solution to this issue?

**Comment by dlutton** [comment]
The error is coming from ffmpeg per the logs, unfortunately I'm not familiar with that plugin.  Can you open an issue with them and let me know if there is anything I can do on my end to help resolve the issue.

**Comment by divshekhar** [comment]
Thank you for clarifying, I will try to get clarity about the issue from the ffmpeg team. you may close this issue for now.
