### ISSUE TITLE
 This version of flutter_tts will break your Android build

### ISSUE THREAD

**Issue by tmxdyf** [dlutton/flutter_tts#257]
## 🐛 Bug Report

WARNING: This version of flutter_tts will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.

**Version:** ^3.2.1

**Platform:** 
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.18363.1139], locale zh-CN)
    • Flutter version 2.2.3 at C:\CYStudio\flutter
    • Framework revision f4abaa0735 (2 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\CYStudio\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = D:\CYStudio\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

**Comment by dlutton** [comment]
@tmxdyf is your build failing for Androidx?  this plugin should be compatible with androidx.

**Comment by yasaman93** [comment]
I am using the last version of flutter_tts (3.2.2) and I get this error as well. 
There is no error when I want to build apk with this command: flutter build apk --split-per-abi
But when I run "gradlew build" in android directory, I get this error:

WARNING: This version of flutter_tts will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.

**Comment by dlutton** [comment]
thanks for the info @yasaman93 , I'll look into correcting that.

**Comment by dlutton** [comment]
@JosephIbe what version of flutter and android API are you on?

**Comment by dlutton** [comment]
@JosephIbe the latest version should work for you.
