### ISSUE TITLE
collection == null - (known issue with API 21 & 22)

### ISSUE THREAD

**Issue by zxj17815** [dlutton/flutter_tts#26]
## 💬 Questions and Help

Provide question related to this flutter plugin.
I encountered this problem, but the android version 5.0.1 cannot be changed, how should I modify the code to solve this problem

**Comment by dlutton** [comment]
@zxj17815 can you clarify your ask here?  Are you asking to receive an error back so you can handle the error in your code?

**Comment by zxj17815** [comment]
Error message：getAvailableLanguages: collection == null - (known issue with API 21 & 22)

**Comment by dlutton** [comment]
@zxj17815 Are you asking for a fall back on the getAvailableLanguages method such as `if Build.VERSION.SDK_INT >= 21` check?

**Comment by zxj17815** [comment]
yea,I set the judgment,that's fine now, thank you

**Comment by dlutton** [comment]
@zxj17815 great, I'll get that added in the next couple of days.

**Comment by dlutton** [comment]
@zxj17815 I'm not sure which method you were receiving this error on, but hopefully it's working for you now.

**Comment by zxj17815** [comment]
great，it's working

**Comment by ekuleshov** [comment]
@dlutton may I ask why minSdk was bumped for this? Were there some tts issues with 16?

**Comment by dlutton** [comment]
@ekuleshov Primarily because this method and a few other methods being used weren't introduced until a later API version.  We could write some fall backs or a work around, however I didn't have the time to do so.  I'm always open to PRs. :)
