### ISSUE TITLE
TTS plugin crashes app when speak() method is called multiple times

### ISSUE THREAD

**Issue by ekuleshov** [dlutton/flutter_tts#260]
## 🐛 Bug Report

A Flutter app crashes from within FlutterTtsPlugin with this stack trace.

```
java.lang.IllegalStateException: Reply already submitted
 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:155)
 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
 	at com.tundralabs.fluttertts.FlutterTtsPlugin$2.run(FlutterTtsPlugin.java:188)
 	at android.os.Handler.handleCallback(Handler.java:938)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.java:223)
 	at android.app.ActivityThread.main(ActivityThread.java:7664)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
### Expected behavior

No crash would be nice

### Reproduction steps

Wasn't been  able to isolate exact steps. It could be related to multiple concurrent calls to .`speak()` method. Each of them is only to speak a few words.

### Configuration

**Version:** 3.2.2

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android

```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.7 19H1217 darwin-x64, locale en-CA)
    • Flutter version 2.2.3 at /Users/eu/Downloads/flutter
    • Framework revision f4abaa0735 (3 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Connected device
    • Pixel 3 XL (mobile) • 8B2Y0T02X • android-arm64  • Android 11 (API 30)

```

**Comment by dlutton** [comment]
@ekuleshov Can you give an example of what you're trying to accomplish with calling speak multiple times concurrently?

**Comment by ekuleshov-idexx** [comment]
@dlutton nothing special. I have two async methods kicked in from external events, one writes some data to DB ant then it triggers first speak() to announce values saved and also triggers another async method to crop video captured from the camera and associated with saved data, after video is cropped and the camera recording is restarted after that the 2nd speak() method is called to say "Ready".

The thing is I usually don't hear this 2nd announcement if 1st announcement hasn't finished speaking.

Even tried to add awaitSpeakCompletion(true), which seem to be helped with above crash, but still no 2nd announcement.

**Comment by dlutton** [comment]
thanks for the explanation @ekuleshov.  In the event the 1st announcement hasn't finished speaking, are you looking for the 1st announcement to stop and then play the 2nd announcement, or are you looking for it to play over the first announcement?

**Comment by ekuleshov** [comment]
@dlutton the data announcement is not good to cut off. And the "Ready" announcement is also informative, so user can start the next thing/cycle after that. Though I don't think it is possible that those announcements could happen backwards (i.e. "Ready" comes first). So, I'd prefer it 1st is finished and then the 2nd is played. Like I said, I've added awaitForSpeakingCompletion() before calling speak() again, but that didn't seem to change things on Android.

I haven't tested on ios yet. Having troubles with getting debug builds to a real device, so have to go trough TestFlight.

**Comment by ekuleshov** [comment]
Should be the same instance. I'm using `get` state manager, so I think it is the same instance. Here is my TtsProvider class below. Both of those announcments are passing `true` for awaiting completion.

Though it was still odd to see that original crash when awaitCompletion is not used

```
import 'package:flutter/foundation.dart';
import 'package:flutter_tts/flutter_tts.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'package:get/get.dart';

class TtsProvider {
  static TtsProvider get to => Get.find();

  bool _isEnabled = false;
  FlutterTts _flutterTts;

  bool get isEnabled => _isEnabled;

  init() async {
    _loadTts();

    _flutterTts = FlutterTts();
    _flutterTts.setErrorHandler((message) async {
      ... log errors
    });

    await _flutterTts.getLanguages;
    await _flutterTts.getVoices;
    await _flutterTts.setLanguage("en-US");
    await _flutterTts.setQueueMode(0);
  }

  _loadTts() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    _isEnabled = prefs.getBool(_PREFS_TTS) ?? false;
  }

  save(bool isEnabled) async {
    .. update prefs
  }

  speak(String text, [ bool awaitCompletion = false]) async {
    if (_isEnabled) {
      if (awaitCompletion) {
        await _flutterTts.awaitSpeakCompletion(true);
      }
      debugPrint('### $text');
      await _flutterTts.speak(text);
    }
  }

  ...
}

**Comment by dlutton** [comment]
@ekuleshov it might be a race condition issue.  Did you try setting queue mode to 1?  I'll also try to replicate the issue locally.

**Comment by ekuleshov-idexx** [comment]
@dlutton yes, tried that and didn't notice any difference. I see that 2nd utterance is printed to console about same time 1st one finished speaking

**Comment by dlutton** [comment]
@ekuleshov thanks for the info, I'll take a look at this bug.  It sounds like result.sucess is being called more times than it should from the android platform code.

**Comment by dlutton** [comment]
@ekuleshov  when you call your speak method ```speak(String text, [ bool awaitCompletion = false])``` are you awaiting that?

**Comment by ekuleshov** [comment]
@dlutton hmm. It is awaiting on the "ready" announcement (which gets missed) and not awaiting on the data read out announcement. Should I await on both?

**Comment by dlutton** [comment]
I think with the way you're using it, you should try ensure you're not calling `awaitSpeakCompletion` or set it to false and instead keep your queue mode set to 1 in your init() `await _flutterTts.setQueueMode(1)`.

**Comment by ekuleshov** [comment]
@dlutton great. it looks like it is speaking at the right times now.

The only question is how it would behave on iOS? I thought `.setQueueMode(1)` is not supported there.

**Comment by dlutton** [comment]
@ekuleshov sorry I didn't realize you trying this on iOS as well, so that wouldn't work on iOS.  I'm not familiar with "get" state management, however I'm assuming it's calling the first speak and then calling the second speak which returns a result and then the first speak tries to send a result back when done and you end up with your error.  In that case you'll need to use the `awaitSpeakCompletion` and figure out if there is a way to await the Get.find() or some other Get command that is being ran.

**Comment by ekuleshov** [comment]
@dlutton all get state manager does - making sure there is only one tts plugin instance in the app. It doesn't do anything about async execution. So, it seems like we are back to square one - when multiple calls to `.speak()` are being sent from different async methods.

The tts plugin does not seem to handle serial execution of the `.speak()` calls... Should I build my own queue and pull messages to speak from there, essentially making tts speak() calls serialized.

**Comment by dlutton** [comment]
that makes sense @ekuleshov, when you get your singleton back, do you await your speak method?

**Comment by ekuleshov** [comment]
No. Not awaiting in my async `speak()` method, though that method delegates to `FlutterTts.speak()` and I am awaiting in it there.

**Comment by ekuleshov** [comment]
@dlutton I tried to add await on my wrappers around awaited `FlutterTts.speak(..)` methods.

What I observe is that when two `speak()` calls have been submitted, the 2nd call gets skipped/swallowed if the 1st call haven't finished speaking.

I'm also awaiting on `FlutterTts.awaitSpeakCompletion(true)` but not sure if this call need to be done at init time only or before every `speak()` call.

**Comment by dlutton** [comment]
@ekuleshov thanks for testing that and it's pretty much what I assumed what was happening.  To your last point, `flutterTts.awaitSpeakCompletion(true)` only needs to be set once so init is sufficient.   Do you have a small sample app on github somewhere using Get so I can do some additional testing?

**Comment by ekuleshov** [comment]
@dlutton don't really need `get` plugin to reproduce this. The the `flutter_tts` example I just replaced this line:

```
        await flutterTts.speak(_newVoiceText!);
```

with this (that is basically simulate my case):

```
        var texts = _newVoiceText!.split(";");
        if(texts.length > 1) {
          Future.delayed(Duration(milliseconds: 200),
              () async {
                print('### ${texts[1]}');
                return await flutterTts.speak(texts[1]);
              });
        }

        print('### ${texts[0]}');
        await flutterTts.speak(texts[0]);
```

then enter text like this and tap play:

`12.33 first entry 0.33;ready`

I see on Console that `### ready` is printed before the first utterance finished playing, but the 2nd utterance never plays.

**Comment by dlutton** [comment]
okay great thanks for that snipped of code, I'll play around with that.

**Comment by davidgalarza** [comment]
I'm facing the same issue. I'm not able to reproduce it by myself but I'm receiving reports of that on Crashlytics.
The error Happens on android 8 devices.
<img width="465" alt="Captura de Pantalla 2021-10-06 a la(s) 12 31 21" src="https://user-images.githubusercontent.com/20847597/136254219-3d09ef18-0ce8-4a03-94da-d647d7b1ba2f.png">
And primarily on Huawei devices.
<img width="471" alt="Captura de Pantalla 2021-10-06 a la(s) 12 33 41" src="https://user-images.githubusercontent.com/20847597/136254534-a4777be0-6e53-4081-8021-9fb5edd90372.png">
<img width="459" alt="Captura de Pantalla 2021-10-06 a la(s) 12 34 52" src="https://user-images.githubusercontent.com/20847597/136254693-a9fcef1f-88e6-46e5-bcb0-2b89e046adf2.png">

**Comment by Zeswen** [comment]
Same here. All our Android 8 - 8.1 users are experiencing crashes using FlutterTTS.
```
Fatal Exception: java.lang.IllegalStateException
Reply already submitted
io.flutter.embedding.engine.f.b$a.a (Unknown Source:35)
h.a.c.a.j$a$a.a (Unknown Source:14)
f.i.a.a.e (Unknown Source:630)
f.i.a.a$e.run (Unknown Source:6)
f.i.a.a$d.onInit (Unknown Source:110)
android.speech.tts.TextToSpeech.dispatchOnInit (TextToSpeech.java:824)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:870)
```

**Comment by dlutton** [comment]
@Zeswen are you using setEngine or do you have any parts of code you can share that is causing the crash?

**Comment by dlutton** [comment]
@ekuleshov
When you get a moment please test the latest release 3.2.3 which should fix the issue you have based on the information you provided me above.

In your case, you'll need both `await flutterTts.setQueueMode(1);` and `await flutterTts.awaitSpeakCompletion(true);`.  Also note that you only need to call those methods once and not every single time you run the speak method.

**Comment by ekuleshov** [comment]
@dlutton thank you. Will do. Can those methods be called on all platforms or conditionally on Android only?

**Comment by dlutton** [comment]
@ekuleshov setQueueMode is only available for Android, so this fix is specific to Android. The awaitSpeakCompletion will work the same on iOS, however the fix is specific to your use case of a request to speak coming into the platform while a speak is already occurring.  The queue mode with the awaitSpeakCompletion together wasn't working properly.  Let me know if you run into any issues on iOS with this since I only researched Android when I got some time over the last weekend.

**Comment by ekuleshov** [comment]
> @ekuleshov setQueueMode is only available for Android, so this fix is specific to Android. The awaitSpeakCompletion will work the same on iOS, however the fix is specific to your use case of a request to speak coming into the platform while a speak is already occurring. The queue mode with the awaitSpeakCompletion together wasn't working properly. Let me know if you run into any issues on iOS with this since I only researched Android when I had some time over the past weekend.

Verified. The TTS seem to be working with .setQueueMode(1); and .awaitSpeakCompletion(true) one time init on Android.

**Comment by Zeswen** [comment]
> @Zeswen are you using setEngine or do you have any parts of code you can share that is causing the crash?

Excuse me for the late response, the problem was unrelated to this since we didn't use `setEngine`.

**Comment by hustjs** [comment]
in my case, I found the reason is that `pendingMethodCalls` always don't remove
