### ISSUE TITLE
ios lock screen cannot play tts

### ISSUE THREAD

**Issue by jay2hk2hk** [dlutton/flutter_tts#262]
when i play the tts, iphone cannot play when i locked screen , how cn i fix it?

**Comment by butterbrain** [comment]
I found (from the audio_service plugin tutorial) that just adding the following to the
./ios/Runner/info.plist
makes it work on my iPad...

    <key>UIBackgroundModes</key>
    <array>
        <string>audio</string>
    </array>

If you already have UIBackgroundModes in the list, add the <audio> string to the array.

**Comment by dlutton** [comment]
@butterbrain thanks for providing the solution.

https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html#//apple_ref/doc/plist/info/UIBackgroundModes

https://developer.apple.com/documentation/bundleresources/information_property_list/uibackgroundmodes
