### ISSUE TITLE
Problem with gradle version and AndroidManifest on the lib

### ISSUE THREAD

**Issue by Luterium** [dlutton/flutter_tts#263]
## 🐛 Bug Report
I updated my flutter_tts to the latest resolvable version (3.2.2) and it started showing those errors when I try to build the project. I have multiDex enabled (2.0.1) on my build.gradle and I've never had such a problem before. If anyone can think of any solution I'd be grateful

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\Luterium\Documents\novel\novel\build\flutter_tts\intermediates\library_manifest\debug\AndroidManifest.xml:9:5-13:15: AAPT: error: unexpected element <queries> found in <manifest>.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility.
Building plugin flutter_tts...
         *********************************************************
WARNING: This version of flutter_tts will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_tts-3.2.2\android\build.gradle' line: 41

* What went wrong:
A problem occurred evaluating root project 'flutter_tts'.
> Failed to apply plugin [id 'com.android.library']
   > Minimum supported Gradle version is 5.4.1. Current version is 5.1.1. If using the gradle wrapper, try editing the distributionUrl in C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_tts-3.2.2\android\gradle\wrapper\gradle-wrapper.properties to gradle-5.4.1-all.zip

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

### Configuration

**Version:** 3.2.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [versÃ£o 10.0.19042.1110], locale pt-BR)
    • Flutter version 2.2.3 at C:\flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)

**Dependencies**
dependencies:
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.3
  diacritic: ^0.1.3
  dio: ^4.0.0
  file: ^6.1.2
  fluro: ^2.0.3
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.1
  flutter_localizations:
    sdk: flutter
  flutter_tts: ^3.2.2
  focus_detector: ^2.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  infinite_scroll_pagination: ^3.0.1
  intl: ^0.17.0
  json_serializable: ^4.1.4
  logger: ^1.0.0
  path_provider: ^2.0.2
  provider: ^5.0.0
  rxdart: ^0.26.0
  scroll_to_index: ^2.0.0
  

dev_dependencies:
  build_runner: ^2.1.1
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0

**Comment by dlutton** [comment]
@Luterium have you tried upgrading your gradle version?

**Comment by Luterium** [comment]
My grave version is 5.6.2, the library is 5.1.1 on 3.2.2, tho

**Comment by dlutton** [comment]
@Luterium ah okay I mis-understood the error.  I'll update the version.

**Comment by kirill-plotnikov** [comment]
Is any progress with that issue?

**Comment by dlutton** [comment]
@kirill-plotnikov sorry I've been crazy busy, but this is a simple fix, so I'll try to roll it out in a small patch update this weekend.

**Comment by ferjlozada** [comment]
In your project, in build.gradle file of android folder change to 'com.android.tools.build:gradle:4.0.1' and in gradle-wrapper.jar file of folder gradle / wrapper change to 'gradle-6.1 .1-all.zip'

**Comment by dlutton** [comment]
this has been fixed in the latest version
