### ISSUE TITLE
Version IOS don't support Vietnamese Language

### ISSUE THREAD

**Issue by ferguquang** [dlutton/flutter_tts#264]
## 🚀 Feature Requests

Version IOS don't support Vietnamese Language

I build in Android, have Vietnamese Language, but in IOS don't have Vietnamese Language.

**Comment by dlutton** [comment]
@ferguquang unfortunately I don't control the languages that are supported on each device.  Android uses the native google TTS engine by default and iOS uses Apple's native TTS engine and language support depend on the device and OS version.
