### ISSUE TITLE
IOS integration not using create i-swift for flutter tts 

### ISSUE THREAD

**Issue by cokn-s** [dlutton/flutter_tts#27]
I am having an issue with the IOS integration for this plugin. 

Background:
I know there is an known issue using the Objective-C template but I am trying to add this plugin to my app that has a lot of custom iOS already in it (specifically a ShareExtension) and it would be a pain to recreate the app using the Swift template.

Somewhat solution:
I followed the advice seen here: [https://github.com/flutter/flutter/issues/16049#issuecomment-382664356](url) and was able to get rid of the Swift version fault but now I am encountering another fault (shown below) and have been unable to fix it.  My Swift programming is very minimal so I would appreciate any help you can give.  Thanks!

> Xcode's output:
↳
    <unknown>:0: error: module map file 'xxx/build/ios/Debug-iphonesimulator/flutter_tts/
flutter_tts.modulemap' not found
    <unknown>:0: error: module map file 'xxx/build/ios/Debug-iphonesimulator/flutter_tts/
flutter_tts.modulemap' not found
    <unknown>:0: error: module map file 'xxx/build/ios/Debug-iphonesimulator/flutter_tts/
flutter_tts.modulemap' not found
    <unknown>:0: error: module map file 'xxx/build/ios/Debug-iphonesimulator/flutter_tts/
flutter_tts.modulemap' not found

**Comment by dlutton** [comment]
@cokn-s Unfortunately I have not come across that error, so I don't have a solution for you.  Have you tried running `flutter clean` and/or removing the DerivedData folder?

**Comment by cokn-s** [comment]
@dlutton I have ran flutter clean quite a lot.  As for the DerivedData folder I am not sure where that is located, can you point me in the right direction?

**Comment by cokn-s** [comment]
@dlutton never mind, a quick google search told me what I needed to know.  I will try deleting that folder and see what happens

**Comment by cokn-s** [comment]
@dlutton Just wanted to give a quick update that the error has persisted after I removed the DerivedData folder and did the flutter clean.  If you have any more ideas please feel free to share!

**Comment by dlutton** [comment]
@cokn-s Other than what I mentioned, unfortunately I wouldn't know how to solve this other than recreating with the swift flag.

**Comment by rishabhdugar** [comment]
same issue, any luck without recreating every damn thing?
