### ISSUE TITLE
Build exception

### ISSUE THREAD

**Issue by hasanm08** [dlutton/flutter_tts#275]
## 🐛 Bug Report

```
         *********************************************************
WARNING: This version of flutter_tts will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.

FAILURE: Build failed with an exception.
         *********************************************************

```

### Configuration

**Version:** 3.2.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by ferjlozada** [comment]
In your project, in build.gradle file of android folder change to 'com.android.tools.build:gradle:4.0.1' and in gradle-wrapper.jar file of folder gradle / wrapper change to 'gradle-6.1 .1-all.zip'

**Comment by alyyasser** [comment]
changed your `compileSdkVersion` and `targetSdkVersion` in `android/app/build.gradle` to 31

**Comment by Rob-wang** [comment]
Flutter 2.5.3 • channel stable •
Tools • Dart 2.14.4

**Comment by PawanGhewande** [comment]
Not sure, but try adding this in your  AndroidManifest.xml
 ```
<queries>  
  <intent>  
      <action android:name="android.intent.action.TTS_SERVICE" />  
  </intent>  
 </queries> 
``` 
and also comment this import if possible  import 'package:flutter_tts/flutter_tts_web.dart';

**Comment by Rob-wang** [comment]
> Not sure, but try adding this in your AndroidManifest.xml
> 
> ```
> <queries>  
>  <intent>  
>      <action android:name="android.intent.action.TTS_SERVICE" />  
>  </intent>  
> </queries> 
> ```
> 
> and also comment this import if possible import 'package:flutter_tts/flutter_tts_web.dart';


This has no effect, and I have not used flutter_tts_web.dart. TTS_SERVICE has been done in the plugin.

**Comment by Rob-wang** [comment]
It is my own problem, and there is a problem with my certificate. It has now been resolved.😅

**Comment by dlutton** [comment]
this is fixed in the latest version
