### ISSUE TITLE
Some mobile phones do not support Chinese

### ISSUE THREAD

**Issue by WyyNever** [dlutton/flutter_tts#28]
### Configuration

**Version:** 0.1.x

**Platform:** 
- [ ] :robot: Android  （API 22）

**Comment by dlutton** [comment]
@WyyNever can you please provide some of the devices Chinese isn't supported for and also provide the TTS engine that's being used on those devices?

**Comment by WyyNever** [comment]
The TTS engine of these phones does not support Chinese. I plan to access some other SDKS to play Chinese voice.Thank you for your help

**Comment by dlutton** [comment]
okay because I'm using the google TTS engine by default which may or may not support Chinese.
`com.google.android.tts`.
