### ISSUE TITLE
Can not speak in android

### ISSUE THREAD

**Issue by lutakrystal305** [dlutton/flutter_tts#281]
![image](https://user-images.githubusercontent.com/65547732/138592770-43be84d5-222e-4545-8b1d-a47cebdbfe14.png)
Why dont speak in andoird (emulator/real device), but in web, they still work fine.

**Comment by mimiaopp** [comment]
我也遇到相同的问题

**Comment by dlutton** [comment]
@mimiaopp do you have details of the error you're receiving and the device and flutter version you're using?  Also, are you able to translate your text to english for me when posting a comment?  Thank you!

**Comment by lgGuo** [comment]
no suound for me too,android version is 7.1, flutter version id 2.5.1.

**Comment by dlutton** [comment]
@lgGuo is this on a real device, emulator, or both?

**Comment by dlutton** [comment]
@lgGuo, also are you adding `TextToSpeech.Engine.INTENT_ACTION_TTS_SERVICE` to your manifest?

**Comment by josephmaklc** [comment]
Try a reset of TTS on the phone to fix it. Settings->General Management->Language and Input ->Text to Speech. My phone has a Reset button there and then it starts to talk again
