### ISSUE TITLE
App crashes at web android

### ISSUE THREAD

**Issue by otopba** [dlutton/flutter_tts#283]
## 🐛 Bug Report

App crashes on start at web android

This feature is not supported at WebView Android https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance#browser_compatibility. App crashes when dart try to access `html.SpeechSynthesisUtterance`. Maybe we should add an operating system check or at least try-catch?

<img width="297" alt="Screenshot 2021-11-03 at 15 38 05" src="https://user-images.githubusercontent.com/4225279/140304631-e70724aa-f4cf-4750-a7ba-82e039358610.png">

### Expected behavior

App not crashes

### Reproduction steps

Add library to your project and run at WebView Android

### Configuration

**Version:** 3.2.2

**Platform:** 
- [X] :robot: Android

**Comment by dlutton** [comment]
good idea @otopba, I'll see if there is a way to put that around a try/catch

**Comment by rohitsangwan01** [comment]
@otopba  @dlutton i was also into the similar situation , so created a package for this
https://pub.dev/packages/web_view_tts
hope this will be helpful for someone

**Comment by otopba** [comment]
> @otopba @dlutton i was also into the similar situation , so created a package for this https://pub.dev/packages/web_view_tts hope this will be helpful for someone

Cool! Thanks
