### ISSUE TITLE
Android 11 不能运行

### ISSUE THREAD

**Issue by mimiaopp** [dlutton/flutter_tts#285]
![Uploading image.png…]()

**Comment by mimiaopp** [comment]
![image](https://user-images.githubusercontent.com/37366343/140880180-2f44c0e5-ae35-4066-9f3f-72e92285ec8a.png)

**Comment by mimiaopp** [comment]
![image](https://user-images.githubusercontent.com/37366343/140880260-2e637fab-79cc-45df-badd-6c87520d9064.png)

**Comment by dlutton** [comment]
@mimiaopp I apologize, but what issue are you running into here?

**Comment by dlutton** [comment]
@mimiaopp I'm closing this issue, let me know if you're able to add any information as to your error since your original post included a picture that isn't rendering correctly.
