### ISSUE TITLE
How are the mixWithOthers and duckOthers options supposed to work?

### ISSUE THREAD

**Issue by mvrsn** [dlutton/flutter_tts#286]
## 💬 Questions and Help
I'm having no luck in understanding how the `IosTextToSpeechAudioCategoryOptions.mixWithOthers` and  `IosTextToSpeechAudioCategoryOptions.duckOthers` are supposed to work

My assumption is that if I am playing music in another app for example, mixing will leave the music playing, and ducking will lower the volume while the text is spoken, but neither of these options seem to prevent the music from stopping

### Expected behavior
I would expect `IosTextToSpeechAudioCategoryOptions.mixWithOthers` to keep the music playing in the background, and `IosTextToSpeechAudioCategoryOptions.duckOthers` to lower the music volume until TTS has finished, or at the very least that the music is resumed after TTS has finished with either of these two options, but maybe I'm misunderstanding how this is supposed to work

### Configuration
```
await tts.setIosAudioCategory(
  IosTextToSpeechAudioCategory.playback,
  [
    IosTextToSpeechAudioCategoryOptions.allowBluetooth,
    IosTextToSpeechAudioCategoryOptions.allowAirPlay,
    IosTextToSpeechAudioCategoryOptions.allowBluetoothA2DP,
    IosTextToSpeechAudioCategoryOptions.mixWithOthers,
  ],
);

await tts.setSharedInstance(true);
await tts.setVolume(1);
await tts.awaitSpeakCompletion(true);
await tts.setSpeechRate(0.4);```
**Version:** 3.2.2

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by dlutton** [comment]
@mvrsn these are all iOS specific options which can be found through their documentation:

mixWithOthers = https://developer.apple.com/documentation/avfaudio/avaudiosession/categoryoptions/1616611-mixwithothers

`If you set this option, your app mixes its audio with audio playing in background apps, such as the Music app.`

duckOthers = https://developer.apple.com/documentation/avfaudio/avaudiosession/categoryoptions/1616618-duckothers

`You can set this option only if the audio session category is playAndRecord, playback, or multiRoute. Setting it implicitly sets the mixWithOthers option.`

`Use this option to mix your app’s audio with that of others. While your app plays its audio, the system reduces the volume of other audio sessions to make yours more prominent. If your app provides occasional spoken audio, such as in a turn-by-turn navigation app or an exercise app, you should also set the interruptSpokenAudioAndMixWithOthers option.`

These should work exactly as it mentions in their docs.  If they aren't, please open a bug ticket for further research.

**Comment by mvrsn** [comment]
@dlutton I tested a bunch more with different settings and made sure that I'm running the latest version of the plugin, pod and ios and music definitely stops for me when I call the `speak()` method, will open a bug ticket
