### ISSUE TITLE
'duckOthers' and 'mixWithOthers' settings not working as expected

### ISSUE THREAD

**Issue by mvrsn** [dlutton/flutter_tts#287]
## 🐛 Bug Report
When trying to speak text while playing music in a different app the music stops immedeately when I call the `speak()` method

I'm not sure if this is related, but I noticed that when I called `setSharedInstance(true)` the music in the background would also stop, but this might be expected behaviour

When putting breakpoints inside the `SwiftFlutterTtsPlugin` the music stopped playing when `self.synthesizer.speak(utterance)` was called

### Expected behavior
Music volume should be lowered while text is spoken and then go back to normal volume

### Reproduction steps
- Play music in background app
- Run the following code
```
var tts = FlutterTts();

await tts.setVolume(1);
await tts.awaitSpeakCompletion(true);
await tts.setSpeechRate(0.4);

await tts.setIosAudioCategory(
  IosTextToSpeechAudioCategory.playback,
  [
    IosTextToSpeechAudioCategoryOptions.allowBluetooth,
    IosTextToSpeechAudioCategoryOptions.allowAirPlay,
    IosTextToSpeechAudioCategoryOptions.allowBluetoothA2DP,
    IosTextToSpeechAudioCategoryOptions.duckOthers,
  ],
);

await tts.stop();
await tts.setLanguage('en');
await tts.speak('Hello');
```

### Configuration

**Version:** 3.2.2

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by Zeswen** [comment]
Can replicate. Users are experiencing audio stopping in iOS if an audio plays (using [`audioplayers`](https://github.com/bluefireteam/audioplayers)) at the same time. I assume it's related to this.

**Comment by dlutton** [comment]
@Zeswen @mvrsn this should be working with the latest release using the Mode option (see the Readme).

**Comment by mvrsn** [comment]
Awesome! Thank you @mitghi @dlutton
