### ISSUE TITLE
 speak failed: not bound to TTS engine

### ISSUE THREAD

**Issue by maheshkumar2150** [dlutton/flutter_tts#29]
FlutterTts flutterTts = FlutterTts();
//List<dynamic> languages = await flutterTts.getLanguages;
//print(languages);
    await flutterTts.setLanguage("en-US");
    await flutterTts.setSpeechRate(1.0);
    await flutterTts.setVolume(1.0);
    await flutterTts.setPitch(1.0);
    //await _stop();
    _speak("Hello World");

Future _speak(String text) async {
    var result = await flutterTts.speak(text);
  }

//List<dynamic> languages = await flutterTts.getLanguages;
//print(languages);

Hot Reload :
getAvailableLanguages failed: not bound to TTS engine
E/MethodChannel#flutter_tts( 3179): Failed to handle method call

W/TextToSpeech( 3179): isLanguageAvailable failed: not bound to TTS engine
W/TextToSpeech( 3179): speak failed: not bound to TTS engine

EDIT.

For the first time it works without giving any voice. After hot-reload, the above errors are thorwn

First Time : 

I/flutter ( 3554): [de, es-ES, es, fr, en, it-IT, it, fr-FR, en-US, de-DE, en-GB]
I/1.gpu   ( 3554): type=1400 audit(0.0:1627): avc: denied { open } for path="/data/data/com.example.my_app/cache/flutter_engine/....AEQABQAAAAAAAA6IAAAADAAAEAAAAAAAAAAAAAAACAAAAAQAALMAA" dev="sdb3" ino=106021 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:system_data_file:s0:c512,c768 tclass=file permissive=1
I/TextToSpeech( 3554): Asked to disconnect from ComponentInfo{com.svox.pico/com.svox.pico.PicoService}
I/TextToSpeech( 3554): Connected to ComponentInfo{com.svox.pico/com.svox.pico.PicoService}
I/TextToSpeech( 3554): Set up connection to ComponentInfo{com.svox.pico/com.svox.pico.PicoService}

**Comment by dlutton** [comment]
@maheshkumar2150 I'm assuming this is occurring on Android.  Try running your async awaits for flutterTts in the ttsInitHandler like below.  I also have it written within the example. 

```
flutterTts.ttsInitHandler(() {
  await flutterTts.setLanguage("en-US");
  await flutterTts.setSpeechRate(1.0);
  await flutterTts.setVolume(1.0);
  await flutterTts.setPitch(1.0);
}); 
```

**Comment by maheshkumar2150** [comment]
`class MyFlutterTts {
MyFlutterTts () {
init()
}

init() {
print('initiating flutter tts');
    _flutterTts = FlutterTts();

    if (Platform.isAndroid) {
      print('isAndroid');
      _flutterTts.ttsInitHandler(() async {
        print('initHandler');
        await _flutterTts.setLanguage("en-US");
        await _flutterTts.setSpeechRate(1.0);
        await _flutterTts.setVolume(1.0);
        await _flutterTts.setPitch(1.0);
      });
    }
    if (Platform.isIOS) {
      await _flutterTts.setLanguage("en-US");
      await _flutterTts.setSpeechRate(1.0);
      await _flutterTts.setVolume(1.0);
      await _flutterTts.setPitch(1.0);
    }
}

playVoice(String text) async {
    print('executing Voice');
      try {
        print('trying....');
        if (_isPlaying) await _stop();
        await _speak(text);
      } catch (e) { print('(playVoice) : '); print(e);}
  }

_speak(String text) async {
    try {
      var result = await _flutterTts.speak(text);
      if (result == 1) {
        _isPlaying = true;
      }
    } catch (e) { print('(_speak) : '); print(e); }
  }

}`

print('initHandler'); is not printed.. Line is not executed there.


I called MyFlutterTts  _myFlutterTts = MyFlutterTts(); inside a statelesswidget
_myFlutterTts.playVoice('Hello');

I/flutter ( 7909): initiating flutter tts
I/flutter ( 7909): isAndroid
I/flutter ( 7909): executing Voice
I/flutter ( 7909): trying....
W/TextToSpeech( 7909): speak failed: not bound to TTS engine

Do i have to use it in a statefulwidget?
_isPlaying = true; is it right to store the status in this way?

**Comment by dlutton** [comment]
@maheshkumar2150  Yes you can set those variables any way you'd like.  I'm using enums in my example, but setting _isPlaying = true will also work.  Is there a reason you're setting your init to async?  the initHandler should be called and executed when the platform channel responds back that the engine has been bound.  Also by default it's using com.google.android.tts as the TTS engine.  On your device make sure you're using that.  I haven't added the ability to set your engine yet.

**Comment by dlutton** [comment]
@maheshkumar2150 is this still an issue?

**Comment by vishweshsoni** [comment]
Asked to disconnect from ComponentInfo{com.google.android.tts/com.google.android.tts.service.GoogleTTSService} same issue
