### ISSUE TITLE
I can't synthesize my TTS file on iOS

### ISSUE THREAD

**Issue by lawzyresources** [dlutton/flutter_tts#290]
I'm trying to synthesize my file on my iOS device and keep receiving this error.

Devices I'm using are:
Iphone 12(personal device)-- Version 14.8.1
Iphone 11 (Simulator) --Version 14.4

 Saving utterance to file: file:///var/mobile/Containers/Data/Application/01C8B139-C5A4-4176-BAC4-6B4FEFD00769/Documents/scannedtext.caf
[ +105 ms] <AVAudioFormat 0x2802e0ff0:  1 ch,  22050 Hz, Int16>

[ +858 ms] **flutter_tts/SwiftFlutterTtsPlugin.swift:364: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value**

[        ] flutter_tts/SwiftFlutterTtsPlugin.swift:364: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
[ +493 ms] Process 38314 stopped
[        ] * thread #1, queue = 'com.apple.main-thread', stop reason = Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
[        ]     frame #0: 0x0000000192e03eac libswiftCore.dylib`_swift_runtime_on_report
[        ] libswiftCore.dylib`_swift_runtime_on_report:
[        ] ->  0x192e03eac <+0>: ret    
[        ] libswiftCore.dylib`_swift_reportToDebugger:
[        ]     0x192e03eb0 <+0>: b      0x192e03eac               ; _swift_runtime_on_report
[        ] libswiftCore.dylib`_swift_shouldReportFatalErrorsToDebugger:
[        ]     0x192e03eb4 <+0>: adrp   x8, 337455
[        ]     0x192e03eb8 <+4>: ldrb   w0, [x8, #0x2a9]
[        ] Target 0: (Runner) stopped.
[        ] ios-deploy exited with code 0
[ +151 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +1 ms] DevFS: Deleting filesystem on the device (file:///private/var/mobile/Containers/Data/Application/01C8B139-C5A4-4176-BAC4-6B4FEFD00769/tmp/A/)
[ +256 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: **Future not completed**
[  +11 ms] "flutter run" took 139,511ms.

Flutter doctor output

[✓] Flutter (Channel stable, 2.5.0, on Mac OS X 10.15.7 19H1323 darwin-x64, locale en-US)
    • Flutter version 2.5.0 at /Users/leedagr8/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (3 months ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/leedagr8/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.59.0)
    • VS Code at /Users/leedagr8/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (4 available)
    • SM G965U (mobile)  • 3444503233423098                     • android-arm64  • Android 10 (API 29)
    • iPhone (mobile)    • 00008101-001E49D10289001E            • ios            • iOS 14.8.1 18H107
    • iPhone 11 (mobile) • D5E2ED8B-C804-47B2-9AE8-1C6485EF2E47 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 96.0.4664.110

**Comment by lawzyresources** [comment]
@dlutton Thank you for taking this bug on. Any update on what can be the error? I'm not familiar with Swift so I wasn't sure how to debug it.

**Comment by mitghi** [comment]
@lawzyresources I have tested this further, and i suspect that you might be calling _.awaitSpeakCompletion(true)_ somewhere before calling _.synthesizeToFile(...)_, which causes the crash. 

The following code causes a **crash**:
```dart
await flutterTts.awaitSpeakCompletion(true);    
flutterTts.synthesizeToFile("Hello World", "tts.caf");
```

But this one does not:
```dart
flutterTts.synthesizeToFile("Hello World", "tts.caf");
```

**Comment by dlutton** [comment]
@lawzyresources do you have a snippet of the code you're running that's causing the crash?

**Comment by dlutton** [comment]
@lawzyresources @mitghi the latest 3.3.3 version should fix this issue.   It's a temporary solution since I need to rework synthesizeToFile anyways to allow someone to pass in an already created directory/file.

**Comment by lawzyresources** [comment]
@mitghi  @dlutton Yes I would call the  await the speak completion to be true. here's a screen shot. I'll pull down the latest version and test it. thank you guys 
![image](https://user-images.githubusercontent.com/77633349/147392988-6b306f1c-8592-4658-919b-c384628647e1.png)

**Comment by lawzyresources** [comment]
I just realized the code above was the latest code I was using but not the one that was crashing. 
This is the code that failed for me before - - Also Merry Christmas
![image](https://user-images.githubusercontent.com/77633349/147393030-f3d1700e-0352-486a-9a8c-1f22954b0339.png)

**Comment by lawzyresources** [comment]
3.3.3 fixed it!! Thank you so much- have an amazing holiday! @dlutton
