### ISSUE TITLE
when build or run apk give me this error 

### ISSUE THREAD

**Issue by Moatamed8** [dlutton/flutter_tts#292]
## 💬 Questions and Help

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\So\Desktop\Flutter Project\app\example\android\App\example\build\flutter_tts\intermediates\library_manifest\debug\AndroidManifest.xml:9:5-13:15: AAPT: error: unexpected element <queries> found in <manifest>.

**Comment by dlutton** [comment]
@Moatamed8 I tried `flutter build apk` and that worked successfully.  what is your classpath in your android/build.gradle file?  You may need to upgrade your gradle version.

**Comment by Moatamed8** [comment]
here's my classpath 
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath 'com.google.gms:google-services:4.3.10'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }

**Comment by Moatamed8** [comment]
i solved it by set    classpath 'com.android.tools.build:gradle:3.5.4'
