### ISSUE TITLE
Support For Beep

### ISSUE THREAD

**Issue by rohitsangwan01** [dlutton/flutter_tts#293]
## 🚀 Feature Requests

Sir can you please add support for Beep sound , or is there any workaround to get a beep sound by this package

Because my app includes TTS as well as Beeps , so it will be really easy to handle all this by one package , instead of adding two

**Comment by dlutton** [comment]
@rohitsangwan01 is Beeps a flutter package?

**Comment by rohitsangwan01** [comment]
@dlutton , yes there is alread a package for that , "Flutter Beeep"

**Comment by dlutton** [comment]
@rohitsangwan01 that package looks like it's intended to play system sounds, which is out of the scope of TTS.  If any of the TTS docs for android (https://developer.android.com/reference/android/speech/tts/TextToSpeech) or ios mention beep as an option, then I will integrate it.
