### ISSUE TITLE
Urdu text to speech in Ios and hebrew text to speech in android not available

### ISSUE THREAD

**Issue by joshua750** [dlutton/flutter_tts#296]
### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by joshua750** [comment]
Urdu text to speech is not available for iphone and hebrew text to speech is android is not available

**Comment by dlutton** [comment]
@joshua750 this package uses the native TTS service on each device, so the languages that are available are out of my hand.
