### ISSUE TITLE
.stop() doesn't work on iOS 15 and above

### ISSUE THREAD

**Issue by OBESTMAN** [dlutton/flutter_tts#298]
OS Version: 15
flutter_tts package version 3.3.3

Platform:
 📱 iOS

**Comment by dlutton** [comment]
Looks like it's being reported as a bug:
https://stackoverflow.com/questions/70537016/ios-15-2-bug-on-didfinish-utterance-callback

**Comment by OBESTMAN** [comment]
That’s interesting.. well, I spent today hacking away some sort of a solution for about 6 hours lol... I used Boolean flags to set conditions for when the stop is clicked as a way to pause the synthesis and also for when it means to end the synthesis. 
Do you plan on looking into a solution for it ? 



Sent from Yahoo Mail for iPhone


On Friday, December 31, 2021, 7:10 pm, Daniel Lutton ***@***.***> wrote:




Looks like it's being reported as a bug:
https://stackoverflow.com/questions/70537016/ios-15-2-bug-on-didfinish-utterance-callback

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dlutton** [comment]
@OBESTMAN it's a bug with Apple, so we'll have to wait and see if they come up with a solution or work around until it's fixed.

**Comment by OBESTMAN** [comment]
Ok, we have no other choice but to wait. 
By the way, how can I keep the flutter_tts playing when someone closes the app but still keeps it in the background? 



Sent from Yahoo Mail for iPhone


On Friday, December 31, 2021, 8:11 pm, Daniel Lutton ***@***.***> wrote:




@OBESTMAN it's a bug with Apple, so we'll have to wait and see if they come up with a solution or work around until it's fixed.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by vtisnado** [comment]
If you have a function that loops for large text, you should check with a boolean value if the text is playing inside the **tts.setCompletionHandler**. 
Here is an example with the function I'm using:

```
int speakLoop = 0;
if(texts.length > 0) {
tts.speak(texts[speakLoop]);
tts.setCompletionHandler(() {
	speakLoop++;
	if (speakLoop <texts.length ) {
		if (_isPlaying.value == true ){
			tts.speak(texts[speakLoop]);
		}
	} else {

	}
});
}
```
