### ISSUE TITLE
a few questions on votes

### ISSUE THREAD

**Issue by FetFrumos** [dlutton/flutter_tts#299]
thanks for the great package. I have a few questions.
1.How to get a list of voices with their names?
I use this method getVoices, this is the result:

![image](https://user-images.githubusercontent.com/18227037/147856780-c6e1f03d-3c05-4507-9070-600e261576de.png)

 But I was expecting to see the name of the voice in the form of the name "Karen"(as example). maybe there is another method?

2. How do I know the current voice? is there a method for this?

**Comment by dlutton** [comment]
@FetFrumos those are the name and locales coming from the native TTS engine on the device.  I'm assuming your output is from Android as it will differ from iOS.

**Comment by FetFrumos** [comment]
thanks, how do I know which voice is used by default?

**Comment by dlutton** [comment]
@FetFrumos for Android, there is a default that's set already depending on the locale/language being used.  Android does have a getDefaultVoice - https://developer.android.com/reference/android/speech/tts/TextToSpeech#getDefaultVoice() which I can add to this package if you'd like, I'm not sure if iOS has something similar.

**Comment by FetFrumos** [comment]
yes, add it please

**Comment by daiweiqiang6688** [comment]
I'm having the same problem, I need to get the default Voice, any progress now?

**Comment by dlutton** [comment]
@daiweiqiang6688 do you need this on Android, iOS, or both?  I haven't seen anything similar on iOS, but I can quickly implement it for Android if you only need it there.

**Comment by daiweiqiang6688** [comment]
@dlutton
Thank you for your reply.
I think both platforms are needed if possible.
I'm writing an application that allows the user to modify parameters such as voice, speech rate, etc.
So it needs to show the current default voice used, and when modified, it can be restored to the default voice by clicking the "restore default" button.
So it is necessary to get the default voice, or is there any other solution?

**Comment by FetFrumos** [comment]
Hi @dlutton, is this method added in plugin(for android)?

**Comment by dlutton** [comment]
sorry for the delay @FetFrumos, but I have just added the feature.  I could only find this feature on Android though so it's not supported on iOS right now.  This has been added to 3.5.3.
