### ISSUE TITLE
Is there a way to know when the tts package is finished speaking?

### ISSUE THREAD

**Issue by CodyBontecou** [dlutton/flutter_tts#300]
Is there an event that I can listen to that allows me to run code after my app is finished speaking?

**Comment by dlutton** [comment]
@CodyBontecou you can use `await flutterTts.awaitSpeakCompletion(true);` and then simply await your speak method.  After your speak method is complete, then you know it's done.  Another way is to use the callback 
```
flutterTts.setCompletionHandler(() {
  setState(() {
    ttsState = TtsState.stopped;
  });
});
```

**Comment by CodyBontecou** [comment]
Perfect, thank you!
