### ISSUE TITLE
There is no option for native Indian languages like Tamil, Oriya, Kannad etc. If the developers can get support for this, this will be best package for text to speech in flutter

### ISSUE THREAD

**Issue by nouveau-riche** [dlutton/flutter_tts#307]
### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by dlutton** [comment]
@nouveau-riche unfortunately this package doesn't control the languages that are available.  This package uses the native TTS engines on each device, so it depends on the device/engine.

**Comment by vikeshvee** [comment]
i facing the same issue no support for Indian languages IOS.
now checking for Cloud TTS for Indian languages
