### ISSUE TITLE
Problem when having to pronounce a word with a "-" in it. Only the first part of the word is pronounced.

### ISSUE THREAD

**Issue by sylvainjack** [dlutton/flutter_tts#309]
## 🐛 Bug Report

When a word contains a "-", only the first word is pronounced. The word "beau-frère" in French : only "beau" is pronounced. 

### Configuration

**Version:** 0.1.x

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by dlutton** [comment]
@sylvainjack by device I meant android vs iOS.  This package uses the native TTS engine on your device.

**Comment by sylvainjack** [comment]
So does it mean that IOS native TTS can't pronounce words with a "-" in them ?

**Comment by JogyBlack** [comment]
@sylvainjack Have you tried to use SSML to add more control on how the text is pronounced?

It helped me for a related issue on Android - see Issue #306

**Comment by sylvainjack** [comment]
No I haven't really looked into SSML. But I am just really surprised that the TTS engine on an iPhone can't pronounce a word containing a hyphen.... Why so ?

**Comment by dlutton** [comment]
@sylvainjack is this only occurring on a real device and not an emulator (When doing a google search for AVSpeechSynthesizer and hyphens I see that someone else ran into a similar issue)?  Have you also tried using another language and other hyphenated words?  when I get a moment I'll try a few words with hyphens.

**Comment by sylvainjack** [comment]
I only use a real device. Never used an emulator. I use an iPhone XSmax. I just tried English words and the words with hyphens were pronounced... Apparently, pb with French ?

**Comment by dlutton** [comment]
@sylvainjack it could be a problem with the French language setting as you mentioned.  I'll have to do some digging around to see if there is a reason for this.

**Comment by sylvainjack** [comment]
I added a string.replaceAll('-',' ') and I no longer have problems :) I guess this could be a solution.

**Comment by dlutton** [comment]
@sylvainjack I'm glad that solution works for you, this is definitely a native iOS TTS issue, so I'll mark this as closed on my end.
