### ISSUE TITLE
IOS build fails due to undefined swift version.

### ISSUE THREAD

**Issue by bradx954** [dlutton/flutter_tts#31]
## 🐛 Bug Report

    - `flutter_tts` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

flutter: 1.2.1
flutter_tts: 0.2.4

**Comment by bradx954** [comment]
Got it working. Combination of what this guy did:
https://github.com/flutter/flutter/issues/16049#issuecomment-382664356

And adding these lines to my pod file:
use_frameworks!
config.build_settings['SWIFT_VERSION'] = '4.0'
Here is where you put them.
`target 'Runner' do
  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
	# referring to absolute paths on developers' machines.
	use_frameworks! # <--- add this
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')

  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
`

**Comment by TheAlphamerc** [comment]
Still got below error after following these steps
` [!] Unable to determine Swift version for the following pods:
    - `flutter_tts` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.`

> Got it working. Combination of what this guy did:
> [flutter/flutter#16049 (comment)](https://github.com/flutter/flutter/issues/16049#issuecomment-382664356)
> 
> And adding these lines to my pod file:
> use_frameworks!
> config.build_settings['SWIFT_VERSION'] = '4.0'
> Here is where you put them.
> [example.txt](https://github.com/dlutton/flutter_tts/files/3089986/example.txt)
