### ISSUE TITLE
Set language does not change the language

### ISSUE THREAD

**Issue by EALeeItsInTheC0de** [dlutton/flutter_tts#319]
## 🐛 Bug Report

When setting the language to another language the text is still read in English but the voice accent changes to the language

### Expected behaviour

The text should be read out in the selected language, as long as it is installed and available

### Reproduction steps

```dart

await flutterTts.setLanguage('de-DE');
await flutterTts.speak("Hello");

```

### Configuration

**Version:** 3.3.3

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by bodoczky** [comment]
Same on Android :\

**Comment by dlutton** [comment]
@EALeeItsInTheC0de the text needs to be in the language that is read.

**Comment by EALeeItsInTheC0de** [comment]
ok but if I change my phone language to german and then run the speak function it plays it in german, even if the text is in English. Is this not the same as setting the language in the package ?

**Comment by dlutton** [comment]
@EALeeItsInTheC0de unfortunately it's not the same in this case.  If you translate the text into the language you want it spoken in and also set the language accordingly, then it should work for you.  Otherwise you'll just have the accent like you're experiencing.
