### ISSUE TITLE
Cannot run for iOS with Flutter (Objective C)

### ISSUE THREAD

**Issue by piyush97** [dlutton/flutter_tts#32]
## 🐛 Bug Report

**Version:** 0.1.x

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by dlutton** [comment]
Hey @piyush97, this plugin was created with swift.  When you created your flutter project, did you use the `-i swift` option?

**Comment by piyush97** [comment]
Got it.
Thanks!
