### ISSUE TITLE
Example can not run in Windows

### ISSUE THREAD

**Issue by iibinix** [dlutton/flutter_tts#321]
## 🐛 Bug Report
Example can not run in Windows ,It shows

`Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Launching lib\main.dart on Windows in debug mode...
lib\main.dart:1
D:\Users\istrator\Desktop\flutter_tts-3.4.0\example\windows\flutter\ephemeral\.plugin_symlinks\flutter_tts\windows\flutter_tts_plugin.cpp(217,10): fatal error C1083: �޷��򿪰����ļ�: ��atlstr.h��: No such file or directory [D:\Users\istrator\Desktop\flutter_tts-3.4.0\example\build\windows\plugins\flutter_tts\flutter_tts_plugin.vcxproj]
Exception: Build process failed.
Exited (sigterm)`

**Version:** 3.4.0

**Platform:** 
- [x] :windows 10

**Comment by dlutton** [comment]
any ideas @vagoston?  Sorry I haven't looked into the windows implementation yet, hopefully I'll have some time soon.

**Comment by vagoston** [comment]
@iibinix  I'm sorry that it doesn't work for you. I checked again and it still works for me, and I know that at least one other person managed to make it work out of the box. Most likely your devenv is not usiing the latest versions.
Make sure that you followed the 'Additional Windows requirements' on https://docs.flutter.dev/get-started/install/windows. Please make sure that your build tools is v142 (latest) and that 'C++ ATL for latest v142 build tools ...' is installed. 
If you still have difficulties, please provide some more details of your environment.

**Comment by julianryorex** [comment]
Hi, I am also getting a very similar issue, but it's in CI. It runs well locally. I'm wondering what additional assets I'll need to download to the image for it to work properly. I originally thought it was a `nuget.exe` [issue](https://stackoverflow.com/questions/71734042/flutter-windows-build-nuget-is-not-installed) (I ran into this problem locally), but it seems like this is already installed in the Windows image on Gitlab.

Environment: 
- Flutter TTS v3.6.0
- Windows 11 (22000.1098)
- Flutter 3.3.7
- Dart SDK version: 2.18.4 (stable)

```
$ Building with sound null safety 
$ Building Windows application...                                 
$ C:\GitLab-Runner\builds\client-app\windows\flutter\ephemeral\.plugin_symlinks\flutter_tts\windows\flutter_tts_plugin.cpp(224,10): fatal error C1083: Cannot open include file: 'atlstr.h': No such file or directory [C:\GitLab-Runner\builds\client-app\build\windows\plugins\flutter_tts\flutter_tts_plugin.vcxproj]
$ Build process failed.
```
