### ISSUE TITLE
Getting fatal error when trying to debug your example code on android mobile

### ISSUE THREAD

**Issue by CleopasMwape** [dlutton/flutter_tts#329]
## 🐛 Bug Report
Getiing this long error log that starts like below:
Invalid depfile: C:\Users\ENE\Documents\example\.dart_tool\flutter_build\211b4f6761bfd841fe4d9a18786a4cd6\kernel_snapshot.d
/C:/SDKs/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_tts-3.5.0/lib/flutter_tts_web.dart:3:8: Error: Not found: 'dart:js'
import 'dart:js' as js;

Note:  The error seems to be caused by flutter_tts_web which is being required to be imported for TtsState management

**Platform:** 
- [ ] :robot: Android

**Comment by dlutton** [comment]
@CleopasMwape try `flutter clean`

**Comment by mateoKutnjak** [comment]
Do a project search for `flutter_tts_web` and remove import it if you don't need it.
