### ISSUE TITLE
Please install this executable, and run CMake again

### ISSUE THREAD

**Issue by shirne** [dlutton/flutter_tts#337]
## 🐛 Bug Report

```
NUGET.EXE not found.
CMake Error at flutter/ephemeral/.plugin_symlinks/flutter_tts/windows/CMakeLists.txt:9 (message):
  Please install this executable, and run CMake again.
```

### Reproduction steps
flutter run
select windows platform

### Configuration
```
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [版本 10.0.19044.1826], locale zh-CN)
Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
[√] Android Studio (version 2021.2)
[√] Connected device (3 available)
[√] HTTP Host Availability
```

**Version:** 3.5.0

**Platform:** 
- [x] :windows
- [ ] :robot: Android

In my other project,when I run on windows, `NUGET.EXE not found.` also shown ,but it will automatic download and cache. 
It shows:
```
Nuget.exe not found, trying to download or use cached version.
```
and run OK.

so i think it's unnecessary to abort when not found NUGET.EXE

I found the cache download cmake code from permission_handler_windows, and modified cmakelist.txt
```
include(FetchContent)

 // ...

FetchContent_Declare(nuget
  URL "https://dist.nuget.org/win-x86-commandline/v6.0.0/nuget.exe"
  URL_HASH SHA256=04eb6c4fe4213907e2773e1be1bbbd730e9a655a3c9c58387ce8d4a714a5b9e1
  DOWNLOAD_NO_EXTRACT true
)

find_program(NUGET_EXE nuget)
if (NOT NUGET_EXE)
    message("Nuget.exe not found, trying to download or use cached version.")
    FetchContent_MakeAvailable(nuget)
    set(NUGET_EXE ${nuget_SOURCE_DIR}/nuget.exe)
endif()
```
and then it work ok

**Comment by vagoston** [comment]
@shirne could you link in that other project? I still don't think that the codebase should be responsible for setting up the environment, but I would like to take a look. If this is a common practice, I don't mind to follow that. 
I would like to point out that this is a template code, generated by Flutter.

**Comment by shirne** [comment]
https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler_windows/windows/CMakeLists.txt#L11

**Comment by sumersm7** [comment]
how i solved this error
STEP 1 :- i downloaded the [NUGET ](https://www.nuget.org/downloads)
STEP 2 :- add file path to env variable in windows 
STEP 3 :- install C++ ATL for latest v142 build tools (image included)
![image](https://user-images.githubusercontent.com/82924076/185743324-bfde428e-a091-4d67-8c04-fb49f9fd133b.png)


STEP 4 :- flutter clean , flutter pub get 

STEP 6 :- close and open new terminal and run NUGET to check if env path is correct

STEP 7 :- run for windows

**Comment by tranhuudang** [comment]
For someone who doesn't find any solution working, you can try to copy these two folders in /windows  in a working project, then paste them to your project. I myself try a lot of different approaches, and this is one of them, and it works. I don't know why but it might help. 
![Screenshot 2023-05-08 094401](https://user-images.githubusercontent.com/96557038/236722468-706dcec4-0a8f-4404-862c-71ef81b85c6a.png)
