### ISSUE TITLE
Silence before speak needed

### ISSUE THREAD

**Issue by mikes222** [dlutton/flutter_tts#34]
## 🚀 Feature Requests

I need to play a silence before starting to speak. 

### Contextualize the feature
When using Bluetooth headsets with batteries the Headsets normally switches off the audio when there is no signal from the device for a while in order to save battery. When flutter_tts starts to speak some headsets needs 500-1500ms to restart and play the audio file. Without a trailing signal the user will not hear the first second of the audio. 

When playing the silence the Headset will detect the (silent) signal and starts up.

### Describe the feature
So I ask to add a feature to define a silence period in milliseconds before starting the speech. 

Optional: For advanced functionality another parameter could be added to define that the silence period will be omitted if the last speech is not older than x seconds. (assuming that the headset is still active)

In android I had the following code snippet:

    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            if (silenceMs > 0)
                tts.playSilentUtterance(silenceMs, TextToSpeech.QUEUE_ADD, utteranceId);
            tts.speak(speak, TextToSpeech.QUEUE_ADD, null, utteranceId);
    } else {
            if (silenceMs > 0)
                tts.playSilence(silenceMs, TextToSpeech.QUEUE_ADD, null);
            tts.speak(speak, TextToSpeech.QUEUE_ADD, null);
    }

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by dlutton** [comment]
this has been merged
