### ISSUE TITLE
flutter_tts just stopped working on Xcode 14 iOS 16

### ISSUE THREAD

**Issue by officialFlutterDeveloper** [dlutton/flutter_tts#342]
## 🐛 Bug Report

I have been developing an app for last 1 month  I would use flutterTts.getVoices to get list of voices but ever since I upgraded to Xcode 14 IOS 16 simulator the .getVoices or any flutterTts function does not return anything no errors are being caught either 

flutter_tts: 3.5.3

**Platform:** 
- [ ✔] :iphone: iOS
- [ ] :robot: Android

**Comment by dlutton** [comment]
@officialFlutterDeveloper You need to download languages for it to work inside of simulators. For IOS 16 simulator, go settings -> Spoken content -> Voices -> Select any language and download.
