### ISSUE TITLE
setPitch doesn't work

### ISSUE THREAD

**Issue by Jounnoo** [dlutton/flutter_tts#347]
Hi,

I'm working on an Android app and I need to change the pitch voice. But setPitch does not work on galaxy S9+ (Android 10) and S21+ (Android 21).
I have no problem with the volume, the speed, ... Only with the pitch voice.

Thanks,
Clement

**Comment by luckyhandler** [comment]
The same happens on a OnePlus5. So I guess it might not be a device specific problem

```
if (Platform.isAndroid) {
    await tts.setPitch(2);
}
```

has no effect

**Comment by dlutton** [comment]
@luckyhandler can you confirm if this still an issue with the latest version?

**Comment by Jounnoo** [comment]
Hi @dlutton,

I tested this morning with the latest version (3.6.0) and I confirm that the problem is still present

**Comment by dlutton** [comment]
@Jounnoo I updated my android phone and setPitch is no longer working.  This issue has been mentioned outside of this package, so this appears to be an issue with the Android API and certain Android versions.

**Comment by Jounnoo** [comment]
Ok thank you for your feedback
