### ISSUE TITLE
Caught a RuntimeException from the binder stub implementation.

### ISSUE THREAD

**Issue by panthe** [dlutton/flutter_tts#35]
I've follow the example and I've inserted flutter_tts in a view of my app.
When I'm playng I see this error from the last update of flutter engine:

`W/Binder  (26640): Caught a RuntimeException from the binder stub implementation.
W/Binder  (26640): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Binder:26640_3
W/Binder  (26640): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
W/Binder  (26640): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:515)
W/Binder  (26640): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:74)
W/Binder  (26640): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:163)
W/Binder  (26640): 	at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:152)
W/Binder  (26640): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:95)
W/Binder  (26640): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:82)
W/Binder  (26640): 	at com.tundralabs.fluttertts.FlutterTtsPlugin$1.onStart(FlutterTtsPlugin.java:42)
W/Binder  (26640): 	at android.speech.tts.TextToSpeech$Connection$1.onStart(TextToSpeech.java:2143)
W/Binder  (26640): 	at android.speech.tts.ITextToSpeechCallback$Stub.onTransact(ITextToSpeechCallback.java:56)
W/Binder  (26640): 	at android.os.Binder.execTransact(Binder.java:731)
`

How can I fix it?

**Comment by dlutton** [comment]
Can you provide the flutter version you're using and the device/emulator and API version you're testing on?

**Comment by panthe** [comment]
Sure,
[✓] Flutter (Channel master, v1.5.9-pre.202, on Mac OS X 10.13.6 17G6030, locale it-IT)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)

**Comment by panthe** [comment]
Sorry, I'm switched to the stable channel and this error disappears.
