### ISSUE TITLE
is it possible to get speech duration?

### ISSUE THREAD

**Issue by serraojoao** [dlutton/flutter_tts#354]
## 💬 Questions and Help

Is it possible to get the speech duration for a given text?

**Comment by dlutton** [comment]
@serraojoao not that I'm aware of.  For the Android piece, it's using the build in android TTS API - https://developer.android.com/reference/android/speech/tts/TextToSpeech and I don't see an option to get the duration.  I also don't see anything for iOS Speech Synthesis.  There is a progressHandler to get the progress as it's playing, but nothing in advance.
