### ISSUE TITLE
Please consider removing this part. "splitablePunctuations"

### ISSUE THREAD

**Issue by khjde1207** [dlutton/flutter_tts#355]
## 🐛 Bug Report

Please consider removing this part.

https://github.com/dlutton/flutter_tts/blob/c0d6d9609929adfbbd2522bb7eb6a7ad6476df46/android/src/main/kotlin/com/tundralabs/fluttertts/FlutterTtsPlugin.kt#L569-L581

"3.14%"
Please listen to tts.
It reads three , fourteen percent.

### Configuration

I don't think you should edit the text.

Japan and China use "。" as a period.

Depending on the user, you may not want to pause too long at the period.

Moon+ Reader has the ability to read multiple lines at once.

This is due to a bug in the TTS engine in some countries that stops reading short sentences.

**Version:** 3.6.2

**Platform:** 
- [ ] :iphone: iOS
- [ O] :robot: Android

**Comment by dlutton** [comment]
@khjde1207 great catch, I'll see if there is a work around to keep this functionality in there for "pause" to work inside of Android.  Otherwise I may need to put a config around it to allow pause in Android knowing this could be an issue.  I'm not a fan of these work arounds since "pause" isn't a native method inside of the Android TTS API, but people want it.

**Comment by khjde1207** [comment]
I've implemented a function to pause in dart.
```
int lastProgrss = 0;
init(){
  tts!.setProgressHandler((text, start, end, word) {
          lastProgrss = start;
    });
}
play(String speakText){
      if (lastProgrss > 1 && speakText.length > lastProgrss ) {
          speakText = speakText.substring(lastProgrss - 1);
          lastProgrss = 0;
      }
    var bspeak = await tts?.speak(speakText);
   lastProgrss = 0;
}
```
I worked based on the reading position as above.

**Comment by dlutton** [comment]
@khjde1207 

Thanks for the idea, I've implemented something similar to that, but I did so inside the android code since running on web causes issues if checking if the Platform.isAndroid inside the dart code.

When you get a moment, do you mind testing out the pause functionality in this branch before I merge it in:

```
flutter_tts:
    git:
      url: https://github.com/dlutton/flutter_tts.git
      ref: android-refactored-pause
```

**Comment by khjde1207** [comment]
I see. I'll do some tests and give you feedback.

**Comment by khjde1207** [comment]
Tested in several ways.
It seems to work very well.
However, I found a couple of issues unrelated to this.
I'll sort this out and register it as a new issue.

**Comment by dlutton** [comment]
@khjde1207 thank you for testing, does it also solve for your issue #365?

**Comment by khjde1207** [comment]
no.
Issue #365 is old.
Due to this problem, I wrote different dart logic for ios, android, and web.
However, recently there have been complaints from users that it uses a lot of battery. By modifying this part, it seemed to reduce battery consumption to some extent.

**Comment by dlutton** [comment]
@khjde1207 I see, so adding the below to both stop and pause will solve the issue for you?
```
if(speakResult != null){
    handler?.post { speakResult?.success(0) }
    speakResult = null;
}
```
I can also add that fix in.

**Comment by khjde1207** [comment]
```
ref: android-refactored-pause : 
FlutterTtsPlugin.kt: 282 line 

 "pause" -> {
                isPaused = true
                if (pauseText != null) {
                    pauseText = pauseText!!.substring(lastProgress)
                }
                stop()
                result.success(1)
                if(speakResult != null){
                    speakResult!!.success(0)
                    speakResult = null;
                } 
            }
            "stop" -> {
                isPaused = false
                pauseText = null
                stop()
                lastProgress = 0
                result.success(1)
                if(speakResult != null){
                    speakResult!!.success(0)
                    speakResult = null;
                } 
            }
```

I modified it as above and confirmed that it works without any problems.

**Comment by dlutton** [comment]
@khjde1207 
Thank you, I appreciate that.  I'll include it in the fix.

**Comment by khjde1207** [comment]
Thank you !

**Comment by dlutton** [comment]
The fix has been merged in.
