### ISSUE TITLE
setProgressHandler end offset seems to be wrong

### ISSUE THREAD

**Issue by bbence84** [dlutton/flutter_tts#356]
## 🐛 Bug Report

It seems that setProgressHandler is broken. :( I would use the start and end variables for text highlighting, but the function returns strange values. See the following debug info:

I/flutter ( 6684): startOff:0, endOff:0, word:Excuse, textLen:36, text:Excuse me, can you tell me the time?,
I/flutter ( 6684): startOff:7, endOff:14, word:me, textLen:36, text:Excuse me, can you tell me the time?,
I/flutter ( 6684): startOff:11, endOff:22, word:can, textLen:36, text:Excuse me, can you tell me the time?,
I/flutter ( 6684): startOff:15, endOff:30, word:you, textLen:36, text:Excuse me, can you tell me the time?,
I/flutter ( 6684): startOff:19, endOff:38, word:tell, textLen:36, text:Excuse me, can you tell me the time?,
I/flutter ( 6684): startOff:24, endOff:48, word:me, textLen:36, text:Excuse me, can you tell me the time?,
I/flutter ( 6684): startOff:27, endOff:54, word:the, textLen:36, text:Excuse me, can you tell me the time?,
I/flutter ( 6684): startOff:31, endOff:62, word:time, textLen:36, text:Excuse me, can you tell me the time?,

As you can see, the end offset is off, it returns wrong values, not the end of the substring in the original text. The problem if I would use the word variable, then if the word would appear multiple times, it would be wrong.

### Expected behavior

start and end values should be suitable for text part highlighting.

### Reproduction steps

Use setProgressHandler :)

### Configuration

**Version:** 3.6.1

**Platform:** 
- [X] :robot: Android

**Comment by dlutton** [comment]
@bbence84 I'll take a look

**Comment by dlutton** [comment]
@bbence84 

Can you test this branch when you get a moment to see if it resolve the issue you're running into (I believe the current pause functionality causes a few issues, so I refactored it).  I did make a note on the README about using `pause` and setProgressHandler.  If you're not using pause, then it should work as is, otherwise you'll need to keep a track of offset values when pause is invoked.

```
flutter_tts:
    git:
      url: https://github.com/dlutton/flutter_tts.git
      ref: android-refactored-pause
```

**Comment by dlutton** [comment]
The fix has been merged in.  Please note the issue if using pause.
