### ISSUE TITLE
Is it working on Android 12?

### ISSUE THREAD

**Issue by joyjiyuan** [dlutton/flutter_tts#358]
v3.6.1
It was working fine on Android 11.
But on Android 12, the initHandler is not working.

v3.6.2
on Android 12, the initHandler is working, but other functions like getDefaultEngine, getEngines are not.

**Comment by dlutton** [comment]
@joyjiyuan depending on how you're using it, the initHandler won't be called when calling setEngine with 3.6.2 since it's done for you.  The initHandler should be called when first initializing the TTS engine (basically when you instantiate FlutterTts).

**Comment by dlutton** [comment]
The fix has been merged in.
