### ISSUE TITLE
Punctuation function

### ISSUE THREAD

**Issue by felix0324324** [dlutton/flutter_tts#360]
How can I add the functions for read "Punctuation"
Just like , . ? !
https://developer.apple.com/documentation/speech/sfspeechrecognitionrequest/3930023-addspunctuation?changes=l_2

Thankyou all for answer this question

**Comment by dlutton** [comment]
looks like a good enhancement @felix0324324 , I don't think Android has this setting, so it may be an iOS only setting.

**Comment by dlutton** [comment]
my apologies @felix0324324 but I just realized addsPunctuation is available for SFSpeechRecognitionRequest and not the AVSpeechSynthesizer class, so I'm unable to implement that.
