### ISSUE TITLE
tts does not play on android 13

### ISSUE THREAD

**Issue by serraojoao** [dlutton/flutter_tts#363]
## 💬 Questions and Help

I've been working with flutter_tts however when testing on android 13 (emulator) it does not work, anyone faced the same issue?

It works fine with emulator on version 11 and samsung a12 with android 12.

Tested with flutter_tts 3.6.2

thank you

**Comment by amirVirtuenetz** [comment]
> ## 💬 Questions and Help
> I've been working with flutter_tts however when testing on android 13 (emulator) it does not work, anyone faced the same issue?
> 
> It works fine with emulator on version 11 and samsung a12 with android 12.
> 
> Tested with flutter_tts 3.6.2
> 
> thank you

have you found the solutions?

**Comment by dlutton** [comment]
I tested on a real device using android 13 and it's working.

**Comment by serraojoao** [comment]
Thanks, had some tests on real device and also working fine as well.
