### ISSUE TITLE
Calling speak() after calling pause() does not work

### ISSUE THREAD

**Issue by aemsoftwarearacatuba** [dlutton/flutter_tts#366]
## 🐛 Bug Report

when you execute speak and then immediately execute pause, you are not executing the pause handler. making pause obsolete.

`  Future _pause() async {
    var result = await flutterTts.pause();
    if (result == 1) setState(() => ttsState = TtsState.paused);
  }

 flutterTts.setPauseHandler(() {
      setState(() {
        print("Paused");
        ttsState = TtsState.paused;
      });
    });

`
### Expected behavior

run the pause handler and print the message to the console

**Version:** 

flutter_tts: ^3.6.3

**Platform:** 
WEB (Chrome)

**Comment by dlutton** [comment]
this is fixed in the latest release
