### ISSUE TITLE
Voice selection for iOS.

### ISSUE THREAD

**Issue by IvanBean** [dlutton/flutter_tts#37]
## 🚀 Feature Requests

Hi, is it possible to do voice selection on iOS? I've seen #16 which implement for Android, not sure whether native iOS allow similar behavior. Thanks!

**Comment by dlutton** [comment]
@IvanBean not that I'm aware of, however if you locate something in their docs, I'd be happy to implement it when I get some time.

**Comment by IvanBean** [comment]
In my imagination from [StackOverFlow's answer](https://stackoverflow.com/questions/35492386/how-to-get-a-list-of-all-voices-on-ios-9), we can use [AVSpeechSynthesisVoice.speechVoices()](https://developer.apple.com/documentation/avfoundation/avspeechsynthesisvoice/1619697-speechvoices) to get available voices, and set voice by [AVSpeechSynthesisVoice.init(identifier:)](https://developer.apple.com/documentation/avfoundation/avspeechsynthesisvoice/1619711-init).

**Comment by dlutton** [comment]
I'm currently using AVSpeechSynthesisVoice.speechVoices() to return the languages since it returns a unique default voice per language region.

**Comment by IvanBean** [comment]
Thank you very much for the explanation! I'll try to implement these days.
