### ISSUE TITLE
setLanguage not working on web deploy

### ISSUE THREAD

**Issue by mbcode64** [dlutton/flutter_tts#373]
setLanguage("es") when built for Android is a woman's voice with a Spanish accent, and the pronunciation is spot on. When built for web, it is a man's voice with an American accent and incorrect pronunciation.

**Comment by dlutton** [comment]
@mbcode64 they all use the platform specific TTS engine.   Android, iOS, Windows, and Web each use their own engine so they will sound different across devices.
