### ISSUE TITLE
setProgressHandler not working in flutter web at all

### ISSUE THREAD

**Issue by OmarBakry-eg** [dlutton/flutter_tts#376]
## 🐛 Bug Report
Thanks for coding this awesome plugin.
This library contain an issue and I can describe it as a bug, the setProgressHandler not working in the web at all the function not being called whatever you did!. So please let us know if we just screwed up or the plugin needed an update.

### Expected behavior
setProgressHandler working fine in all platforms as the library description. 

### Configuration

**Package Version:** : ^3.6.3
**Flutter Version:** :  3.7.6

**Platform:** 
- [ ] :robot: Web

**Code snippet**

enum TtsState { playing, stopped, paused, continued }

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController textEditingController = TextEditingController();
  FlutterTts flutterTts = FlutterTts();
  TtsState? ttsState;
  Future _speak(String sentence) async {
    log('play');
    await flutterTts.speak(sentence);
    setState(() => ttsState = TtsState.playing);
  }

  Future _stop() async {
    log('stop');
    await flutterTts.stop();
    setState(() => ttsState = TtsState.stopped);
  }

  @override
  void initState() {
    super.initState();
    flutterTts
        .setProgressHandler((String text, int start, int end, String word) {
      log('message');
    });
    flutterTts.setCompletionHandler(() {
      setState(() {
        ttsState = TtsState.stopped;
      });
    });
  }

  @override
  void dispose() {
    super.dispose();
    flutterTts.stop();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        actions: [
          IconButton(
              onPressed: () async {
                if (textEditingController.text.isNotEmpty) {
                  ttsState == TtsState.playing
                      ? _stop()
                      : _speak(textEditingController.text);
                }
              },
              icon: ttsState == TtsState.playing
                  ? const Icon(Icons.stop)
                  : const Icon(Icons.play_arrow_outlined))
        ],
        centerTitle: true,
        title: const Text("Text Reader App"),
      ),
      body: Column(
        children: [
          TextField(
            controller: textEditingController,
            onChanged: (String v) {
              setState(() {});
            },
            decoration: const InputDecoration(
                labelText: 'Text', hintText: 'Enter the text to read'),
          ),
          const SizedBox(
            height: 40,
          ),
          if (textEditingController.text.isNotEmpty) ...[
            Text(textEditingController.text)
          ]
        ],
      ),
    );
  }
}

**Comment by dlutton** [comment]
@OmarBakry-eg this isn't currently supported for web
