### ISSUE TITLE
Macos error when trying to install pod

### ISSUE THREAD

**Issue by silasrm** [dlutton/flutter_tts#377]
## 🐛 Bug Report

When flutter run -d macos is running, there try to install all pods, but failing when try to install flutter_tts pod.

### Expected behavior

Install pod and run without error.

### Reproduction steps

On Macos, with flutter tts package, run: flutter run -d macos

```
Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_d_d_6.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/d/d/6/ReachabilitySwift/5.0.0/ReachabilitySwift.podspec.json exists! Returning local because checking is only performed in repo update
    [!] CocoaPods could not find compatible versions for pod "flutter_tts":
      In Podfile:
        flutter_tts (from `Flutter/ephemeral/.symlinks/plugins/flutter_tts/macos`)

    Specs satisfying the `flutter_tts (from `Flutter/ephemeral/.symlinks/plugins/flutter_tts/macos`)` dependency were found, but they required a higher minimum deployment target.
```

### Configuration

Flutter 3.7.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c07f788888 (3 weeks ago) • 2023-02-22 17:52:33 -0600
Engine • revision 0f359063c4
Tools • Dart 2.19.2 • DevTools 2.20.1

**Platform:** 
- [ x] MacOS

**Comment by addelete** [comment]
1. edit `macos/Podfile`
```ruby
platform :osx, '10.15'
```
2.open `Runner.xcodeproj` in xcode
<img width="865"  src="https://user-images.githubusercontent.com/15151761/226817720-33955644-1870-4685-bd29-b57141ff758c.png">

**Comment by silasrm** [comment]
> 1. edit `macos/Podfile`
> 
> ```ruby
> platform :osx, '10.15'
> ```
> 
> 2.open `Runner.xcodeproj` in xcode <img alt="" width="865" src="https://user-images.githubusercontent.com/15151761/226817720-33955644-1870-4685-bd29-b57141ff758c.png">

Many thanks! App run like a charm.
