### ISSUE TITLE
Selected hindi but 49 is speaking in english

### ISSUE THREAD

**Issue by bipin5711** [dlutton/flutter_tts#378]
Hii,
I have numbers 0 to 90 to speak

i have hindi language selected and others numbers are working fine but 49 is speaking in english.
can you pls check this
,4 ,9 , 49  . here 49 is speaking in english. (wrong)
,6,5, 65 here 65 speaking in hindi (correct) 

Thankjs

**Comment by dlutton** [comment]
This looks like an issue with the TTS engine on the device rather than this plugin.
