### ISSUE TITLE
It don't work when used on android 13.0

### ISSUE THREAD

**Issue by zhaoMing8** [dlutton/flutter_tts#379]
## 🐛 Bug Report
It seems impossible to get the job done.

![image](https://user-images.githubusercontent.com/41000894/224975544-3968d49a-460e-47cb-abe4-8db2a1129e60.png)

![image](https://user-images.githubusercontent.com/41000894/224975910-3bbd2deb-1631-4cba-be54-a0c1dcb4dadb.png)

**Comment by sea-fat** [comment]
我也遇到

**Comment by justjew** [comment]
Got the same

**Comment by qhdctod** [comment]
This is still an issue on android 11 as well.

**Comment by dlutton** [comment]
@zhaoMing8 @justjew @sea-fat @qhdctod  is it working for you with the example application in this repo?  I tested on a real device (pixel 5) using android 13 and it's working.
