### ISSUE TITLE
Query for com.apple.MobileAsset.VoiceServices.VoiceResources failed: 2

### ISSUE THREAD

**Issue by jplauber** [dlutton/flutter_tts#380]
## 🐛 Bug Report

On Android its working fine, but on iOS I am getting this error message: 
Query for com.apple.MobileAsset.VoiceServices.VoiceResources failed: 2

### Expected behavior
Should play the sound

### Reproduction steps
 await flutterTts.speak(germanTerm)

### Configuration

**Version:** 3.6.3

**Platform:** 
- [ x] :iphone: iOS
- [ ] :robot: Android

**Comment by valerauko** [comment]
You should check if the voice you want to use is available (try playing its sample from the settings page)

**Comment by dlutton** [comment]
@jplauber voices will differ between iOS and Android and you'll more than likely not be able to use the same voice name.  As @valerauko mentioned, you'll first need to get the voices to see what is available on the device/os.

**Comment by valerauko** [comment]
When I faced this problem, the steps I took before I noticed it's working again:
* download the "additional" version of the voice
* enable voiceover
* double check system volume
