### ISSUE TITLE
getVoices isnt returning the list of languages.

### ISSUE THREAD

**Issue by bipin5711** [dlutton/flutter_tts#386]
Hii,
I am using getVoices and it is not working.

Please check this
![image](https://user-images.githubusercontent.com/58762094/232274619-2c6f76c4-dfab-41c8-8134-a33960e779c5.png)

Thanks

**Comment by dlutton** [comment]
@bipin5711 is this Android, iOS, or Web?

**Comment by bipin5711** [comment]
Android
