### ISSUE TITLE
Is this package support Hebrew language?

### ISSUE THREAD

**Issue by BilalN10** [dlutton/flutter_tts#387]
## 💬 Questions and Help

I just want to know is this package support Hebrew language? If not  then why its not support ?

**Comment by dlutton** [comment]
@BilalN10 this package uses the native TTS APIs provided on iOS and Android, so it would be up to them to provide support for it.

**Comment by BilalN10** [comment]
ok can you please guide me if I want to use Hebrew language how can I do that?

**Comment by dlutton** [comment]
@BilalN10 it's more than likely not supported through the Google TTS Engine.
Here is a stackoverflow with a mention of it on Android -> https://stackoverflow.com/questions/16463226/android-texttospeech-in-hebrew#:~:text=That's%2C%20most%20probably%2C%20Hebrew%20is,if%20Hebrew%20is%20listed%20there.

You'd need to find a TTS engine that supports it.
