### ISSUE TITLE
How to add additional languages to the web example

### ISSUE THREAD

**Issue by MarcVanDaele90** [dlutton/flutter_tts#389]
## 💬 Questions and Help

I would like to add additional languages to the web demo on https://dlutton.github.io/flutter_tts/.
I understand that you retrieve the list of supported languages from the browser so this is beyond the scope of your plugin, right?

But do you have a pointer to a document that describes how we can add additional TTS languages to the browser?
I'm on Linux (Mint) but I would also like to know how to do this on Windows&Mac.

Thanks,

Marc

**Comment by dlutton** [comment]
@MarcVanDaele90 yes it's beyond the scope of the plugin.

It uses the web speech API -> https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API specifically the speech synthesis -> https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis
