### ISSUE TITLE
 Unable to properly handle text segments separated by "%pause%" in Flutter TTS on Android

### ISSUE THREAD

**Issue by burhanaksendir** [dlutton/flutter_tts#399]
Hello,

I am experiencing an issue with the Flutter TTS package on the Android platform. When I try to split the text using the "%pause%" delimiter, I'm unable to achieve the desired pause duration between the speech segments. The speech segments transition to the next one immediately without the expected delay. I have tried several approaches to address this problem but haven't been successful, and I'm seeking your assistance on this matter.

Example Code:

```
var text = "This is a test text. %pause% This is the second segment.";
var parts = text.split('%pause%');
for (var part in parts) {
  await _speakWithDelay(part.trim());
}

Future<void> _speakWithDelay(String text) async {
  await _flutterTts!.speak(text);
  await Future.delayed(const Duration(milliseconds: 500));
}
```

I kindly request your support in resolving this issue and ensuring proper handling of the text segments separated by "%pause%" in the Flutter TTS package on the Android platform.

Thank you for your assistance.

**Comment by dlutton** [comment]
@burhanaksendir , you can use SSML and do something like this 

```
<speak>This is a test text. <break time="2s"/> This is the second segment.</speak>
```

or you can use what you have and make sure you use `await flutterTts.awaitSpeakCompletion(true);` before you run speak.
