### ISSUE TITLE
Not working on Mac

### ISSUE THREAD

**Issue by Rockvole** [dlutton/flutter_tts#4]
I tried opening my project in xcode with flutter_tts 0.0.6 on my mac, but I get an error on startup.

![flutter_tts](https://user-images.githubusercontent.com/4139576/43795335-e392034a-9a35-11e8-9ab5-017e3faecbb9.png)

**Comment by dlutton** [comment]
I'll look into this issue.

**Comment by Rockvole** [comment]
I installed Xcode 8.3.3 using this method :
https://www.youtube.com/watch?v=IG36E5fYIpg

Now, when I try the project in Xcode 8.3.3 I get this different error :
![tts](https://user-images.githubusercontent.com/4139576/43867307-a656b8b6-9b1d-11e8-8ece-41e3f0cd3482.png)

**Comment by dlutton** [comment]
Did you try going to Build Settings to set the "Swift Language Version" to 2 and then do a clean and build project?

**Comment by Rockvole** [comment]
Apparently that's not supported in Xcode 8.3.3 :(
https://stackoverflow.com/questions/43107179/xcode-8-3-cant-support-swift-2-3

I tried converting to Swift 3 automatically, but it didn't work and there are a ton of errors.
I am completely new to the Mac, so the errors don't mean anything to me.

**Comment by dlutton** [comment]
I've gotten it to work on a couple of ios apps, so I'll need to revisit what I did.

**Comment by Rockvole** [comment]
So I installed Xcode 8.2.1 and now the tts code stops having any errors.
Unfortunately, I discovered that flutter no longer Supports XCode below version 9 (and has a hardcoded check to exclude older versions).
https://flutter.io/setup-macos/

flutter doctor doesnt find the older XCode versions.

**Comment by dlutton** [comment]
Thanks for doing further research.  I'll need to update the swift code so it's supported in version 9.

**Comment by Rockvole** [comment]
Cool thanks - do you think you will have a chance to look at that soon ?

Incidentally, you might like to know your library works great on Kindle devices. I bought a $30 Kindle Fire HD 6 (2014) and the standard voice is much more human than Android tablets. I guess because Amazon designed it for listening to audio books.

**Comment by dlutton** [comment]
Definitely, it shouldn't be too much work converting it to the latest version.

**Comment by dlutton** [comment]
@Rockvole I opened up the example in this repo without an errors in Xcode 9.4.1.  Did you make sure to run flutter build ios --no-codesign before trying to open the project in xcode?  Also, what version of swift do you have installed on your machine?

**Comment by Rockvole** [comment]
@dlutton - sorry I know so little about the Mac

Your flutter_tts is imported in pubspec.yaml with <code>flutter_tts: ^0.0.6</code>

	david-mac:kbml_viewer david$ hg meld
	david-mac:kbml_viewer david$ flutter build ios --no-codesign
	Running "flutter packages get" in kbml_viewer...             1.8s
	Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
	Building com.rockvole.kbmlViewer for device (ios-release)...
	Running pod install...                                       2.5s
	Starting Xcode build...                                          
	Xcode build done.                                            1.7s
	Failed to build iOS app
	Error output from Xcode build:
	↳
		** BUILD FAILED **
		
	Xcode's output:
	↳
		The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.
	════════════════════════════════════════════════════════════════════════════════
	Building a deployable iOS app requires a selected Development Team with a 
	Provisioning Profile. Please ensure that a Development Team is selected by:
	  1- Open the Flutter project's Xcode target with
		   open ios/Runner.xcworkspace
	  2- Select the 'Runner' project in the navigator then the 'Runner' target
		 in the project settings
	  3- In the 'General' tab, make sure a 'Development Team' is selected. 
		 You may need to:
			 - Log in with your Apple ID in Xcode first
			 - Ensure you have a valid unique Bundle ID
			 - Register your device with your Apple Developer Account
			 - Let Xcode automatically provision a profile for your app
	  4- Build or run your project again

	For more information, please visit:
	  https://flutter.io/setup/#deploy-to-ios-devices

	Or run on an iOS simulator without code signing
	════════════════════════════════════════════════════════════════════════════════
	Encountered error while building for device.

**Comment by Rockvole** [comment]
I tried to find which version of swift my project is using but I cant find it anywhere.
https://stackoverflow.com/questions/30790188/how-do-i-see-which-version-of-swift-im-using

**Comment by dlutton** [comment]
When you first open up xcode, select the option to open a new project and select the Runner.xcworkspace from the example/ios folder.  You can run swift -version from the command line to get your swift version.

**Comment by Rockvole** [comment]
david-mac:kbml_viewer david$ swift -version
Apple Swift version 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0

**Comment by dlutton** [comment]
Great now run flutter build ios --no-codesign from your main project folder and open the Runner.xcworkspace in xocde from your project/ios folder and you shouldn't get that error.

**Comment by Rockvole** [comment]
I don't have the option to set the language to Swift language version 2. Am I looking at the correct location ?
I still get the language version error when I do <code>flutter build ios --no-codesign</code> (I fixed the Development Team error).
![tts](https://user-images.githubusercontent.com/4139576/43996381-9815bd50-9d76-11e8-8026-d3c739077ffb.png)

**Comment by Rockvole** [comment]
It sounds like you are able to open the root of your project in Xcode and then navigate to <code>ios/Runner.xcworkspace</code>. I just get a could not open error - I can only open the ios directory from Xcode.

**Comment by dlutton** [comment]
When you first open up xcode, there should be an option to open a project.  From there you will open Runner.xcworkspace from your project/ios folder.

**Comment by dlutton** [comment]
okay, I ran into this issue before and I'm not sure exactly how to fix it in it's current state, however since this package was built using swift, when you build your project, you'll have to build it with the swift command, such as `flutter create -i swift first_app`.   With that, I was able to copy over your pubspec.yaml and main.dart file and ran `flutter build ios --no-codesign` successfully.

**Comment by Rockvole** [comment]
You are right - that worked straight away

@dlutton - thanks for all your help with this I really appreciate it :)
