### ISSUE TITLE
[iOS] Add additional `quality` field to return value of `getVoices` to distinguish different voices

### ISSUE THREAD

**Issue by SPICYJO** [dlutton/flutter_tts#400]
## 🚀 Feature Requests

- Add additional `quality` field to the map returned by `getVoices` for identification of voices.

### Contextualize the feature

- For now, we cannot distinguish two voices of the same name when we install the enhanced version of voice in iOS.

- If we install the additional voices of the same name with different qualities (normal, enhanced, and premium), and call the `getVoices` function, we cannot distinguish the voices of the same name.

### Reproduction steps

- Settings > Accessibility > Spoken Content > Voices > Install additional voices with different qualities
![image](https://github.com/dlutton/flutter_tts/assets/48597218/28a91038-4648-45b1-83f5-bced0915893d)

- Then, calling the `getVoices` returns map containing indistinguishable entries of voices.
![image](https://github.com/dlutton/flutter_tts/assets/48597218/0ec44806-aa42-4df5-aeee-efa7e0d1cd78)

### Describe the feature
- Adding an additional field describing `quality` would help. iOS's `AVSpeechSynthesisVoice` class has quality field, so I think we can use that. (iOS enum values: default, enhanced, premium)
- Android's API also provide quality field too. (Android values: QUALITY_VERY_HIGH, QUALITY_HIGH, QUALITY_NORMAL, QUALITY_LOW, QUALITY_VERY_LOW)
- Web API does not provide quality field.

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android (maybe)

**Comment by Colton127** [comment]
I'm able to discover premium/enhanced voices via getVoices and select them appropriately on an iPhone X running iOS 16.6. 

For example, after installing Susan (enhanced), getVoices returns:
`Susan (Enhanced), locale: en-US `

From there, you can do

`flutterTTS.setVoice({"name": 'Susan (Enhanced)', "locale":'en-US'});`
