### ISSUE TITLE
Support for onRangeStart in UtteranceProgressListener 

### ISSUE THREAD

**Issue by ormrodjames** [dlutton/flutter_tts#41]
Great plugin! Any chance you can add support for onRangeStart (Android) and willSpeakRangeOfSpeechString (IOS)??

I'm porting my Swift/IOS app to Flutter/Android, it uses this callback to highlight each utterance as it is spoken, giving useful feedback to the user that the app is actually speaking (if the volume is off, for example).

I'd do a pull request but I'm running flat out to hit a hard deadline at the moment ;) but FWIW I implemented a quick version in a local copy (Android only) with the following:

// In FlutterTtsPlugin.java within utteranceProgressListener..
        // ...
        @Override
        public void onRangeStart(String utteranceId, int start, int end, int frame) {
          ArrayList<Integer> offsets = new ArrayList<>(3);
          offsets.add(Integer.valueOf(start));
          offsets.add(Integer.valueOf(end));
          offsets.add(Integer.valueOf(frame));
          channel.invokeMethod("speak.onRangeStart", offsets);
        }
        // ...

// In flutter_tts.dart..

   typedef void RangeHandler(dynamic offset);

   // Within FlutterTts
   RangeHandler onRangeStartHandler;
  
   void setRangeHandler(RangeHandler callback) {
     onRangeStartHandler = callback;
   }

  // New case

  Future platformCallHandler(MethodCall call) async {
    switch (call.method)
      // ...
      case "speak.onRangeStart":
        if (onRangeStartHandler != null) {
          onRangeStartHandler(call.arguments);
        }
        break;
       // ...

**Comment by dlutton** [comment]
I had someone else request this feature, so I'll look into adding it after I go through the pull requests I currently have.  Thanks for the suggestion.

**Comment by ormrodjames** [comment]
Cheers!

**Comment by paulscliu** [comment]
Any update on this feature?

**Comment by dlutton** [comment]
@paulscliu Unfortunately I haven't had the time to implement this feature yet.  I was more concerned with adding a web implementation first.  This is still a priority though.
