### ISSUE TITLE
synthesizeToFile not working in web

### ISSUE THREAD

**Issue by bansalgaurav852** [dlutton/flutter_tts#410]
``` await flutterTts
            .synthesizeToFile(_newVoiceText!, "voice-${DateTime.now()}.mp3")
            .then((value) {
          print("downloaded");
        });

```
this code working fine in android and downloading file in app storage but when i use same in web get error.
please help to resolve this or anyway to get bytes list so can store it on desire path/folder

**Comment by dlutton** [comment]
@bansalgaurav852 this is only supported on iOS and Android.  The web speech API doesn't provide a method for downloading the speech to a file unfortunately.

Link to web speech API -> https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis
