### ISSUE TITLE
Is that possible to integrate engine with Google Cloud?

### ISSUE THREAD

**Issue by Jaha96** [dlutton/flutter_tts#411]
## 💬 Exploring Integration of Engine with Google Cloud

I'm curious about the feasibility of integrating the engine with Google Cloud. While I'm aware that the plugin primarily utilizes built-in engines from Android or iOS devices, I'm interested in knowing whether there's a possibility to integrate it with [ Google Cloud's text-to-speech service](https://cloud.google.com/text-to-speech#section-2). Specifically, I'm keen on leveraging features like the Neural2 voices that Google Cloud offers. 

Is there a potential workaround to achieve this integration?

**Comment by dlutton** [comment]
@Jaha96 there might already be another flutter package that deals with Google Cloud Text to Speech, but I'm not sure.  i'm not sure if it makes sense to integrate a cloud service into this package which I believe is also a paid service.  It might make sense to create a separate package for that.

**Comment by Jaha96** [comment]
@dlutton Thank you for your response. I agree that if it really make sense. I wanted to confirm just in case. Unfortunately they do not currently offer client package for Flutter or Dart.

**Comment by dlutton** [comment]
@Jaha96 It should be a rather simple API request and there might be some 3rd party implementations out there.
