### ISSUE TITLE
Speak... Done... or Cancel?

### ISSUE THREAD

**Issue by SteveBraich** [dlutton/flutter_tts#412]
## 💬 Questions and Help

I have having a problem when I have a IconButton button that uses flutter_tts.  

This IconButton widget shows a speaker (or volumn_up Icon).

- When you press it, the IconButton changes to a 'stop' icon
- When it is done speaking, the speaker IconButton should change back to a volume up button

However, when pressing the IconButton (stop), it should basically change back into a mic icon state, and cancel the speak.

I can't seem to get both cancelling and change back to a mic when done to work.

I can do one or the other.

Any help, like some code, would be greatly appreciated.

**Comment by dlutton** [comment]
@SteveBraich I'm not sure this is related to this package.  You can set await flutterTts.awaitSpeakCompletion(true); and then await for the speaking to be completed or use the completion handler.  If stopped is pressed then you'd need a way to update those values when that action occurs.  You'll want to make sure you update the state.
