### ISSUE TITLE
"Cannot convert value of type 'String' to expected argument type 'URL'" in version 3.8.0

### ISSUE THREAD

**Issue by bjarke-uptime** [dlutton/flutter_tts#416]
## 🐛 Bug Report

I'm getting a build error on iOS when using the latest version (3.8.0) of this package:

Swift Compiler Error (Xcode): Cannot convert value of type 'String' to expected argument type 'URL'
/Users/bjarke/.pub-cache/hosted/pub.dev/flutter_tts-3.8.0/ios/Classes/SwiftFlutterTtsPlugin.swift:198:26

### Expected behavior

Expected to build without issues, it appears to be a broken cast between 'string' and 'NSUrl'.

### Reproduction steps

````
VSCode: > Flutter New Project

flutter pub add flutter_tts
flutter run
````

### Configuration

**Version:** 3.8.0

**Platform:** 
- [x] :iphone: iOS

**Comment by dlutton** [comment]
fixed in 3.8.1
