### ISSUE TITLE
Android builds break on version 3.8.3

### ISSUE THREAD

**Issue by chris208** [dlutton/flutter_tts#424]
## 🐛 Bug Report

I am trying to use this plugin on my Flutter project and installed the v3.8.3, I already followed the example code but I can't build my project, I've tried to uninstall the plugin, and I can build my project back.

### Configuration
Flutter doctor:
![image](https://github.com/dlutton/flutter_tts/assets/12391114/393de7cb-b5e7-4871-b1c6-aabe9b3a8ea2)

/android/build.gradle:
![image](https://github.com/dlutton/flutter_tts/assets/12391114/5430d755-4cf5-4104-a2a2-06f10696a128)

Error message:
![image](https://github.com/dlutton/flutter_tts/assets/12391114/d91c9883-259a-427c-b756-b442c6bb4d81)

**Version:** 3.8.3

**Platform:** 
- [ ] :robot: Android

**Comment by Haris2v** [comment]
Try deleting the pubspec.lock file and then run `flutter clean` and then` flutter pub get`. Hope it will work
