### ISSUE TITLE
Example app doesn't work on iOS 17 simulator on MacOS Sonoma

### ISSUE THREAD

**Issue by vasanth-asokan** [dlutton/flutter_tts#425]
## 🐛 Bug Report

The example flutter_tts app doesn't work on iOS 17 simulators on MacOS Sonoma. I was able to narrow it down by verifying that the example app works fine on an iOS 16 simulator and Android simulators. 

### Expected behavior
Typing some text into the text field and pressing play should work but doesn't. I also don't see any of the messages in the debug console of VSCode that indicate the FlutterTts lifecycle is executing normally (e.g. "Playing"). No error messages are displayed in the stack trace.

### Reproduction steps

1. Clone flutter_tts repo
2. Launch `example/lib/main.dart` on iOS simulator 17.0 (tried IPhone 15 pro and Ipad 10th generation 11 inch simulators) and clicking on play produces no audio. No errors on the console.
### Configuration

**Version:** 3.8.3

**Platform:** 
- [X] :iphone: iOS
- [ ] :robot: Android

**Comment by dlutton** [comment]
@vasanth-asokan this has been an issue with previous iOS simulators which is unrelated to this package.  There may not be any languages installed by default on the simulator you're using.
Try going to settings -> Spoken content -> Voices -> Select any language and download.

**Comment by vasanth-asokan** [comment]
Thanks @dlutton. Indeed, I had noticed the previous issue reports. I forgot to mention, languages are downloaded on my 17.0 simualtors so this seems like a different issue, specific to iOS 17.0 simulators.

**Comment by alanguodev** [comment]
I got a similar issue, TTS play on iOS 17.0 simulator broken (no sound) and under XCode debugger I got the following errors: 
Query for com.apple.MobileAsset.VoiceServicesVocalizerVoice failed: 2
#FactoryInstall Unable to query results, error: 5
Unable to list voice folder
Query for com.apple.MobileAsset.VoiceServices.GryphonVoice failed: 2
Unable to list voice folder
Unable to list voice folder
Query for com.apple.MobileAsset.VoiceServices.GryphonVoice failed: 2
Unable to list voice folder
Query for com.apple.MobileAsset.VoiceServicesVocalizerVoice failed: 2
Unable to list voice folder
Query for com.apple.MobileAsset.VoiceServices.GryphonVoice failed: 2
Unable to list voice folder
Unable to list voice folder
Query for com.apple.MobileAsset.VoiceServices.GryphonVoice failed: 2
Unable to list voice folder

**Comment by gunantosteven** [comment]
After I changed the voice other than Karen, for instance "Agnes". Reset simulator, now it works.

**Comment by getong** [comment]
I have some issue with MacOS Sonoma. I create the project
```
flutter create flutter_tts_example
cd flutter_tts_example
flutter pub add -d flutter_tts
```
I change example/lib/main.dart into  flutter_tts_example/lib/main.dart,
and change the macos/Podfile:
```
platform :osx, '10.15'
```
But I compile fail, the error code:
```
flutter_tts_example/macos/Flutter/GeneratedPluginRegistrant.swift:8:8: error: compiling for macOS 10.14, but module 'flutter_tts' has a minimum deployment target of macOS
 10.15: flutter_tts_example/build/macos/Build/Products/Debug/flutter_tts/flutter_tts.framework/Modules/flutter_tts.swiftmodule/x86_64-apple-macos.swiftmodule
import flutter_tts
```

But I can compile the example code in the flutter_tts code project.
Finally I copy the podfile and project.pbxproj into the flutter_tts_example project, and it compiles.
```
cp  flutter_tts/example/macos/Podfile macos/Podfile
cp  flutter_tts/example/macos/Runner.xcodeproj/project.pbxproj macos/Runner.xcodeproj/project.pbxproj
```
I wonder the `Podfile` and `project.pbxproj` might be updated in the macos sonoma.

**Comment by swarupbhc** [comment]
I'm facing the same issue.

**Comment by zfc0812** [comment]
Any fix for this issue?

**Comment by umairsaeed-us** [comment]
Any updare of this issue?

**Comment by proddam** [comment]
Any update on this issue?

**Comment by dlutton** [comment]
issues related to iOS 17 appear to be an issue with Apple's TTS engine AVSpeechSynthesis.

https://forums.developer.apple.com/forums/thread/738048
