### ISSUE TITLE
Error "java.lang.IllegalStateException: Reply already submitted" when calling getDefaultEngine

### ISSUE THREAD

**Issue by TranTuanManh** [dlutton/flutter_tts#428]
## 🐛 Bug Report
Thank you for your great plugin. 
Some users got this error on their Samsung devices. Maybe this caused crash app because my users reported that their app was closed right after a few seconds. 

![image](https://github.com/dlutton/flutter_tts/assets/29418461/98a55109-f301-4083-8688-a803e2e95f6b)

### Reproduction steps
This is my code
![image](https://github.com/dlutton/flutter_tts/assets/29418461/bbb5f743-ebfa-4f8d-b9f1-9cdc448e34d2)
![image](https://github.com/dlutton/flutter_tts/assets/29418461/ad32aba9-e1e7-4928-a047-7b1ee3de4e02)

### Configuration
![image](https://github.com/dlutton/flutter_tts/assets/29418461/a5eb2ce7-3811-45d0-a16f-b666b85f025d)

**Version:** 3.8.3

**Platform:** 
- [x] :robot: Android

**Comment by Colton127** [comment]
I encountered this issue on a s22 ultra. This pull request appeared to resolve it: https://github.com/dlutton/flutter_tts/pull/421

**Comment by dlutton** [comment]
fix merged in
