### ISSUE TITLE
Persian language support

### ISSUE THREAD

**Issue by vaaniiaa** [dlutton/flutter_tts#434]
Persian language support

Hello
I need to know whether this TTS library supports Persian (Farsi) language (fa-IR) or not.
I add fa-IR to locales list but it did not work.
will it be added in future? because there many countries that speaks in Farsi and this feature can help them in their application.

with regards

**Comment by dlutton** [comment]
This flutter package utilizes the TTS engines on the devices itself, so unfortunately it has no control over languages that are supported or not.
