### ISSUE TITLE
Build error with 3.8.4 when iOS minimum version is lower than 13.

### ISSUE THREAD

**Issue by Leffe108** [dlutton/flutter_tts#439]
## 🐛 Bug Report

When building my app with flutter_tts upgraded from 3.8.3 to 3.8.4 I get this build error. It looks related to what is mentioned in the changelog for 3.8.4.

```
Swift Compiler Error (Xcode): 'AVSpeechSynthesisVoiceGender' is only available in iOS 13.0 or newer
/Users/builder/.pub-cache/hosted/pub.dev/flutter_tts-3.8.4/ios/Classes/SwiftFlutterTtsPlugin.swift:433:10
```

### Expected behavior

Able to complie app for iOS with the plugin updated to 3.8.4. or that the changelog notes that this is a breaking change that requires raising minimum supported iOS version of your app.

### Reproduction steps

I build app using codemagic.io with default Xcode 15 version supplied by them.

From my AppFrameworkInfo.plist
```
  <key>MinimumOSVersion</key>
  <string>11.0</string>
```

### Configuration

**Version:** 3.8.4

**Platform:** 
- [x] :iphone: iOS

**Comment by dlutton** [comment]
fixed in 3.8.5
