### ISSUE TITLE
Continuously facing this issue. The method 'speak' was called on null. Receiver: null

### ISSUE THREAD

**Issue by SSG111** [dlutton/flutter_tts#44]
Is there any way to make it work? I have tried nearly all the code available for flutter_tts. It is still not working for me. It will be a huge favor if you can guide me a little.

```
import 'package:flutter/material.dart';

import 'dart:async';
import 'dart:io';
import 'package:easelang/Modals/Alphabets.dart';
import 'package:flutter_tts/flutter_tts.dart';

class AlphabetRow extends StatefulWidget {
  final Alphabet alphabet;
  final bool horizontal;

  AlphabetRow(this.alphabet, {this.horizontal = true});
  AlphabetRow.vertical(this.alphabet) : horizontal = false;

  @override
  _AlphabetRowState createState() => _AlphabetRowState();
}

enum TtsState { playing, stopped }

class _AlphabetRowState extends State<AlphabetRow> {
  var alphabet;
  FlutterTts flutterTts;
  dynamic languages;
  dynamic voices;
  String language;
  String voice;

  TtsState ttsState = TtsState.stopped;

  get isPlaying => ttsState == TtsState.playing;
  get isStopped => ttsState == TtsState.stopped;

  @override
  void initState() {
    super.initState();
    initSpeak();
  }

  initSpeak() async {
    FlutterTts flutterTts = FlutterTts();

    if (Platform.isAndroid) {
      flutterTts.ttsInitHandler(() {
        _getLanguages();
        _getVoices();
      });
    } else if (Platform.isIOS) {
      _getLanguages();
      _getVoices();
    }

    flutterTts.setStartHandler(() {
      print("runtimeType is: ${widget.runtimeType}");
      setState(() {
        ttsState = TtsState.playing;
      });
    });

    flutterTts.setCompletionHandler(() {
      setState(() {
        ttsState = TtsState.stopped;
      });
      print("setCompletionHandler called");
    });

    flutterTts.setErrorHandler((msg) {
      setState(() {
        ttsState = TtsState.stopped;
      });
    });
  }

  Future _getLanguages() async {
    languages = await flutterTts.getLanguages;
    if (languages != null) setState(() => languages);
  }

  Future _getVoices() async {
    voices = await flutterTts.getVoices;
    if (voices != null) setState(() => voices);
  }

  Future<dynamic> _speak() async {
    if (widget.alphabet.letter != null) {
      if (widget.alphabet.letter.isNotEmpty) {
        var result = await flutterTts.speak(widget.alphabet.letter);
        if (result == 1) setState(() => ttsState = TtsState.playing);
      }
    }
  }

  // Future _stop() async {
  //   var result = await flutterTts.stop();
  //   if (result == 1) setState(() => ttsState = TtsState.stopped);
  // }

  @override
  void dispose() {
    super.dispose();
    flutterTts.stop();
  }

  @override
  Widget build(BuildContext context) {
    final alphabetSound = Container(
      margin: EdgeInsets.symmetric(
        vertical: 24.0,
      ),
      alignment: widget.horizontal
          ? FractionalOffset.centerRight
          : FractionalOffset.center,
      child: MaterialButton(
        padding: EdgeInsets.fromLTRB(0.0, 0.0, 0.0, 0.0),
        shape:
            RoundedRectangleBorder(borderRadius: BorderRadius.circular(100.0)),
        highlightColor: Colors.white,
        color: Colors.white,
        splashColor: Colors.red[800],
        height: 25.0,
        minWidth: 65.0,
        child: Icon(
          Icons.volume_up,
          size: 25.0,
        ),
        onPressed: () {
          _speak();
        },
      ),
    );
}
}

```

**Comment by dlutton** [comment]
Is this the full code of what you're trying to test or a snippet of it?  Also, are you testing in an emulator and if so, which one?

**Comment by SSG111** [comment]
Thank you so much for your quick response. I have tested it on my phone Redmi 4. And also on anemulator Pixel 2 API 28. here is the full code - 

import 'package:flutter/material.dart';

import 'dart:async';
import 'dart:io';
import 'package:easelang/Modals/Alphabets.dart';
import 'package:flutter_tts/flutter_tts.dart';

class AlphabetRow extends StatefulWidget {
  final Alphabet alphabet;
  final bool horizontal;

  AlphabetRow(this.alphabet, {this.horizontal = true});
  AlphabetRow.vertical(this.alphabet) : horizontal = false;

  @override
  _AlphabetRowState createState() => _AlphabetRowState();
}

enum TtsState { playing, stopped }

class _AlphabetRowState extends State<AlphabetRow> {
  var alphabet;
  FlutterTts flutterTts;
  dynamic languages;
  dynamic voices;
  String language;
  String voice;

  TtsState ttsState = TtsState.stopped;

  get isPlaying => ttsState == TtsState.playing;
  get isStopped => ttsState == TtsState.stopped;

  @override
  void initState() {
    super.initState();
    initSpeak();
  }

  initSpeak() async {
    FlutterTts flutterTts = FlutterTts();

    if (Platform.isAndroid) {
      flutterTts.ttsInitHandler(() {
        _getLanguages();
        _getVoices();
      });
    } else if (Platform.isIOS) {
      _getLanguages();
      _getVoices();
    }

    flutterTts.setStartHandler(() {
      print("runtimeType is: ${widget.runtimeType}");
      setState(() {
        ttsState = TtsState.playing;
      });
    });

    flutterTts.setCompletionHandler(() {
      setState(() {
        ttsState = TtsState.stopped;
      });
      print("setCompletionHandler called");
    });

    flutterTts.setErrorHandler((msg) {
      setState(() {
        ttsState = TtsState.stopped;
      });
    });
  }

  Future _getLanguages() async {
    languages = await flutterTts.getLanguages;
    if (languages != null) setState(() => languages);
  }

  Future _getVoices() async {
    voices = await flutterTts.getVoices;
    if (voices != null) setState(() => voices);
  }

  Future<dynamic> _speak() async {
    if (widget.alphabet.letter != null) {
      if (widget.alphabet.letter.isNotEmpty) {
        var result = await flutterTts.speak(widget.alphabet.letter);
        if (result == 1) setState(() => ttsState = TtsState.playing);
      }
    }
  }

  // Future _stop() async {
  //   var result = await flutterTts.stop();
  //   if (result == 1) setState(() => ttsState = TtsState.stopped);
  // }

  @override
  void dispose() {
    super.dispose();
    flutterTts.stop();
  }

  @override
  Widget build(BuildContext context) {
    final alphabetSound = Container(
      margin: EdgeInsets.symmetric(
        vertical: 24.0,
      ),
      alignment: widget.horizontal
          ? FractionalOffset.centerRight
          : FractionalOffset.center,
      child: MaterialButton(
        padding: EdgeInsets.fromLTRB(0.0, 0.0, 0.0, 0.0),
        shape:
            RoundedRectangleBorder(borderRadius: BorderRadius.circular(100.0)),
        highlightColor: Colors.white,
        color: Colors.white,
        splashColor: Colors.red[800],
        height: 25.0,
        minWidth: 65.0,
        child: Icon(
          Icons.volume_up,
          size: 25.0,
        ),
        onPressed: () {
          _speak();
        },
      ),
    );

    final alphabetThumbnail = Container(
      margin: EdgeInsets.symmetric(
        vertical: 14.0,
        horizontal: 14.0,
      ),
      alignment: widget.horizontal
          ? FractionalOffset.centerLeft
          : FractionalOffset.center,
      child: Hero(
        tag: "Alphabet-hero-${widget.alphabet.id}",
        child: Image(
          image: AssetImage(widget.alphabet.image),
          height: 72.0,
          width: 72.0,
        ),
      ),
    );

    final alphabetCardContent = Container(
      margin: EdgeInsets.fromLTRB(widget.horizontal ? 10.0 : 16.0,
          widget.horizontal ? 16.0 : 42.0, 16.0, 16.0),
      constraints: BoxConstraints.expand(),
      child: Column(
        crossAxisAlignment: widget.horizontal
            ? CrossAxisAlignment.center
            : CrossAxisAlignment.center,
        children: <Widget>[
          Container(height: 20.0),
          Text(
            widget.alphabet.letter,
            style: TextStyle(
                fontFamily: 'Oswald',
                fontSize: 18.0,
                fontWeight: FontWeight.bold,
                color: Colors.red[800]),
          ),
          // Divider(
          //   color: Colors.white,
          //   height: 5.0,
          // ),
          // Container(height: 4.0),
          // Text(
          //   widget.alphabet.meaning,
          //   style: TextStyle(
          //       fontSize: 10.0,
          //       fontWeight: FontWeight.bold,
          //       color: Colors.blue[800]),
          // ),
        ],
      ),
    );

    final alphabetCard = Container(
      child: alphabetCardContent,
      height: widget.horizontal ? 100.0 : 150.0,
      margin: widget.horizontal
          ? EdgeInsets.fromLTRB(50.0, 0.0, 30.0, 0.0)
          : EdgeInsets.only(top: 72.0),
      decoration: BoxDecoration(
        color: Colors.yellow[50],
        shape: BoxShape.rectangle,
        borderRadius: BorderRadius.circular(16.0),
        boxShadow: <BoxShadow>[
          BoxShadow(
            color: Colors.black26,
            blurRadius: 10.0,
            offset: Offset(0.0, 10.0),
          ),
        ],
      ),
    );

    return Container(
      margin: const EdgeInsets.fromLTRB(0.0, 4.0, 16.0, 16.0),
      child: Stack(
        children: <Widget>[
          alphabetCard,
          alphabetThumbnail,
          alphabetSound,
        ],
      ),
    );
  }
}


Here is the Full Error -

E/flutter ( 4191): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method 'speak' was called on null.
E/flutter ( 4191): Receiver: null
E/flutter ( 4191): Tried calling: speak("А а")
E/flutter ( 4191): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:50:5)
E/flutter ( 4191): #1      _AlphabetRowState._speak 
package:easelang/widgets/alphabet_row.dart:87
E/flutter ( 4191): <asynchronous suspension>
E/flutter ( 4191): #2      _AlphabetRowState.build.<anonymous closure>
E/flutter ( 4191): #5      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:166
E/flutter ( 4191): #6      TapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:240
E/flutter ( 4191): #7      TapGestureRecognizer.acceptGesture 
package:flutter/…/gestures/tap.dart:211
E/flutter ( 4191): #8      GestureArenaManager.sweep 
package:flutter/…/gestures/arena.dart:156
E/flutter ( 4191): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:225
E/flutter ( 4191): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:199
E/flutter ( 4191): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:156
E/flutter ( 4191): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:102
E/flutter ( 4191): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:86
E/flutter ( 4191): #14     _rootRunUnary  (dart:async/zone.dart:1136:13)
E/flutter ( 4191): #15     _CustomZone.runUnary  (dart:async/zone.dart:1029:19)
E/flutter ( 4191): #16     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:931:7)
E/flutter ( 4191): #17     _invoke1  (dart:ui/hooks.dart:233:10)
E/flutter ( 4191): #18     _dispatchPointerDataPacket  (dart:ui/hooks.dart:154:5)
E/flutter ( 4191):

**Comment by SSG111** [comment]
I can understand, It is difficult to troubleshoot the code without having the full app to test with. I am posting the code for this file too.
import 'package:easelang/Modals/Alphabets.dart';

This may be more helpful for you. Thank you for your help and patience.

```
class Alphabet {
  final String id;
  final String letter;
  final String meaning;
  final String image;

  const Alphabet({this.id, this.letter, this.meaning, this.image});
}

List<Alphabet> alphabets = [
  const Alphabet(
    id: "1",
    letter: "А а",
    meaning: "(ah)",
    image: "assets/img/alphabets.png"
  ),
  const Alphabet(
    id: "2",
    letter: "Б б",
    meaning: "(beh)",
    image: "assets/img/alphabets.png"
  ),
  const Alphabet(
    id: "3",
    letter: "В в",
    meaning: "(veh)",
    image: "assets/img/alphabets.png"
  ),
  const Alphabet(
    id: "4",
    letter: "Г г",
    meaning: "(geh)",
    image: "assets/img/alphabets.png"
  ),
  const Alphabet(
    id: "5",
    letter: "Д д",
    meaning: "(deh)",
    image: "assets/img/alphabets.png"
  ),
  const Alphabet(
    id: "6",
    letter: "Е е",
    meaning: "(yeh)",
    image: "assets/img/alphabets.png"
  ),
  const Alphabet(
    id: "7",
    letter: "Ё ё",
    meaning: "(yo)",
    image: "assets/img/alphabets.png"
  ),
  const Alphabet(
    id: "8",
    letter: "Ж ж",
    meaning: "(zheh)",
    image: "assets/img/alphabets.png"
  ),
];
```

**Comment by dlutton** [comment]
Is there a reason your _speak function is returning a `Future<dynamic>` rather than just a `Future`?

Also try returning the _speak method as a call back.
`onPressed: () => _speak()`

**Comment by SSG111** [comment]
Thank you for your suggestions. I have replaced both the codes but still getting the error when I press the button. 

```
E/flutter ( 5878): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method 'speak' was called on null.
E/flutter ( 5878): Receiver: null
E/flutter ( 5878): Tried calling: speak("В в")
E/flutter ( 5878): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:50:5)
E/flutter ( 5878): #1      _AlphabetRowState._speak 
package:easelang/widgets/alphabet_row.dart:87
E/flutter ( 5878): <asynchronous suspension>
E/flutter ( 5878): #2      _AlphabetRowState.build.<anonymous closure> 
package:easelang/widgets/alphabet_row.dart:126
E/flutter ( 5878): #3      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:511
E/flutter ( 5878): #4      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:566
E/flutter ( 5878): #5      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:166
E/flutter ( 5878): #6      TapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:240
E/flutter ( 5878): #7      TapGestureRecognizer.acceptGesture 
package:flutter/…/gestures/tap.dart:211
E/flutter ( 5878): #8      GestureArenaManager.sweep 
package:flutter/…/gestures/arena.dart:156
E/flutter ( 5878): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:225
E/flutter ( 5878): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:199
E/flutter ( 5878): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:156
E/flutter ( 5878): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:102
E/flutter ( 5878): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket 
E/flutter ( 5878): #14     _rootRunUnary  (dart:async/zone.dart:1136:13)
E/flutter ( 5878): #15     _CustomZone.runUnary  (dart:async/zone.dart:1029:19)
E/flutter ( 5878): #16     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:931:7)
E/flutter ( 5878): #17     _invoke1  (dart:ui/hooks.dart:233:10)
E/flutter ( 5878): #18     _dispatchPointerDataPacket  (dart:ui/hooks.dart:154:5)
E/flutter ( 5878):
```

**Comment by dlutton** [comment]
Also try moving FlutterTts flutterTts outside of initSpeak().
Something like this:

```
FlutterTts flutterTts;
 initSpeak() {
     flutterTts = FlutterTts();
```

If that doesn't work, I'll try to play around with the code a bit when I get home.

**Comment by SSG111** [comment]
Words are speaking. Thank you so much for your kind guidance. You have made a great plugin. 

I have tested on the phone and on the emulator with several languages before writing to you. And I am facing another issue now. On the emulator, only English words are speaking. And on the phone, English, and Hindi words are speaking. Those Languages which are written in Latin script(similar to English) i.e. French is also working fine.

Should I add this code to make other languages work? 

For example - Russian

````
List<dynamic> languages = await flutterTts.getLanguages;

await flutterTts.setLanguage("ru-RU");

await flutterTts.setSpeechRate(1.0);

await flutterTts.setVolume(1.0);

await flutterTts.setPitch(1.0);

await flutterTts.isLanguageAvailable("ru-RU");`
```

**Comment by dlutton** [comment]
Yes exactly, you'll need to set the language to the desired language and ensure the text is written in that language.   You'll also want to get the available languages available to you on the TTS engine to make sure you're using a support language.

**Comment by SSG111** [comment]
I have replaced this code -
```
Future _getLanguages() async {
    languages = await flutterTts.getLanguages;
    if (languages != null) setState(() => languages);
  }
```
with this code -
```
Future _getLanguages() async {
    languages = await flutterTts.getLanguages;
    await flutterTts.setLanguage("ru-RU");
    await flutterTts.setSpeechRate(1.0);
    await flutterTts.setVolume(1.0);
    await flutterTts.setPitch(1.0);
    await flutterTts.isLanguageAvailable("ru-RU");
    if (languages != null) setState(() => languages);
  }
```
The output is still the same- On the emulator, only English words are speaking. And on the phone, English, and Hindi words are speaking. Those Languages which are written in Latin script(similar to English) i.e. French is also working fine.

I am looking for language code from here [Supported voices and languages](https://cloud.google.com/text-to-speech/docs/voices)

And I have this TTS engine installed on phone and it supports Russian. [Google Text-to-Speech](https://play.google.com/store/apps/details?id=com.google.android.tts&hl=en)

Kindly guide me further.

**Comment by dlutton** [comment]
The _getLanguages should simply return languages, so the first code snippet you replaced is correct.  
```
Future _getLanguages() async {
    languages = await flutterTts.getLanguages;
    if (languages != null) setState(() => languages);
  }
```
You should run that and print out the languages to the console while debugging to view the available languages.

Whatever is returned to you from the _getLanguages call should be an allowable language you can use within the setLanguage method.

You don't need to set the volume, pitch, or speech rate when getting or setting languages.

The isLanguageAvailable method isn't necessary either as that simply returns a Boolean value as to whether or not your language code is supported.

**Comment by SSG111** [comment]
Thank you for your help and patience. I am trying this code -
```
Future _getLanguages() async {
    languages = await flutterTts.getLanguages;
    print(languages);
    await flutterTts.setLanguage("ru-RU");
  }
```
It doesn't make any difference, not even printed any languages in the console.

I have also tried this code, still not printed any language -
```
Future _getLanguages() async {
    languages = await flutterTts.getLanguages;
    print(languages);
    if (languages != null) setState(() => languages);
  }
```
When I printed languages in below code, it shows null -

```
Future _speak() async {
    if (widget.alphabet.letter != null) {
      if (widget.alphabet.letter.isNotEmpty) {
        var result = await flutterTts.speak(widget.alphabet.letter);
        print(widget.alphabet.letter);
        print(languages);
        if (result == 1) setState(() => ttsState = TtsState.playing);
      }
    }
  }

```

**Comment by dlutton** [comment]
you're retrieving the languages within your initState method so ensure to view the logging on a fresh state.  You can always try a fresh build with `flutter clean` and then `flutter run`.

You should be able to view the log in the console through your method.

```
Future _getLanguages() async {
    languages = await flutterTts.getLanguages;
    print(languages);
    if (languages != null) setState(() => languages);
  }
```

**Comment by SSG111** [comment]
Thanks a ton. The most pleasing moment when the Russian words started speaking. All the issues have been solved. You have been very helpful throughout the difficulty. I am very grateful for your kind gesture.

I added codes like this-

```
@override
  void initState() {
    super.initState();
    initSpeak();
    _getLanguages();
    _getVoices();
  }
```

And then -

```
Future _getLanguages() async {
    languages = await flutterTts.getLanguages;
    print(languages);
    await flutterTts.setLanguage("ru-RU");
    if (languages != null) setState(() => languages);
  }
```
