### ISSUE TITLE
Allow voice to be set to nil on ios (or set voice to the default)

### ISSUE THREAD

**Issue by bcaspe** [dlutton/flutter_tts#440]
## 🚀 Feature Requests
After setting the voice to a different value than the default, I would like to be able to clear the selected voice. 

I belive that simply providing a method clearVoice which sets self.voice to nil in SwiftFlutterTtsPlugin would work and setting the voice to default voice on android. I'm not sure about the other platforms. 

Mostly I would be interested in this due to this bug as I am using silent playback quite a bit in my app and .. setting the volume to 0 is not actually making the sound silent.

https://stackoverflow.com/questions/75753211/avspeechutterance-with-volume-zero-can-still-be-heard

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by dlutton** [comment]
clearVoice method was added in version 4.0.0

**Comment by bcaspe** [comment]
Awesome! Thanks!
