### ISSUE TITLE
Requesting to add Tamil, Sanskrit, Telugu, Kannada, Malayalam, Bengali - Indian Languages

### ISSUE THREAD

**Issue by RajaramTech** [dlutton/flutter_tts#454]
## 🚀 Feature Requests

In Flutter_tts, it would be great to have more Indian Languages which should include Tamil, Sanskrit, Telugu, Malayalam, Kannada, Bengali, Marathi, Gujarati. Right now, it supports only Hindi Language. 

### Contextualize the feature
It would be great to have a option in the synthesizeToFile Feature to save audio in different Indian languages.

### Describe the feature
Right now, we  dont have much Indian languages except Hindi to be supported in the Flutter_tts. It would be great to have more Indian Languages especially Tamil, Sanskrit, Telugu, Malayalam, Kannada, Marathi, Gujarati, Bengali and it would be helpful to have it in speak and as well synthesizetofile. 

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by dlutton** [comment]
I'm unable to add languages as this package uses the native TTS engines on each device.  The languages are dependent upon the TTS engine.
