### ISSUE TITLE
macOS - Unable to 

### ISSUE THREAD

**Issue by PushBackNeil** [dlutton/flutter_tts#456]
## 🐛 Bug Report

My macOS app crashed because I exceeded the max speechInput length, a subsequent call to getMaxSpeechInputLength whilst debugging gave me this exception MissingPluginException(No implementation found for method getMaxSpeechInputLength on channel flutter_tts.

### Expected behavior
return the getMaxSpeechInputLength
### Reproduction steps
try a getMaxSpeechInputLength call on macOS;
### Configuration

**Version:** 0.1.x

**Platform:** 
macOS 12.7.3 (Monterey)

**Comment by dlutton** [comment]
getMaxSpeechInputLength is only available on Android as the README suggests.
