### ISSUE TITLE
Error occurred with synthesizeToFile in Android 13

### ISSUE THREAD

**Issue by ossgoossgo** [dlutton/flutter_tts#457]
## 🐛 Bug Report

The error message encountered with synthesizeToFile is: 

E/TextToSpeech(17968): Opening file tts.wav failed
E/TextToSpeech(17968): java.io.FileNotFoundException: open failed: EROFS (Read-only file system)
E/TextToSpeech(17968): 	at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:342)
E/TextToSpeech(17968): 	at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:229)
E/TextToSpeech(17968): 	at android.speech.tts.TextToSpeech.synthesizeToFile(TextToSpeech.java:1899)
E/TextToSpeech(17968): 	at com.tundralabs.fluttertts.FlutterTtsPlugin.synthesizeToFile(FlutterTtsPlugin.kt:627)
E/TextToSpeech(17968): 	at com.tundralabs.fluttertts.FlutterTtsPlugin.onMethodCall(FlutterTtsPlugin.kt:320)
E/TextToSpeech(17968): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/TextToSpeech(17968): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/TextToSpeech(17968): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/TextToSpeech(17968): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/TextToSpeech(17968): 	at android.os.Handler.handleCallback(Handler.java:942)
E/TextToSpeech(17968): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/TextToSpeech(17968): 	at android.os.Looper.loopOnce(Looper.java:241)
E/TextToSpeech(17968): 	at android.os.Looper.loop(Looper.java:358)
E/TextToSpeech(17968): 	at android.app.ActivityThread.main(ActivityThread.java:8114)
E/TextToSpeech(17968): 	at java.lang.reflect.Method.invoke(Native Method)
E/TextToSpeech(17968): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/TextToSpeech(17968): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
D/TTS     (17968): Failed creating file : tts.wav

### Configuration
<img width="677" alt="截圖 2024-01-25 16 36 15" src="https://github.com/dlutton/flutter_tts/assets/28197067/5811fb15-cd74-441d-a6c8-6bbe9ac83a2f">

**Version:**
3.8.5

**Platform:** 
- [ ] :robot: Android

**Comment by baranidharanofficial** [comment]
Same issue for me also

**Comment by dlutton** [comment]
The latest 4.0.1 should resolve this issue.
