### ISSUE TITLE
Voice name not found: {name=Karen, locale=bn-BD}

### ISSUE THREAD

**Issue by emonxcode** [dlutton/flutter_tts#462]
## 💬 Questions and Help

Worked fine but suddenly not working.

**Comment by dlutton** [comment]
@emonxcode which device?  keep in mind this plugin uses the native Text to speech engine on each device, so the languages and voices are specific to the device's engine.

**Comment by emonxcode** [comment]
It's works fine but also getting this message in log.

**Comment by emonxcode** [comment]
Sorry, It's works fine but also getting this message in log. I'm closing
this issue from github, Thanks
