### ISSUE TITLE
add download  and  share Feature 

### ISSUE THREAD

**Issue by kalimaty** [dlutton/flutter_tts#463]
### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android

**Contextualize the feature.** 
Please add the feature of downloading audio to devices
And the feature of sharing audios on WhatsApp, Google Drive, Telegram, and email
Describe the feature
Provide download button and share button

Platforms affected (mark all that apply)
 📱 iOS
🤖 Android

**Comment by dlutton** [comment]
These features seem out of scope for the responsibility of this package.

**Comment by kalimaty** [comment]
import 'dart:io';
import 'dart:developer';
import 'package:external_path/external_path.dart';
import 'package:flutter/material.dart';
import 'package:flutter_tts/flutter_tts.dart';
import 'package:share_plus/share_plus.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../../../helper/permission_handler.dart';

enum TtsState { playing, stopped }

enum Voice { male, boy, female, girl }

class TtsProvider with ChangeNotifier {
  late FlutterTts flutterTts;
  Voice currentVoice = Voice.male;
  TtsState ttsState = TtsState.stopped;
  String currentWord = '';
  List<dynamic> allSounds = [];
  TtsProvider() {
    initTTsProvider();
  }

  void initTTsProvider() {
    flutterTts = FlutterTts();
    flutterTts.setStartHandler(() {
      ttsState = TtsState.playing;
      notifyListeners();
    });

    flutterTts.setCompletionHandler(() {
      ttsState = TtsState.stopped;
      notifyListeners();
    });

    flutterTts.setErrorHandler((msg) {
      ttsState = TtsState.stopped;
      notifyListeners();
    });

    flutterTts.getVoices.then((voices) {
      allSounds = voices.where((voice) => voice['locale'] == 'en-US').toList();
      notifyListeners();
    });

    SharedPreferences.getInstance().then((prefs) {
      final voiceString = prefs.getString('voice');
      //  اذا موجود صوت احفظه
      if (voiceString != null) {
        currentVoice =
            Voice.values.firstWhere((g) => g.toString() == voiceString);
        changeVoice(currentVoice);
      } else {
        // وان لم فخزن صوت
        flutterTts.setPitch(0.8);
        flutterTts
            .setVoice({'name': 'en-us-x-sfg#male_1-local', 'locale': 'en-US'});
      }
    });
  }

  Future<void> changeVoice(Voice vc) async {
    double pitch;
    String voice;
    switch (vc) {
      case Voice.male:
        pitch = 0.8;
        voice = 'en-us-x-sfg#male_1-local';
        break;
      case Voice.boy:
        pitch = 1.8;
        voice = 'en-us-x-sfg#male_1-local';
        break;
      case Voice.female:
        pitch = 1.0;
        voice = 'en-us-x-sfg#female_1-local';
        break;
      case Voice.girl:
        pitch = 1.7;
        voice = 'en-us-x-sfg#female_1-local';
        break;
      default:
        pitch = 1.0;
        voice = 'en-US-language';
    }

    await flutterTts.setPitch(pitch);
    await flutterTts.setVoice({'name': voice, 'locale': 'en-US'});
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('voice', vc.toString());
    currentVoice = vc;
    notifyListeners();
  }

  Future<void> speak(String word) async {
    if (ttsState == TtsState.stopped) {
      currentWord = word;
      await flutterTts.speak(word);
    } else if (ttsState == TtsState.playing && currentWord == word) {
      await flutterTts.stop();
    }
  }

  bool isPlaying(String word) {
    return ttsState == TtsState.playing && currentWord == word;
  }

  Future<String> _getPathToDownload() async {
    final dir = await ExternalPath.getExternalStoragePublicDirectory(
      ExternalPath.DIRECTORY_DOWNLOADS,
    );
    return dir;
  }

  Future<bool> downloadVoice(String word, String wordId) async {
    try {
      final permissionHandler = PermissionHandler();
      final hasPermission = await permissionHandler.hasStoragePermission();

      if (!hasPermission) {
        final granted = await permissionHandler.requestStoragePermission();
        if (!granted) {
          throw Exception('Storage permission not granted');
        }
      }
      final directoryPath = await _getPathToDownload();
      final directory = Directory('$directoryPath/MyWords/');
      if (!await directory.exists()) {
        await directory.create(recursive: true);
      }
      final path = '${directory.path}$wordId.wav';
      if (await File(path).exists()) {
        return true;
      }
      await flutterTts
          .synthesizeToFile(word, path)
          .then((value) => log('Flutter TTS: $value'));
      return true;
    } catch (_) {
      return false;
    }
  }

  Future<void> shareVoice(String word, String wordId) async {
    try {
      final directoryPath = await _getPathToDownload();
      final directory = Directory('$directoryPath/MyWords/');
      if (!await directory.exists()) {
        await directory.create(recursive: true);
      }
      final path = '${directory.path}$wordId.wav';
      final file = XFile(path);

      if (await File(path).exists()) {
        await Share.shareFiles(
          [file.path],
          subject: 'Check out this audio file!',
          text: 'Sent from MyWords App',
        );
      } else {
        final downloadSuccess = await downloadVoice(word, wordId);
        if (downloadSuccess) {
          await Share.shareFiles(
            [file.path],
            subject: 'Check out this audio file!',
            text: 'Sent from MyWords App',
          );
        } else {
          log('Failed to download voice');
        }
      }
    } catch (e) {
      log('error: $e');
    }
  }
}

**Comment by kalimaty** [comment]
import 'package:device_info_plus/device_info_plus.dart';
import 'package:permission_handler/permission_handler.dart';

class PermissionHandler {
  Future<bool> requestStoragePermission() async {
    var status = await Permission.storage.status;
    var androidInfo = await DeviceInfoPlugin().androidInfo;

    if (androidInfo.version.sdkInt >= 30) {
      status = await Permission.manageExternalStorage.request();
    } else {
      status = await Permission.storage.request();
    }

    return status.isGranted;
  }

  Future<bool> hasStoragePermission() async {
    PermissionStatus status;
    var androidInfo = await DeviceInfoPlugin().androidInfo;
    if (androidInfo.version.sdkInt >= 30) {
      status = await Permission.manageExternalStorage.status;
    } else {
      status = await Permission.storage.status;
    }
    return status.isGranted;
  }
}

**Comment by kalimaty** [comment]
https://youtu.be/M6ct3Y2QtKM?si=0nxB90HQ1oIcxd_v

**Comment by kalimaty** [comment]
> These features seem out of scope for the responsibility of this package.
https://youtu.be/M6ct3Y2QtKM?si=0nxB90HQ1oIcxd_v
