### ISSUE TITLE
incompatible Kotlin versions

### ISSUE THREAD

**Issue by kip-too** [dlutton/flutter_tts#479]
### Reproduction steps

1. Add the `flutter_tts` package to a Flutter project.
2. Use the package in the project, for example, by initializing and using the `FlutterTts` object.
3. Attempt to build the project, and observe the error related to incompatible Kotlin versions.

### Configuration

**Version:** 4.0.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by dlutton** [comment]
@kip-too please follow this issue/thread or steps on getting this working for you.
https://github.com/dlutton/flutter_tts/issues/469

**Comment by kip-too** [comment]
I upgraded ext. Kotlin_version to '1.9.23' but it did not solve the
problem.

**Comment by dlutton** [comment]
@kip-too please follow the steps outlined here -> https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply, this should resolve any issues related to Kotlin version mismatches. I did create a new flutter project and brought this plugin in and after applying the changes from that flutter link, it fixed the issue.  If your project is open source, I can take a look and help you out if you'd like.
