### ISSUE TITLE
is Arabic language not Supported ?

### ISSUE THREAD

**Issue by basharbachir** [dlutton/flutter_tts#50]
## 🐛 Bug Report

await flutterTts.setLanguage("ar-sa");
// or
await flutterTts.setLanguage("ar-ar");
// or
await flutterTts.setLanguage("ar-eg");

### Expected behavior
Arabic language is not available
### Reproduction steps
print(await flutterTts.isLanguageAvailable('ar-sa')); // false  = ar-eg, ar-a.
### Configuration

**Version:** 0.1.x
0.2.6
**Platform:** 
- [ ] :robot: Android

**Comment by dlutton** [comment]
This all depends on the Google TTS Engine com.google.android.tts.

If the engine supports that language, then it'll work.  You should try the getLanguages() method to view the list of available languages on your device.

**Comment by visualo** [comment]
@basharbachir did you found a solution to add the Arabic language for TTS?
