### ISSUE TITLE
getVoices Android

### ISSUE THREAD

**Issue by Ryannc95** [dlutton/flutter_tts#516]
## 💬 Questions and Help

Hi,

I'm only getting 6x results for getVoices on Android (and only 2x English), is this all there is? My android emulator and flutter web both return many more.

Android version is 14 and I'm using flutter_tts 4.0.2, min sdk 24

I thought I had used other voices on my physical android device before

Thanks
Ryan

**Comment by Ryannc95** [comment]
The voices returned are:

name: es-MX-default, locale: spa-default
name: pt-BR-SMTf00, locale: por-x-lvariant-f00
name: en-US-default, locale: eng-default
name: pt-BR-default, locale: por-default
name: es-MX-SMTf00, locale: spax-x-lvariant-f00
name: en-US-SMTf00, locale: eng-x-lvariant-f00

**Comment by echogit** [comment]
There is definitelly many more. Which device are you using? Which engine did you select?

**Comment by Ryannc95** [comment]
Ah.. the engine was defaulting to com.samsung.smt. Setting to com.google.android.tts has solved my issues. Thanks!

**Comment by zicas2000** [comment]
> Ah.. the engine was defaulting to com.samsung.smt. Setting to com.google.android.tts has solved my issues. Thanks!

Can you please tell me where to edit this value ?

**Comment by echogit** [comment]
> Ah.. the engine was defaulting to com.samsung.smt. Setting to com.google.android.tts has solved my issues. Thanks!

Bare in mind that some mobiles don't have Google's engine installed.
