### ISSUE TITLE
Can't change language in iOS

### ISSUE THREAD

**Issue by nguyenlinhnttu** [dlutton/flutter_tts#52]
## 🐛 Bug Report

Hi  Friend
I my app i use two language en-us, en-gb
When i call func speak() and use  
`await flutterTts.setLanguage(language);`
But it not work in iOS, and work fine in android.

Hope you check it.
Thanks.
### Configuration

**Version:** 0.1.x

**Platform:** 
- [v] :iphone: iOS
- [ ] :robot: Android

**Comment by dlutton** [comment]
@nguyenlinhnttu I have tested on iOS and it's working.  You may want to use getLanguages to view the languages that are available.  Please make sure you're using "en-US" rather than "en-us" and "en-GB" rather than "en-gb" as the region needs to be uppercase.

**Comment by joknjokn** [comment]
You did you make it work for iOS? Our app can't build for iOS after adding TTS, Android works. Some Swift-error. (I don't have the error message here, sorry).

**Comment by dlutton** [comment]
Please open a new issue with the error message you're receiving @joknjokn .
