### ISSUE TITLE
Callback registered in ttsInitHandler is never called

### ISSUE THREAD

**Issue by Dimous** [dlutton/flutter_tts#53]
### Expected behavior
```
this._flutterTts = FlutterTts();
this._flutterTts.ttsInitHandler(() {
print("init");
});
```
I expect it to output "init" in the console.

_Callbacks registered in other handlers `setStartHandler`/`setCompletionHandler` are called when `speak` is called._

### Configuration
**Version:** 0.2.6

**Android:** 5.1.1
**Flutter:** git master `83a8a575eed882c49b629effedf7c95b6184515d`
**TTS engine:** `com.google.android.tts/com.google.android.tts.service.GoogleTTSService`

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by dlutton** [comment]
@Dimous I tested it out on API level 28 using the example in this repo and it's working for me.  Which Android API version are you using?

**Comment by Dimous** [comment]
Hello!

```
compileSdkVersion 29
minSdkVersion 19
targetSdkVersion 29
```
**Device:** Samsung Galaxy J3

**Comment by Dimous** [comment]
I set tts parameters _(pitch, volume, language)_ right after `FlutterTts` instantiation and they are applied, so, actually, I don't need `ttsInitHandler`. It doesn't affect usability, as speech is working. _It is not a problem for me._
