### ISSUE TITLE
Whether to support mixed Speech of two languages

### ISSUE THREAD

**Issue by charlescwx** [dlutton/flutter_tts#54]
## 🚀 Feature Requests
Whether to support mixed Speech of two languages

For example: English and Chinese are in a paragraph. If I set the English mode, the voice cannot read another language correctly.
Text case: 'test，测试'(测试 is Chinese after translation)

**Comment by charlescwx** [comment]
![image](https://user-images.githubusercontent.com/43430499/63237857-3c977880-c276-11e9-9604-2b203e7b519b.png)

The above screenshot can only read ‘test’ correctly, and the latter Chinese cannot be read. It cannot be identified.

**Comment by dlutton** [comment]
@charlescwx I don't believe this is a feature supported by the Android or IOS TTS engines and might be outside the scope of what TTS does.  This sounds more like language detection which automatically switches the TTS language it's using.  If you have located something in either the android or ios speech package that would allow this, I'd be happy to look into it.

**Comment by charlescwx** [comment]
Okay thank you
