### ISSUE TITLE
Move to AndroidX

### ISSUE THREAD

**Issue by shaxxx** [dlutton/flutter_tts#62]
## 🚀 Feature Requests

Please move Android project to AndroidX

### Describe the feature
Google Play Store started warning users that their app must switch to new Google Play API 3 until December 1st. Please move your project to AndroidX. This should be trivial with Android studio.

More info:
https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [x ] :robot: Android

**Comment by dlutton** [comment]
Thanks for the information @shaxxx, I'll look into migrating this project to AndroidX.
