### ISSUE TITLE
Speak without stopping background audio playback

### ISSUE THREAD

**Issue by alexandergottlieb** [dlutton/flutter_tts#68]
## 🚀 Feature Requests

It would be great if this package didn't interfere with music playback (or other background audio) on iOS.

### Contextualize the feature

Currently, as `FlutterTts` initialises, it pauses any currently playing music (from eg. Spotify). This happens even if `_textToSpeech.speak()` is never called, so sometimes the background audio is stopped unnecessarily providing an odd UX.

### Describe the feature

- don't stop background audio when initialising `FlutterTts`
- provide an API to speak _without_ stopping the background audio
- ideally, lower the volume of the background audio slightly while speaking

If this isn't possible, it would be good not to stop the background audio until the first time `_textToSpeech.speak()` is called.

Thanks so much for your hard work on this package!

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [ ] :robot: Android (haven't tested)

**Comment by JonasJW** [comment]
I agree, that feature is very important and it works on android out of the box. I don't know a lot of iOS development, is that possible?

**Comment by meowofficial** [comment]
It would be very nice if this feature gets provided.

**Comment by dlutton** [comment]
@meowofficial @JonasJW @alexandergottlieb this should now be resolved thanks to the PR from @marcotta.

**Comment by alexandergottlieb** [comment]
Just tested and it's working perfectly (iOS 13.3) - thanks!
