### ISSUE TITLE
Version solving failed.

### ISSUE THREAD

**Issue by Henry667** [dlutton/flutter_tts#77]
### Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.37.1)
[✓] Connected device (1 available)

• No issues found!

**Version:**v1.12.13+hotfix.5

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android Redmi note 6 Pro(android-arm64) 

Compiler issue
Because flutter_tts 0.8.5 requires Flutter SDK version >=1.10.0 <2.0.0 and no versions of flutter_tts match >0.8.5 <0.9.0, flutter_tts ^0.8.5 is forbidden.

So, because inshortsclone depends on flutter_tts ^0.8.5, version solving failed.
pub get failed (1)
exit code 1

**Comment by dlutton** [comment]
@Henry667 I'm not receiving that error while using the stable channel.  Does the latest version fix this error you're receiving?  Also I'm not sure what inshortsclone is.
