### ISSUE TITLE
Recording to a file for web

### ISSUE THREAD

**Issue by AbhishekPantUK** [dlutton/flutter_tts#79]
## 🚀 Feature Requests

Can we add a feature to record text to speech to a mp3 or wav file?
Is it possible?
Thanks

**Comment by adityaddy** [comment]
Is there any update on this feature?

**Comment by dlutton** [comment]
This is a feature that is probably out of scope for this package.  When reviewing the web speech API, android speech API, and iOS, none of them include a recording option.  This might be better off as a separate package.

**Comment by dlutton** [comment]
@adityaddy and @AbhishekPantUK I have added a very basic synthesizeToFile method for android only at this time.  It takes in the text and filename you want it saved as.  Please test when you have a moment.
