### ISSUE TITLE
API doesn't account for non-unique voice names on iOS

### ISSUE THREAD

**Issue by Lx** [dlutton/flutter_tts#80]
## 🐛 Bug Report

Where iOS devices have multiple voices with the same name (e.g. Daniel en-GB and Daniel fr-FR), it is only possible to select one and not the others.

### Expected behavior

Voice selection should occur by some mechanism other than name (which is demonstrably not guaranteed to be unique).

Ideally, `flutter_tts` would return more information about each voice, perhaps as a `Voice` object, including a unique ID (`Voice.identifier` in the case of iOS and `Voice.name` in the case of Android), a display name (`Voice.name` in the case of iOS and `null` or `Voice.name` again in the case of Android), and locale information (e.g. `en-AU`, available from both underlying platforms per voice).

If `flutter_tts` returned `Voice` objects in response to `getVoices`, those objects could be passed back in later calls to `setVoice`.

### Reproduction steps

1.  Have an iOS device with two Daniels (one en-GB, one fr-FR).
2.  Attempt to speak using French Daniel™ and observe that British Daniel utters instead.

### Configuration

**Version:** 0.8.6

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by dlutton** [comment]
Sorry for the delay, @Lx , when you get a moment, can you test this PR to see if it works for what you're requesting? #177. If you need assistance on pulling in this dependency using a certain branch, you can look here (https://flutter.dev/docs/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages).  Use the ref argument to pin the branch you want to use.  In this case, that ref is `voice_enhancement`.  If it all works, I'll merge in the code and update the version number.  

Also, note that the method now returns a map of name and locales so when you set it, you'll do something like this `await flutterTts.setVoice({"name": "Karen", "locale": "en-AU"});`

I'm not a heavy user of the voices, so let me know if you'd like this set a different way and I can make the adjustment.
