### ISSUE TITLE
select voice

### ISSUE THREAD

**Issue by toshiossada** [dlutton/flutter_tts#82]
How could I set another voice to TTS?

**Comment by dlutton** [comment]
I'm sorry but can you be a little more specific?  Are you having an issue with setting another voice?

**Comment by toshiossada** [comment]
by default is a female voice, I'd like to set a male voice

**Comment by toshiossada** [comment]
I think is await flutterTts.setVoice('pt-br-x-afs#male_3-local'); right?

**Comment by toshiossada** [comment]
but I think this isnt works on iOS, has any other way?

**Comment by dlutton** [comment]
You can also return voices for iOS.  It doesn't guarantee that there will be both a female and male voice for each language.

**Comment by MurtuzaSrashtaSoft** [comment]
i set this voice but still speak male voice **en-gb-x-afx#female_1-local**

**Comment by shinriyo** [comment]
wher the list?
