### ISSUE TITLE
Can't run app on iOS

### ISSUE THREAD

**Issue by NickalasB** [dlutton/flutter_tts#83]
## 💬 Questions and Help

I'm building a very simple app that is working fine on Android. When I try to install it on an iOS simulator through Anroid Studio's run button or `flutter run` from the command line- the build fails. 
I've tried running `flutter pub cache repair` and re-running `packages-get` as well as just deleting the ` /Users/####/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_tts-0.8.6` file but still no luck.

Any help would be greatly appreciated. 

flutter version = `1.12.13+hotfix.5`
plugin version = `flutter_tts: ^0.8.6`
Swift version = `Apple Swift version 5.1.3`
CocoaPods version = `1.7.5`

Here's the output I get
```

Xcode build done.                                            1.6s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/####/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_tts-0.8.6/ios/Classes/FlutterTtsPlugin.m:2:9: fatal error: 'flutter_tts/flutter_tts-Swift.h' file not found
    #import <flutter_tts/flutter_tts-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning build
    note: Constructing build description
```

**Comment by dlutton** [comment]
@NickalasB this looks related to issue #9 .  Let me know if this helps solve the issue you're having.

**Comment by NickalasB** [comment]
Yes I guess I just didn't check the right checkbox when creating my project through Android Studio. Mine was new enough to just start over. Not sure if it's worth adding something about that to your ReadMe but if people plan to make a project using this plugin they should make sure to check the `Include Swift support for iOS code` checkbox when starting out. 

Thank you. Problem fixed

<img width="798" alt="Screen Shot 2020-01-27 at 4 27 48 PM" src="https://user-images.githubusercontent.com/16969303/73226708-dcaad500-4125-11ea-83b3-d5212439c24c.png">
