### ISSUE TITLE
API support for Speech Stream to a file

### ISSUE THREAD

**Issue by afzaal-ahmad-zeeshan** [dlutton/flutter_tts#86]
## 🚀 Feature Requests
I am requesting to add the support for an API that lets the developers capture the speech stream generated by Android speech API. I have an application running on Android (you can find it on Google Play [here](https://play.google.com/store/apps/details?id=com.wordpress.afzaalahmadzeeshan.speakitapp)) that allows the users to save the speech stream as a local file. 

If `flutter_tts` can expose an API that takes a file as a parameter and fills it with the bytes for the media generated by native speech APIs, it would be amazing.

### Contextualize the feature
It allows the developers to generate a file of the speech and manually control the media playback. The current state only allows the developer to speak or stop the speech. This improved API will enable the developers to run the speech at their own pace (actually at the pace of the user). This will improve the app UX.

### Describe the feature
Check out the Android documentation for this, [TextToSpeech](https://developer.android.com/reference/android/speech/tts/TextToSpeech).

This is the method that I am specifically talking about,[ `synthesizeToFile()`](https://developer.android.com/reference/android/speech/tts/TextToSpeech#synthesizeToFile(java.lang.CharSequence,%20android.os.Bundle,%20java.io.File,%20java.lang.String)).

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS (if possible, I have not worked with iOS yet)
- [x] :robot: Android

**Comment by dlutton** [comment]
@afzaal-ahmad-zeeshan I have added a very basic synthesize to file feature to this package.  Please test it when you have a moment.  It takes in the text and the filename you want it saved as.  Let me know if you have any questions or additional functionality you'd like to see with this feature and I'll build upon the simple implementation.  Also don't forget that you'll need to request storage permissions through your android manifest file.

**Comment by afzaal-ahmad-zeeshan** [comment]
Not sure if this is related to this issue or not. But I tried your recent update to the package and it seems to return, "Reply already submitted" with the speaking function. 

```
E/MethodChannel#flutter_tts(20430): Failed to handle method call
E/MethodChannel#flutter_tts(20430): java.lang.IllegalStateException: Reply already submitted
E/MethodChannel#flutter_tts(20430): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:148)
E/MethodChannel#flutter_tts(20430): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.notImplemented(MethodChannel.java:244)
E/MethodChannel#flutter_tts(20430): 	at com.tundralabs.fluttertts.FlutterTtsPlugin.onMethodCall(FlutterTtsPlugin.java:176)
E/MethodChannel#flutter_tts(20430): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#flutter_tts(20430): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/MethodChannel#flutter_tts(20430): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/MethodChannel#flutter_tts(20430): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_tts(20430): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#flutter_tts(20430): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#flutter_tts(20430): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#flutter_tts(20430): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_tts(20430): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#flutter_tts(20430): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/DartMessenger(20430): Uncaught exception in binary message listener
E/DartMessenger(20430): java.lang.IllegalStateException: Reply already submitted
E/DartMessenger(20430): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:148)
E/DartMessenger(20430): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:249)
E/DartMessenger(20430): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/DartMessenger(20430): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/DartMessenger(20430): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/DartMessenger(20430): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/DartMessenger(20430): 	at android.os.Looper.loop(Looper.java:160)
E/DartMessenger(20430): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/DartMessenger(20430): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(20430): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/DartMessenger(20430): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
The file part I need to check yet, it gives the error for the path not existing (seems the path, including directory needs to be created before the call).

**Comment by afzaal-ahmad-zeeshan** [comment]
Here is the code that I have used for the synthesis of speech to file, 

```
var directoryPath = "${(await getApplicationDocumentsDirectory()).path}/audio/";
var directory = Directory(directoryPath);
if(!await directory.exists()) {
  await directory.create();
  print('[INFO] Created the directory');
}

var path = "${(await getApplicationDocumentsDirectory()).path}/audio/${uuid.v4()}.wav";
print('[INFO] path: $path');
var file = File(path);
if(!await file.exists()) {
  await file.create();
  print('[INFO] Created the file');
}
service.synthesizeToFile(sentence, file.path);
``` It gives the error "Failed creating file."

**Comment by dlutton** [comment]
What's the filename you're passing?  try just passing a file name as "test.wav" to start out with.  It should create the file for you.

**Comment by afzaal-ahmad-zeeshan** [comment]
I am using a UUID to be generated for the files.

Secondly, I have just checked, your version 0.8.7 speaks properly, but 0.9.0 fails to speak and gives the error that "Reply already submitted". Maybe you should check that.

For the file, sure I will try passing a file name (without creating a file first).

**Comment by dlutton** [comment]
thanks @afzaal-ahmad-zeeshan, the error should no longer be occurring.
