### ISSUE TITLE
Using instance second time doesn't work (iPhone)

### ISSUE THREAD

**Issue by prantto** [dlutton/flutter_tts#87]
I'm using the flutter tts plugin in my small App. It really worked fine. I always tested every function on the iPhone 11 pro max simulator and the app worked. But now I wanted to test the App on a real iPhone and I always have the same issue on 3 different iPhones. The second time the plugin is called, it doesn't 'speak'. I'm using always the same instance now (singleton), but this doesn't fixed the issue. 

My App is a simple App. The first time flutter tts says that you have to speak something, then the speech recognition plugin is called. After that I use the same flutter tts instance, which should speak the content what was found to the spoken word. But this second it doesn't speaks at the real phones. On the simulator everything works fine. 
Somebody having the same issue? and maybe a work around.

**Comment by dlutton** [comment]
@prantto I haven't tried using this plugin with speech recognition.  Does this issue exist with the example provided in repo on a real device?

**Comment by prantto** [comment]
The example App works fine on the iPhone. Maybe there is a problem if you use both plugins. But I don't understand why it is working fine on the simulator. 
I just saw that there is another speech to text plugin now. Maybe I try if this one is working better.

**Comment by dlutton** [comment]
Are you able to provide your codebase or a sample of your code and the other plugin your'e using? There could be a conflict between the 2 plugins.

**Comment by prantto** [comment]
Hey. Yeah seems like there is a conflict. I can't provide the code, but I build a simple app that shows the problem. I use this plugin: speech_recognition: ^0.3.0+1; but also tested it with the other one speech_to_text: ^1.0.0. Same issue working on Simulator, but not on the phone.

`import 'package:flutter/material.dart';
import 'Voice.dart';



void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: VoiceHome(),
    );
  }
}`
`import 'package:flutter/material.dart';
import 'package:flutter_tts/flutter_tts.dart';
import 'package:speech_recognition/speech_recognition.dart';

class VoiceHome extends StatefulWidget {
  @override
  _VoiceHomeState createState() => _VoiceHomeState();
}

class _VoiceHomeState extends State<VoiceHome> {
  SpeechRecognition _speechRecognition;
  bool _isAvailable = false;
  bool _isListening = false;

  String resultText = "hallo";

  @override
  void initState() {
    super.initState();
    initSpeechRecognizer();
  }

  void initSpeechRecognizer() {
    _speechRecognition = SpeechRecognition();

    _speechRecognition.setAvailabilityHandler(
          (bool result) => setState(() => _isAvailable = result),
    );

    _speechRecognition.setRecognitionStartedHandler(
          () => setState(() => _isListening = true),
    );

    _speechRecognition.setRecognitionResultHandler(
          (String speech) => setState(() => resultText = speech),
    );

    _speechRecognition.setRecognitionCompleteHandler(
          () => setState(() => _isListening = false),
    );

    _speechRecognition.activate().then(
          (result) => setState(() => _isAvailable = result),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: <Widget>[
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                FloatingActionButton(
                  child: Icon(Icons.cancel),
                  mini: true,
                  backgroundColor: Colors.deepOrange,
                  onPressed: () {
                    if (_isListening)
                      _speechRecognition.cancel().then(
                            (result) => setState(() {
                          _isListening = result;
                          resultText = "";
                        }),
                      );
                  },
                ),
                FloatingActionButton(
                  child: Icon(Icons.mic),
                  onPressed: () {
                    if (_isAvailable && !_isListening)
                      _speechRecognition
                          .listen(locale: "de_DE")
                          .then((result) => print('$result'));
                  },
                  backgroundColor: Colors.pink,
                ),
                FloatingActionButton(
                  child: Icon(Icons.stop),
                  mini: true,
                  backgroundColor: Colors.deepPurple,
                  onPressed: () {
                    if (_isListening)
                      _speechRecognition.stop().then(
                            (result) => setState(() => _isListening = result),
                      );
                  },
                ),
                FloatingActionButton(
                  child: Icon(Icons.volume_up),
                  mini: true,
                  backgroundColor: Colors.deepPurple,
                  onPressed: () {
                   FlutterTts flutterTts = new FlutterTts();
                   flutterTts.setLanguage("en-US");
                   flutterTts.speak(resultText);
                  },
                ),
              ],
            ),
            Container(
              width: MediaQuery.of(context).size.width * 0.8,
              decoration: BoxDecoration(
                color: Colors.orangeAccent[100],
                borderRadius: BorderRadius.circular(6.0),
              ),
              padding: EdgeInsets.symmetric(
                vertical: 8.0,
                horizontal: 12.0,
              ),
              child: Text(
                resultText,
                style: TextStyle(fontSize: 24.0),
              ),
            )
          ],
        ),
      ),
    );
  }
}`

I put in the default string "hallo". If you tap on the speaker button it speaks hallo. But if you tap on the mic button speak a word and then tap the speaker button. it speaks nothing. 

I also tried the tts_improved plugin. After the recognition it shows me the text output on the screen, but don't speaks.

Thanks for helping me:)

**Comment by dlutton** [comment]
Sorry I haven't had a chance to research this yet.  Have you tried creating the instance of FlutterTts at the top similar to what you're doing with SpeechRecognition _speechRecognition;  So create the FlutterTts _flutterTts at the top and then instantiate it within your initState the same way.  Update your onpressed method to call the _flutterTts you created at the top.  Please let me know if that works.

**Comment by prantto** [comment]
I already changed to the other plugin SpeechToText, this is now working for my app. 
Thanks for your help:)
