### ISSUE TITLE
Can pause the voice?

### ISSUE THREAD

**Issue by Dorbmon** [dlutton/flutter_tts#89]

**Comment by dlutton** [comment]
I don't believe the android tts api provides a pause method.
https://developer.android.com/reference/android/speech/tts/TextToSpeech.html

If you find a way to accomplish this, let me know and I'll implement it.

**Comment by Dorbmon** [comment]
> I don't believe the android tts api provides a pause method.
> https://developer.android.com/reference/android/speech/tts/TextToSpeech.html
> 
> If you find a way to accomplish this, let me know and I'll implement it.

I found setSlience does the same work.

**Comment by ajay-ackerman** [comment]
> 

then how will you resume it again?
