### ISSUE TITLE
Flutter_TTS issue in iOS

### ISSUE THREAD

**Issue by osamasabir** [dlutton/flutter_tts#9]
## 💬 Questions and Help

hi,
its my first flutter app ... i don't know much about iOS and Flutter thats why i am asking here

why i am getting that error ??
i tried that package with Swift/C++ support option..
anyone help me out ??

![46908713-5d998980-cf40-11e8-83f7-4bc7d36e6e7e](https://user-images.githubusercontent.com/17942396/47111205-5211cf80-d26c-11e8-8e13-cfee61e45c51.png)

i am stuck here.. please guide me :(

**Comment by dlutton** [comment]
When you first created your project, did you create it with the swift flag such as `flutter create -i swift newProject`?

**Comment by osamasabir** [comment]
Sir,
i have created that project in android studio..
i tried with both options .. 
like first time i have checked the swift option.
and second time i choose the C# option.
in both conditions error remains the same..

**this one is with "C#" option..**

**Comment by osamasabir** [comment]
okay i will try with swift option again and let you know..

**Comment by osamasabir** [comment]
Thanks .. it is working with swift option...
