### ISSUE TITLE
Can I call text to speech without connect to Google?

### ISSUE THREAD

**Issue by hoangquy4897** [dlutton/flutter_tts#91]
My network device is behind proxy so my device cannot connect to Google to call text to speech with this package. Is there anyway I can do it offline?

**Comment by dlutton** [comment]
For Android, this plugin uses the standard `com.google.android.tts` TTS engine.  As far as I know, this shouldn't require internet connection unless you need to download the engine.  Are you running into an issue where this is not working without internet connection?

**Comment by hydralien** [comment]
@dlutton it seems like it doesn't work in offline, unless the language is installed on device. It's probably not an easy thing to solve, but something to be aware of.
