### ISSUE TITLE
Interaction with audio input

### ISSUE THREAD

**Issue by ab36245** [dlutton/flutter_tts#94]
I have a question about using this plugin in conjunction with speech recognition (microphone input). I am building a simple app which listens for speech input, processes it and generates a simple audio response and then listens for the next input. I'm using this plugin for the audio response and speech_to_text for the speech recognition.

The problem I have is that after generating the first audio output using this package the speech recognition software does not detect any input until it is restarted. I have described the problem in more detail in a speech_to_text issue (https://github.com/csdcorp/speech_to_text/issues/66).

The developer has asked whether the problem is related to flutter_tts changing the audio mode: 

> There might be a solution to this but it depends on some details of how iOS handles audio sessions that I'm not sure about. What I think is likely happening is that text to speech package you're using is changing the audio mode and not remembering the current mode when they do. Basically speech_to_text puts the audio into play and record during a listen session. If the text to speech changes the mode to play only when it speaks and then either doesn't reset the mode at all or resets it back to a default instead of the pre-existing mode, you'd get the behaviour you describe.

Is it possible that this is causing the problem? Is there a "best practice" way to use flutter_tts in conjunction with audio input?

Thanks!

**Comment by dlutton** [comment]
@ab36245 I went ahead and made a quick update to the audio session so it's set to playAndRecord rather than just play.  That should make it compatible with the audio session of the other package you're using.

**Comment by ab36245** [comment]
I've upgraded to 1.0.0 but still have the same problem (see csdcorp/speech_to_text#66).
