### ISSUE TITLE
Can't talk Chinese

### ISSUE THREAD

**Issue by 792266344** [dlutton/flutter_tts#95]
## 💬 Questions and Help

It can't talk chinese after setLanguage('zh-CN').

**Comment by dlutton** [comment]
Is there an error?  Is the text in Chinese?  Also, when you run the getLanguages method, is zh-CN a supported language on your phone?  I'm not sure which device you're testing on, however I quickly ran a test on the web version of this plugin [here](https://dlutton.github.io/flutter_tts).  When setting the language to zH-CN from the drop down and pasting in Chinese characters, it's speaking in Chinese.

**Comment by 792266344** [comment]
aha,I'm sorry,it haven't 'zh-CN' when I run the getLanguages,Thanks
