### ISSUE TITLE
TTS won't stop

### ISSUE THREAD

**Issue by coder-Aayush** [dlutton/flutter_tts#97]
## 🐛 Bug Report

While Playing Something with TTS when we close app from recent than the Plugin won't stop.
also, I have disposed, it won't work.

flutter_tts: ^0.9.1

**Platform:** 
Android

**Comment by dlutton** [comment]
@coder-Aayush is this still an issue?  I have tested in an emulator and it doesn't appear to be an issue.

**Comment by coder-Aayush** [comment]
I will check and confirm it...

**Comment by coder-Aayush** [comment]
@dlutton Ya issue  doesn't appear now. But when I press back action button the app crash. Can you check it.

**Comment by dlutton** [comment]
@coder-Aayush do you mind opening a new issue then with details of the app crash?  Thank you!
