### ISSUE TITLE
The background audio is stopped with speak completion on iOS device.

### ISSUE THREAD

**Issue by yoshoten-i-sol** [dlutton/flutter_tts#99]
## 💬 Questions and Help

Thank you for you hard work.

I'm not sure it's a issue.
The background audio is stopped when the speak completion on iOS device.
I'm creating a game app and using this plug in on it. I played the music on background and run the tts to speak something to user, but the music always stopped when the speak completion.
This issue always appeared on speak completion so I put some placeholder word after the content and using stop method on progress callback before placeholder to stop speaking now.
That's working well but maybe have any better way to solve this issue.

**Comment by wexder** [comment]
I open pull request for setting audio category and options. I feel like that should fix by choosing different audio category or option https://developer.apple.com/documentation/avfoundation/avaudiosession

**Comment by dlutton** [comment]
@yoshoten-i-sol the latest update has been published.
